In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_160124(12hdem)\thoitrangnam\aosomi"
os.listdir(path)

['.ipynb_checkpoints',
 'tk_aosomi.csv',
 'tk_aosomi_all.ipynb',
 'tk_ttnam_aosomi.ipynb',
 'tk_ttnam_aosomi_npage.ipynb',
 'tk_ttnam_aosomi_t10.csv',
 'tk_ttnam_aosomi_t11.csv',
 'tk_ttnam_aosomi_t12.csv',
 'tk_ttnam_aosomi_t13.csv',
 'tk_ttnam_aosomi_t14.csv',
 'tk_ttnam_aosomi_t15.csv',
 'tk_ttnam_aosomi_t16.csv',
 'tk_ttnam_aosomi_t17.csv',
 'tk_ttnam_aosomi_t18.csv',
 'tk_ttnam_aosomi_t19.csv',
 'tk_ttnam_aosomi_t2.csv',
 'tk_ttnam_aosomi_t20.csv',
 'tk_ttnam_aosomi_t21.csv',
 'tk_ttnam_aosomi_t22.csv',
 'tk_ttnam_aosomi_t23.csv',
 'tk_ttnam_aosomi_t24.csv',
 'tk_ttnam_aosomi_t25.csv',
 'tk_ttnam_aosomi_t26.csv',
 'tk_ttnam_aosomi_t27.csv',
 'tk_ttnam_aosomi_t28.csv',
 'tk_ttnam_aosomi_t29.csv',
 'tk_ttnam_aosomi_t3.csv',
 'tk_ttnam_aosomi_t30.csv',
 'tk_ttnam_aosomi_t31.csv',
 'tk_ttnam_aosomi_t32.csv',
 'tk_ttnam_aosomi_t33.csv',
 'tk_ttnam_aosomi_t34.csv',
 'tk_ttnam_aosomi_t35.csv',
 'tk_ttnam_aosomi_t36.csv',
 'tk_ttnam_aosomi_t37.csv',
 'tk_ttnam_aosomi_t38.csv',
 'tk_ttnam_aosomi_t39.csv',
 'tk_ttnam_aosomi_t4.csv',
 'tk_ttnam_aosomi_t40.csv',
 'tk_ttnam_aosomi_t41.csv',
 'tk_ttnam_aosomi_t42.csv',
 'tk_ttnam_aosomi_t43.csv',
 'tk_ttnam_aosomi_t44.csv',
 'tk_ttnam_aosomi_t45.csv',
 'tk_ttnam_aosomi_t46.csv',
 'tk_ttnam_aosomi_t47.csv',
 'tk_ttnam_aosomi_t48.csv',
 'tk_ttnam_aosomi_t49.csv',
 'tk_ttnam_aosomi_t5.csv',
 'tk_ttnam_aosomi_t50.csv',
 'tk_ttnam_aosomi_t6.csv',
 'tk_ttnam_aosomi_t7.csv',
 'tk_ttnam_aosomi_t8.csv',
 'tk_ttnam_aosomi_t9.csv']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_aosomi_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales,category
0,Áo sơ mi nam trắng chuẩn soái ca,159.000₫,https://tka.tiki.vn/pixel/pixel?data=sEVl1AIlJ...,1,-41%,Đã bán 38,aosomi
1,Áo sơ mi nam dài tay màu tím,159.000₫,https://tka.tiki.vn/pixel/pixel?data=oJ6AoBkNw...,2,-35%,Đã bán 23,aosomi
2,Áo sơ mi nam dài tay vải cotton mểm không nhăn,108.000₫,https://tka.tiki.vn/pixel/pixel?data=6x2qJ1eHq...,3,-31%,Đã bán 16,aosomi
3,Áo sơ mi nam dài tay kẻ caro trắng đen,159.000₫,https://tka.tiki.vn/pixel/pixel?data=RhTzapv_l...,4,-41%,Đã bán 14,aosomi
4,Áo sơ mi nam cổ trụ cài hêt cúc tay dài vài kh...,108.000₫,https://tka.tiki.vn/pixel/pixel?data=s6Dr93r7d...,5,-20%,Đã bán 2,aosomi
...,...,...,...,...,...,...,...
35,NaN,NaN,https://tiki.vn/ao-so-mi-nam-ao-so-mi-coc-tay-...,36,NaN,NaN,aosomi
36,Áo sơ mi nam ngắn tay a,195.000₫,https://tiki.vn/ao-so-mi-nam-ngan-tay-a-p25161...,37,NaN,Đã bán 3,aosomi
37,Áo Sơ Mi Nam Tay Ngắn Mẫu 1,228.000₫,https://tiki.vn/a-o-so-mi-nam-tay-ngan-ma-u-1-...,38,NaN,Đã bán 10,aosomi
38,ÁO SƠ MI TRẮNG NAM HỌA TIẾT HOA THƯ PHÁP,99.000₫,https://tiki.vn/ao-so-mi-trang-nam-hoa-tiet-ho...,39,NaN,Đã bán 9,aosomi
39,Áo Sơ Mi Nam Họa Tiết Vải Lụa Hàn Không Nhăn H...,299.000,https://tiki.vn/ao-so-mi-nam-hoa-tiet-vai-lua-...,40,NaN,Đã bán 4,aosomi

1. Xử lý dữ liệu

In [5]:
df_all = df_all.drop('index', axis=1)

In [6]:
df_all.dropna(subset=['sales'], inplace=True)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales,category
0,Áo sơ mi nam trắng chuẩn soái ca,159.000₫,https://tka.tiki.vn/pixel/pixel?data=sEVl1AIlJ...,-41%,Đã bán 38,aosomi
1,Áo sơ mi nam dài tay màu tím,159.000₫,https://tka.tiki.vn/pixel/pixel?data=oJ6AoBkNw...,-35%,Đã bán 23,aosomi
2,Áo sơ mi nam dài tay vải cotton mểm không nhăn,108.000₫,https://tka.tiki.vn/pixel/pixel?data=6x2qJ1eHq...,-31%,Đã bán 16,aosomi
3,Áo sơ mi nam dài tay kẻ caro trắng đen,159.000₫,https://tka.tiki.vn/pixel/pixel?data=RhTzapv_l...,-41%,Đã bán 14,aosomi
4,Áo sơ mi nam cổ trụ cài hêt cúc tay dài vài kh...,108.000₫,https://tka.tiki.vn/pixel/pixel?data=s6Dr93r7d...,-20%,Đã bán 2,aosomi
...,...,...,...,...,...,...
873,Áo Sơ Mi Nam Tay Dài Màu Trơn Thời Trang Poniv...,105.000₫,https://tiki.vn/ao-so-mi-nam-tay-dai-mau-tron-...,NaN,Đã bán 4,aosomi
874,Áo sơ mi nam ngắn tay a,195.000₫,https://tiki.vn/ao-so-mi-nam-ngan-tay-a-p25161...,NaN,Đã bán 3,aosomi
875,Áo Sơ Mi Nam Tay Ngắn Mẫu 1,228.000₫,https://tiki.vn/a-o-so-mi-nam-tay-ngan-ma-u-1-...,NaN,Đã bán 10,aosomi
876,ÁO SƠ MI TRẮNG NAM HỌA TIẾT HOA THƯ PHÁP,99.000₫,https://tiki.vn/ao-so-mi-trang-nam-hoa-tiet-ho...,NaN,Đã bán 9,aosomi
877,Áo Sơ Mi Nam Họa Tiết Vải Lụa Hàn Không Nhăn H...,299.000,https://tiki.vn/ao-so-mi-nam-hoa-tiet-vai-lua-...,NaN,Đã bán 4,aosomi

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0      159000
1      159000
2      108000
3      159000
4      108000
        ...
873    105000
874    195000
875    228000
876     99000
877    299000
Name: price, Length: 878, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0      38.0
1      23.0
2      16.0
3      14.0
4       2.0
       ...
873     4.0
874     3.0
875    10.0
876     9.0
877     4.0
Name: sales, Length: 878, dtype: float64

In [11]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0      6042000.0
1      3657000.0
2      1728000.0
3      2226000.0
4       216000.0
         ...
873     420000.0
874     585000.0
875    2280000.0
876     891000.0
877    1196000.0
Name: revenue, Length: 878, dtype: float64

In [12]:
total = df_all["revenue"].sum()

In [13]:
print("Tổng doanh số aosomi: ", total)
print("So mat hang da ban: ", len(df_all["title"])) # san pham da ban
print("So san pham da ban: ", df_all["sales"].sum()) # san pham co luot ban

Tổng doanh số aosomi:  3527633549.0
So mat hang da ban:  878
So san pham da ban:  22174.0

In [14]:
df_all

,title,price,link_item,discount,sales,category,revenue
0,Áo sơ mi nam trắng chuẩn soái ca,159000,https://tka.tiki.vn/pixel/pixel?data=sEVl1AIlJ...,-41%,38.0,aosomi,6042000.0
1,Áo sơ mi nam dài tay màu tím,159000,https://tka.tiki.vn/pixel/pixel?data=oJ6AoBkNw...,-35%,23.0,aosomi,3657000.0
2,Áo sơ mi nam dài tay vải cotton mểm không nhăn,108000,https://tka.tiki.vn/pixel/pixel?data=6x2qJ1eHq...,-31%,16.0,aosomi,1728000.0
3,Áo sơ mi nam dài tay kẻ caro trắng đen,159000,https://tka.tiki.vn/pixel/pixel?data=RhTzapv_l...,-41%,14.0,aosomi,2226000.0
4,Áo sơ mi nam cổ trụ cài hêt cúc tay dài vài kh...,108000,https://tka.tiki.vn/pixel/pixel?data=s6Dr93r7d...,-20%,2.0,aosomi,216000.0
...,...,...,...,...,...,...,...
873,Áo Sơ Mi Nam Tay Dài Màu Trơn Thời Trang Poniv...,105000,https://tiki.vn/ao-so-mi-nam-tay-dai-mau-tron-...,NaN,4.0,aosomi,420000.0
874,Áo sơ mi nam ngắn tay a,195000,https://tiki.vn/ao-so-mi-nam-ngan-tay-a-p25161...,NaN,3.0,aosomi,585000.0
875,Áo Sơ Mi Nam Tay Ngắn Mẫu 1,228000,https://tiki.vn/a-o-so-mi-nam-tay-ngan-ma-u-1-...,NaN,10.0,aosomi,2280000.0
876,ÁO SƠ MI TRẮNG NAM HỌA TIẾT HOA THƯ PHÁP,99000,https://tiki.vn/ao-so-mi-trang-nam-hoa-tiet-ho...,NaN,9.0,aosomi,891000.0
877,Áo Sơ Mi Nam Họa Tiết Vải Lụa Hàn Không Nhăn H...,299000,https://tiki.vn/ao-so-mi-nam-hoa-tiet-vai-lua-...,NaN,4.0,aosomi,1196000.0

In [15]:
df_all.to_csv("tk_aosomi_all_ed.csv")