In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_170124(12hdem) - Copy\thoitrangnam\aosomi"
os.listdir(path)

['.ipynb_checkpoints',
 'tk_aosomi.csv',
 'tk_aosomi_all.ipynb',
 'tk_ttnam_aosomi.ipynb',
 'tk_ttnam_aosomi_npage.ipynb',
 'tk_ttnam_aosomi_t10.csv',
 'tk_ttnam_aosomi_t11.csv',
 'tk_ttnam_aosomi_t12.csv',
 'tk_ttnam_aosomi_t13.csv',
 'tk_ttnam_aosomi_t14.csv',
 'tk_ttnam_aosomi_t15.csv',
 'tk_ttnam_aosomi_t16.csv',
 'tk_ttnam_aosomi_t17.csv',
 'tk_ttnam_aosomi_t18.csv',
 'tk_ttnam_aosomi_t19.csv',
 'tk_ttnam_aosomi_t2.csv',
 'tk_ttnam_aosomi_t20.csv',
 'tk_ttnam_aosomi_t21.csv',
 'tk_ttnam_aosomi_t22.csv',
 'tk_ttnam_aosomi_t23.csv',
 'tk_ttnam_aosomi_t24.csv',
 'tk_ttnam_aosomi_t25.csv',
 'tk_ttnam_aosomi_t26.csv',
 'tk_ttnam_aosomi_t27.csv',
 'tk_ttnam_aosomi_t28.csv',
 'tk_ttnam_aosomi_t29.csv',
 'tk_ttnam_aosomi_t3.csv',
 'tk_ttnam_aosomi_t30.csv',
 'tk_ttnam_aosomi_t31.csv',
 'tk_ttnam_aosomi_t32.csv',
 'tk_ttnam_aosomi_t33.csv',
 'tk_ttnam_aosomi_t34.csv',
 'tk_ttnam_aosomi_t35.csv',
 'tk_ttnam_aosomi_t36.csv',
 'tk_ttnam_aosomi_t37.csv',
 'tk_ttnam_aosomi_t38.csv',
 'tk_ttnam_aosomi_t39.csv',
 'tk_ttnam_aosomi_t4.csv',
 'tk_ttnam_aosomi_t40.csv',
 'tk_ttnam_aosomi_t41.csv',
 'tk_ttnam_aosomi_t42.csv',
 'tk_ttnam_aosomi_t43.csv',
 'tk_ttnam_aosomi_t44.csv',
 'tk_ttnam_aosomi_t45.csv',
 'tk_ttnam_aosomi_t46.csv',
 'tk_ttnam_aosomi_t47.csv',
 'tk_ttnam_aosomi_t48.csv',
 'tk_ttnam_aosomi_t49.csv',
 'tk_ttnam_aosomi_t5.csv',
 'tk_ttnam_aosomi_t50.csv',
 'tk_ttnam_aosomi_t6.csv',
 'tk_ttnam_aosomi_t7.csv',
 'tk_ttnam_aosomi_t8.csv',
 'tk_ttnam_aosomi_t9.csv']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_aosomi_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales,category
0,Áo sơ mi nam vải cotton mềm không nhăn-Quà tặng,108.000₫,https://tka.tiki.vn/pixel/pixel?data=HufSYHShV...,1,-35%,Đã bán 32,aosomi
1,Áo sơ mi nam cổ trụ cài hêt cúc tay dài vài kh...,108.000₫,https://tka.tiki.vn/pixel/pixel?data=eDmi0URcB...,2,-35%,Đã bán 2,aosomi
2,"áo sơ mi phong cách Hàn quốc cực năng động, ph...",211.250₫,https://tka.tiki.vn/pixel/pixel?data=I85_8D-Jx...,3,-35%,NaN,aosomi
3,áo sơ mi nam phối màu tay lỡ phong cách hàn qu...,260.000₫,https://tka.tiki.vn/pixel/pixel?data=OwoFtllTO...,4,-51%,Đã bán 2,aosomi
4,áo sơ mi cổ trụ phong cách thượng hải siêu chấ...,230.750₫,https://tka.tiki.vn/pixel/pixel?data=sPES9HDpX...,5,-35%,Đã bán 1,aosomi
...,...,...,...,...,...,...,...
35,NaN,NaN,https://tiki.vn/ao-so-mi-nam-ngan-tay-cong-so-...,36,NaN,NaN,aosomi
36,"Áo sơ mi nam, áo sơ mi cộc tay phối màu trẻ tr...",199.000₫,https://tiki.vn/ao-so-mi-nam-ao-so-mi-coc-tay-...,37,NaN,Đã bán 2,aosomi
37,Áo sơ mi nam ngắn tay a,195.000₫,https://tiki.vn/ao-so-mi-nam-ngan-tay-a-p25161...,38,NaN,Đã bán 3,aosomi
38,Áo Sơ Mi Nam Tay Ngắn Mẫu 1,228.000₫,https://tiki.vn/a-o-so-mi-nam-tay-ngan-ma-u-1-...,39,NaN,Đã bán 10,aosomi
39,ÁO SƠ MI TRẮNG NAM HỌA TIẾT HOA THƯ PHÁP,99.000₫,https://tiki.vn/ao-so-mi-trang-nam-hoa-tiet-ho...,40,NaN,NaN,aosomi

1. Xử lý dữ liệu

In [5]:
df_all = df_all.drop('index', axis=1)

In [6]:
df_all.dropna(subset=['sales'], inplace=True)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales,category
0,Áo sơ mi nam vải cotton mềm không nhăn-Quà tặng,108.000₫,https://tka.tiki.vn/pixel/pixel?data=HufSYHShV...,-35%,Đã bán 32,aosomi
1,Áo sơ mi nam cổ trụ cài hêt cúc tay dài vài kh...,108.000₫,https://tka.tiki.vn/pixel/pixel?data=eDmi0URcB...,-35%,Đã bán 2,aosomi
2,áo sơ mi nam phối màu tay lỡ phong cách hàn qu...,260.000₫,https://tka.tiki.vn/pixel/pixel?data=OwoFtllTO...,-51%,Đã bán 2,aosomi
3,áo sơ mi cổ trụ phong cách thượng hải siêu chấ...,230.750₫,https://tka.tiki.vn/pixel/pixel?data=sPES9HDpX...,-35%,Đã bán 1,aosomi
4,Áo sơ mi nam trơn tay dài cao cấp Lados - 779 ...,116.000₫,https://tiki.vn/ao-so-mi-nam-tron-tay-dai-cao-...,-31%,Đã bán 3.2k,aosomi
...,...,...,...,...,...,...
880,Áo sơ mi ngắn tay nam Columbia Pine Canyon - 2...,545.000₫,https://tiki.vn/ao-so-mi-ngan-tay-nam-columbia...,NaN,Đã bán 1,aosomi
881,Áo Sơ Mi Nam Tay Dài Màu Trơn Thời Trang Poniv...,105.000,https://tiki.vn/ao-so-mi-nam-tay-dai-mau-tron-...,NaN,Đã bán 4,aosomi
882,"Áo sơ mi nam, áo sơ mi cộc tay phối màu trẻ tr...",199.000₫,https://tiki.vn/ao-so-mi-nam-ao-so-mi-coc-tay-...,NaN,Đã bán 2,aosomi
883,Áo sơ mi nam ngắn tay a,195.000₫,https://tiki.vn/ao-so-mi-nam-ngan-tay-a-p25161...,NaN,Đã bán 3,aosomi
884,Áo Sơ Mi Nam Tay Ngắn Mẫu 1,228.000₫,https://tiki.vn/a-o-so-mi-nam-tay-ngan-ma-u-1-...,NaN,Đã bán 10,aosomi

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0      108000
1      108000
2      260000
3      230750
4      116000
        ...
880    545000
881    105000
882    199000
883    195000
884    228000
Name: price, Length: 885, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0        32.0
1         2.0
2         2.0
3         1.0
4      3200.0
        ...
880       1.0
881       4.0
882       2.0
883       3.0
884      10.0
Name: sales, Length: 885, dtype: float64

In [11]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0        3456000.0
1         216000.0
2         520000.0
3         230750.0
4      371200000.0
          ...
880       545000.0
881       420000.0
882       398000.0
883       585000.0
884      2280000.0
Name: revenue, Length: 885, dtype: float64

In [12]:
total = df_all["revenue"].sum()

In [13]:
print("Tổng doanh số aosomi: ", total)
print("So mat hang da ban: ", len(df_all["title"])) # san pham da ban
print("So san pham da ban: ", df_all["sales"].sum()) # san pham co luot ban

Tổng doanh số aosomi:  3593188839.0
So mat hang da ban:  885
So san pham da ban:  23227.0

In [14]:
df_all

,title,price,link_item,discount,sales,category,revenue
0,Áo sơ mi nam vải cotton mềm không nhăn-Quà tặng,108000,https://tka.tiki.vn/pixel/pixel?data=HufSYHShV...,-35%,32.0,aosomi,3456000.0
1,Áo sơ mi nam cổ trụ cài hêt cúc tay dài vài kh...,108000,https://tka.tiki.vn/pixel/pixel?data=eDmi0URcB...,-35%,2.0,aosomi,216000.0
2,áo sơ mi nam phối màu tay lỡ phong cách hàn qu...,260000,https://tka.tiki.vn/pixel/pixel?data=OwoFtllTO...,-51%,2.0,aosomi,520000.0
3,áo sơ mi cổ trụ phong cách thượng hải siêu chấ...,230750,https://tka.tiki.vn/pixel/pixel?data=sPES9HDpX...,-35%,1.0,aosomi,230750.0
4,Áo sơ mi nam trơn tay dài cao cấp Lados - 779 ...,116000,https://tiki.vn/ao-so-mi-nam-tron-tay-dai-cao-...,-31%,3200.0,aosomi,371200000.0
...,...,...,...,...,...,...,...
880,Áo sơ mi ngắn tay nam Columbia Pine Canyon - 2...,545000,https://tiki.vn/ao-so-mi-ngan-tay-nam-columbia...,NaN,1.0,aosomi,545000.0
881,Áo Sơ Mi Nam Tay Dài Màu Trơn Thời Trang Poniv...,105000,https://tiki.vn/ao-so-mi-nam-tay-dai-mau-tron-...,NaN,4.0,aosomi,420000.0
882,"Áo sơ mi nam, áo sơ mi cộc tay phối màu trẻ tr...",199000,https://tiki.vn/ao-so-mi-nam-ao-so-mi-coc-tay-...,NaN,2.0,aosomi,398000.0
883,Áo sơ mi nam ngắn tay a,195000,https://tiki.vn/ao-so-mi-nam-ngan-tay-a-p25161...,NaN,3.0,aosomi,585000.0
884,Áo Sơ Mi Nam Tay Ngắn Mẫu 1,228000,https://tiki.vn/a-o-so-mi-nam-tay-ngan-ma-u-1-...,NaN,10.0,aosomi,2280000.0

In [15]:
df_all.to_csv("tk_aosomi_all_ed.csv")