In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_190124(12htrua) - Copy (6)\dienthoai_maytinhbang\maydocsach"
os.listdir(path)

['.ipynb_checkpoints',
 'tk_dienthoai_maytinhbang_maydocsach.ipynb',
 'tk_dienthoai_maytinhbang_maydocsach_t2.ipynb',
 'tk_maydocsach_all.ipynb',
 'tk_maydocsach_t1.csv',
 'tk_maydocsach_t2.csv']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_maydocsach_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales,category
0,Máy đọc sách New Kindle 11th 2022 (16GB) - Hàn...,2.680.000₫,https://tka.tiki.vn/pixel/pixel?data=6RZpqklcr...,1,-18%,Đã bán 3,maydocsach
1,Máy đọc sách All New Kindle Paperwhite 5 (11th...,3.330.000₫,https://tka.tiki.vn/pixel/pixel?data=nve5b7Otz...,2,-32%,Đã bán 3,maydocsach
2,Máy đọc sách Kindle 2022 (11th) - All new kind...,2.680.000₫,https://tka.tiki.vn/pixel/pixel?data=7ap19FL6_...,3,-10%,Đã bán 8,maydocsach
3,Máy đọc sách Kindle Paperwhite 5 (8GB) - Hàng ...,3.440.000₫,https://tka.tiki.vn/pixel/pixel?data=wilMfQXM0...,4,-21%,NaN,maydocsach
4,Combo Máy đọc sách All New Kindle Paperwhite 5...,3.380.000₫,https://tka.tiki.vn/pixel/pixel?data=B92DfFlfA...,5,-3%,Đã bán 4,maydocsach
...,...,...,...,...,...,...,...
13,Máy đọc sách Kindle Scribe - Hàng nhập khẩu,12.590.000₫,https://tka.tiki.vn/pixel/pixel?data=7oJHKw8OR...,14,NaN,Đã bán 5,maydocsach
14,Combo Máy đọc sách All New Kindle Paperwhite 5...,3.850.000₫,https://tka.tiki.vn/pixel/pixel?data=Rv7x3K1el...,15,NaN,Đã bán 7,maydocsach
15,Bút học tiếng Anh i-Tek Venus 2023 (HÀNG CHÍNH...,560.000₫,https://tiki.vn/but-hoc-tieng-anh-i-tek-chinh-...,16,NaN,Đã bán 1,maydocsach
16,Máy đọc sách All new Paperwhite Gen 5 (11th) m...,3.490.000₫,https://tiki.vn/may-doc-sach-all-new-paperwhit...,17,NaN,NaN,maydocsach
17,Máy đọc sách Kobo Nia - Hàng nhập khẩu,2.680.000₫,https://tiki.vn/may-doc-sach-kobo-nia-p1487018...,18,NaN,NaN,maydocsach

1. Xử lý dữ liệu

In [5]:
df_all = df_all.drop('index', axis=1)

In [6]:
df_all.dropna(subset=['sales'], inplace=True)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales,category
0,Máy đọc sách New Kindle 11th 2022 (16GB) - Hàn...,2.680.000₫,https://tka.tiki.vn/pixel/pixel?data=6RZpqklcr...,-18%,Đã bán 3,maydocsach
1,Máy đọc sách All New Kindle Paperwhite 5 (11th...,3.330.000₫,https://tka.tiki.vn/pixel/pixel?data=nve5b7Otz...,-32%,Đã bán 3,maydocsach
2,Máy đọc sách Kindle 2022 (11th) - All new kind...,2.680.000₫,https://tka.tiki.vn/pixel/pixel?data=7ap19FL6_...,-10%,Đã bán 8,maydocsach
3,Combo Máy đọc sách All New Kindle Paperwhite 5...,3.380.000₫,https://tka.tiki.vn/pixel/pixel?data=B92DfFlfA...,-3%,Đã bán 4,maydocsach
4,Máy đọc sách New Kindle 11th 2022 (16GB) - Hàn...,2.630.000₫,https://tiki.vn/may-doc-sach-new-kindle-11th-2...,-11%,Đã bán 502,maydocsach
...,...,...,...,...,...,...
60,Máy đọc sách Kindle Oasis 3 (2019) - Amazon - ...,5.790.000₫,https://tka.tiki.vn/pixel/pixel?data=wm48QfRw-...,NaN,Đã bán 35,maydocsach
61,Combo Máy đọc sách All New Kindle Paperwhite 5...,3.480.000₫,https://tka.tiki.vn/pixel/pixel?data=GE_ran5pb...,NaN,Đã bán 454,maydocsach
62,Máy đọc sách Kindle Scribe - Hàng nhập khẩu,12.590.000₫,https://tka.tiki.vn/pixel/pixel?data=7oJHKw8OR...,NaN,Đã bán 5,maydocsach
63,Combo Máy đọc sách All New Kindle Paperwhite 5...,3.850.000₫,https://tka.tiki.vn/pixel/pixel?data=Rv7x3K1el...,NaN,Đã bán 7,maydocsach
64,Bút học tiếng Anh i-Tek Venus 2023 (HÀNG CHÍNH...,560.000₫,https://tiki.vn/but-hoc-tieng-anh-i-tek-chinh-...,NaN,Đã bán 1,maydocsach

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0      2680000
1      3330000
2      2680000
3      3380000
4      2630000
        ...
60     5790000
61     3480000
62    12590000
63     3850000
64      560000
Name: price, Length: 65, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0       3.0
1       3.0
2       8.0
3       4.0
4     502.0
      ...
60     35.0
61    454.0
62      5.0
63      7.0
64      1.0
Name: sales, Length: 65, dtype: float64

In [11]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0     8.040000e+06
1     9.990000e+06
2     2.144000e+07
3     1.352000e+07
4     1.320260e+09
          ...
60    2.026500e+08
61    1.579920e+09
62    6.295000e+07
63    2.695000e+07
64    5.600000e+05
Name: revenue, Length: 65, dtype: float64

In [12]:
total = df_all["revenue"].sum()

In [13]:
print("Tổng doanh số maydocsach: ", total)
print("So mat hang da ban: ", len(df_all["title"])) # san pham da ban
print("So san pham da ban: ", df_all["sales"].sum()) # san pham co luot ban

Tổng doanh số maydocsach:  28362183924.0
So mat hang da ban:  65
So san pham da ban:  7884.0

In [14]:
df_all

,title,price,link_item,discount,sales,category,revenue
0,Máy đọc sách New Kindle 11th 2022 (16GB) - Hàn...,2680000,https://tka.tiki.vn/pixel/pixel?data=6RZpqklcr...,-18%,3.0,maydocsach,8.040000e+06
1,Máy đọc sách All New Kindle Paperwhite 5 (11th...,3330000,https://tka.tiki.vn/pixel/pixel?data=nve5b7Otz...,-32%,3.0,maydocsach,9.990000e+06
2,Máy đọc sách Kindle 2022 (11th) - All new kind...,2680000,https://tka.tiki.vn/pixel/pixel?data=7ap19FL6_...,-10%,8.0,maydocsach,2.144000e+07
3,Combo Máy đọc sách All New Kindle Paperwhite 5...,3380000,https://tka.tiki.vn/pixel/pixel?data=B92DfFlfA...,-3%,4.0,maydocsach,1.352000e+07
4,Máy đọc sách New Kindle 11th 2022 (16GB) - Hàn...,2630000,https://tiki.vn/may-doc-sach-new-kindle-11th-2...,-11%,502.0,maydocsach,1.320260e+09
...,...,...,...,...,...,...,...
60,Máy đọc sách Kindle Oasis 3 (2019) - Amazon - ...,5790000,https://tka.tiki.vn/pixel/pixel?data=wm48QfRw-...,NaN,35.0,maydocsach,2.026500e+08
61,Combo Máy đọc sách All New Kindle Paperwhite 5...,3480000,https://tka.tiki.vn/pixel/pixel?data=GE_ran5pb...,NaN,454.0,maydocsach,1.579920e+09
62,Máy đọc sách Kindle Scribe - Hàng nhập khẩu,12590000,https://tka.tiki.vn/pixel/pixel?data=7oJHKw8OR...,NaN,5.0,maydocsach,6.295000e+07
63,Combo Máy đọc sách All New Kindle Paperwhite 5...,3850000,https://tka.tiki.vn/pixel/pixel?data=Rv7x3K1el...,NaN,7.0,maydocsach,2.695000e+07
64,Bút học tiếng Anh i-Tek Venus 2023 (HÀNG CHÍNH...,560000,https://tiki.vn/but-hoc-tieng-anh-i-tek-chinh-...,NaN,1.0,maydocsach,5.600000e+05

In [15]:
df_all.to_csv("tk_maydocsach_all_ed.csv")