In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_170124(12hdem) - Copy\thoitrangnu\dodoi"
os.listdir(path)

['.ipynb_checkpoints',
 'tk_dodoi.csv',
 'tk_dodoi_all.ipynb',
 'tk_ttn_dd.ipynb',
 'tk_ttn_dd_npage.ipynb',
 'tk_ttn_dd_t10.csv',
 'tk_ttn_dd_t11.csv',
 'tk_ttn_dd_t12.csv',
 'tk_ttn_dd_t13.csv',
 'tk_ttn_dd_t14.csv',
 'tk_ttn_dd_t15.csv',
 'tk_ttn_dd_t16.csv',
 'tk_ttn_dd_t17.csv',
 'tk_ttn_dd_t18.csv',
 'tk_ttn_dd_t19.csv',
 'tk_ttn_dd_t2.csv',
 'tk_ttn_dd_t20.csv',
 'tk_ttn_dd_t21.csv',
 'tk_ttn_dd_t22.csv',
 'tk_ttn_dd_t23.csv',
 'tk_ttn_dd_t24.csv',
 'tk_ttn_dd_t25.csv',
 'tk_ttn_dd_t26.csv',
 'tk_ttn_dd_t27.csv',
 'tk_ttn_dd_t28.csv',
 'tk_ttn_dd_t29.csv',
 'tk_ttn_dd_t3.csv',
 'tk_ttn_dd_t30.csv',
 'tk_ttn_dd_t31.csv',
 'tk_ttn_dd_t32.csv',
 'tk_ttn_dd_t33.csv',
 'tk_ttn_dd_t34.csv',
 'tk_ttn_dd_t35.csv',
 'tk_ttn_dd_t36.csv',
 'tk_ttn_dd_t37.csv',
 'tk_ttn_dd_t38.csv',
 'tk_ttn_dd_t39.csv',
 'tk_ttn_dd_t4.csv',
 'tk_ttn_dd_t40.csv',
 'tk_ttn_dd_t41.csv',
 'tk_ttn_dd_t42.csv',
 'tk_ttn_dd_t43.csv',
 'tk_ttn_dd_t44.csv',
 'tk_ttn_dd_t45.csv',
 'tk_ttn_dd_t46.csv',
 'tk_ttn_dd_t47.csv',
 'tk_ttn_dd_t48.csv',
 'tk_ttn_dd_t49.csv',
 'tk_ttn_dd_t5.csv',
 'tk_ttn_dd_t50.csv',
 'tk_ttn_dd_t6.csv',
 'tk_ttn_dd_t7.csv',
 'tk_ttn_dd_t8.csv',
 'tk_ttn_dd_t9.csv']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_dodoi_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales,category
0,Áo gia đình mặt cười đồ đồng phục gia đình 3/4...,49.000₫,https://tiki.vn/ao-gia-dinh-mac-cuoi-thun-cott...,1,-11%,Đã bán 27,dodoi
1,Áo gia đình 3/4/5 người set đồ đồng phục đôi m...,49.000₫,https://tiki.vn/ao-gia-dinh-thun-cotton-mau-xa...,2,NaN,Đã bán 5,dodoi
2,Áo gia đình Love you Đồ đôi mẹ và bé Đồng phục...,49.000₫,https://tiki.vn/ao-gia-dinh-love-you-thun-cott...,3,NaN,Đã bán 5,dodoi
3,Áo gia đình 3/4/5 người dễ thương Đồng phục gi...,25.000₫,https://tiki.vn/ao-gia-dinh-dang-yeu-thun-cott...,4,NaN,Đã bán 5,dodoi
4,Áo gia đình 3/4/5 người mẫu bắn tim màu vàng c...,49.000₫,https://tiki.vn/ao-gia-dinh-ban-tim-thun-cotto...,5,NaN,Đã bán 1,dodoi
...,...,...,...,...,...,...,...
35,NaN,NaN,https://tiki.vn/combo-2-quan-di-bien-mau-moi-x...,36,NaN,NaN,dodoi
36,Cặp quần đôi đi biển mẫu mới xinh yêu (giá com...,149.000₫,https://tiki.vn/cap-quan-doi-di-bien-mau-moi-x...,37,NaN,NaN,dodoi
37,Quần đôi đi biển mẫu mới đẹp xinh combo 2 quần...,99.000₫,https://tiki.vn/quan-doi-di-bien-mau-moi-dep-x...,38,NaN,NaN,dodoi
38,TẠP DỀ YẾM NHỰA CHỐNG THẤM NƯỚC,30.000₫,https://tiki.vn/tap-de-yem-nhua-chong-tham-nuo...,39,NaN,Đã bán 1,dodoi
39,Áo Gia Đình Local Brand NOMYC Mẫu GĐ8 Chất Liệ...,180.000,https://tiki.vn/ao-gia-dinh-local-brand-nomyc-...,40,NaN,NaN,dodoi

1. Xử lý dữ liệu

In [5]:
df_all = df_all.drop('index', axis=1)

In [6]:
df_all.dropna(subset=['sales'], inplace=True)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales,category
0,Áo gia đình mặt cười đồ đồng phục gia đình 3/4...,49.000₫,https://tiki.vn/ao-gia-dinh-mac-cuoi-thun-cott...,-11%,Đã bán 27,dodoi
1,Áo gia đình 3/4/5 người set đồ đồng phục đôi m...,49.000₫,https://tiki.vn/ao-gia-dinh-thun-cotton-mau-xa...,NaN,Đã bán 5,dodoi
2,Áo gia đình Love you Đồ đôi mẹ và bé Đồng phục...,49.000₫,https://tiki.vn/ao-gia-dinh-love-you-thun-cott...,NaN,Đã bán 5,dodoi
3,Áo gia đình 3/4/5 người dễ thương Đồng phục gi...,25.000₫,https://tiki.vn/ao-gia-dinh-dang-yeu-thun-cott...,NaN,Đã bán 5,dodoi
4,Áo gia đình 3/4/5 người mẫu bắn tim màu vàng c...,49.000₫,https://tiki.vn/ao-gia-dinh-ban-tim-thun-cotto...,NaN,Đã bán 1,dodoi
...,...,...,...,...,...,...
169,Áo và quần đôi đi biển ĐỦ SIZE (DDB13T),195.000₫,https://tiki.vn/ao-va-quan-doi-di-bien-du-size...,NaN,Đã bán 3,dodoi
170,Áo thun gia đình mẫu màu cam GD340 dễ thương đ...,25.000₫,https://tiki.vn/ao-thun-gia-dinh-happy-family-...,NaN,Đã bán 7,dodoi
171,"áo gia đình con là tất cả , hàng đẹp,nhóm, thu...",50.000₫,https://tiki.vn/ao-gia-dinh-con-la-tat-ca-hang...,NaN,Đã bán 3,dodoi
172,[ĐỦ SIZE ĐỦ MÀU] Đồ bảo hộ y tế người lớn và t...,49.000₫,https://tiki.vn/du-size-du-mau-do-bao-ho-y-te-...,NaN,Đã bán 7,dodoi
173,TẠP DỀ YẾM NHỰA CHỐNG THẤM NƯỚC,30.000₫,https://tiki.vn/tap-de-yem-nhua-chong-tham-nuo...,NaN,Đã bán 1,dodoi

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0       49000
1       49000
2       49000
3       25000
4       49000
        ...
169    195000
170     25000
171     50000
172     49000
173     30000
Name: price, Length: 174, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0      27.0
1       5.0
2       5.0
3       5.0
4       1.0
       ...
169     3.0
170     7.0
171     3.0
172     7.0
173     1.0
Name: sales, Length: 174, dtype: float64

In [11]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0      1323000.0
1       245000.0
2       245000.0
3       125000.0
4        49000.0
         ...
169     585000.0
170     175000.0
171     150000.0
172     343000.0
173      30000.0
Name: revenue, Length: 174, dtype: float64

In [12]:
total = df_all["revenue"].sum()

In [13]:
print("Tổng doanh số dodoi: ", total)
print("So mat hang da ban: ", len(df_all["title"])) # san pham da ban
print("So san pham da ban: ", df_all["sales"].sum()) # san pham co luot ban

Tổng doanh số dodoi:  108277297.0
So mat hang da ban:  174
So san pham da ban:  1016.0

In [14]:
df_all

,title,price,link_item,discount,sales,category,revenue
0,Áo gia đình mặt cười đồ đồng phục gia đình 3/4...,49000,https://tiki.vn/ao-gia-dinh-mac-cuoi-thun-cott...,-11%,27.0,dodoi,1323000.0
1,Áo gia đình 3/4/5 người set đồ đồng phục đôi m...,49000,https://tiki.vn/ao-gia-dinh-thun-cotton-mau-xa...,NaN,5.0,dodoi,245000.0
2,Áo gia đình Love you Đồ đôi mẹ và bé Đồng phục...,49000,https://tiki.vn/ao-gia-dinh-love-you-thun-cott...,NaN,5.0,dodoi,245000.0
3,Áo gia đình 3/4/5 người dễ thương Đồng phục gi...,25000,https://tiki.vn/ao-gia-dinh-dang-yeu-thun-cott...,NaN,5.0,dodoi,125000.0
4,Áo gia đình 3/4/5 người mẫu bắn tim màu vàng c...,49000,https://tiki.vn/ao-gia-dinh-ban-tim-thun-cotto...,NaN,1.0,dodoi,49000.0
...,...,...,...,...,...,...,...
169,Áo và quần đôi đi biển ĐỦ SIZE (DDB13T),195000,https://tiki.vn/ao-va-quan-doi-di-bien-du-size...,NaN,3.0,dodoi,585000.0
170,Áo thun gia đình mẫu màu cam GD340 dễ thương đ...,25000,https://tiki.vn/ao-thun-gia-dinh-happy-family-...,NaN,7.0,dodoi,175000.0
171,"áo gia đình con là tất cả , hàng đẹp,nhóm, thu...",50000,https://tiki.vn/ao-gia-dinh-con-la-tat-ca-hang...,NaN,3.0,dodoi,150000.0
172,[ĐỦ SIZE ĐỦ MÀU] Đồ bảo hộ y tế người lớn và t...,49000,https://tiki.vn/du-size-du-mau-do-bao-ho-y-te-...,NaN,7.0,dodoi,343000.0
173,TẠP DỀ YẾM NHỰA CHỐNG THẤM NƯỚC,30000,https://tiki.vn/tap-de-yem-nhua-chong-tham-nuo...,NaN,1.0,dodoi,30000.0

In [15]:
df_all.to_csv("tk_dodoinu_all_ed.csv")