In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_180124(12htrua) - Copy (4)\thoitrangnam\quanaotrungnien"
os.listdir(path)

['tk_quanaotrungniennam.csv',
 'tk_quanaotrungniennam.ipynb',
 'tk_quanaotrungniennam_all.ipynb',
 'tk_ttn_quanaotrungniennam_t1.csv',
 'tk_ttn_quanaotrungniennam_t10.csv',
 'tk_ttn_quanaotrungniennam_t11.csv',
 'tk_ttn_quanaotrungniennam_t12.csv',
 'tk_ttn_quanaotrungniennam_t13.csv',
 'tk_ttn_quanaotrungniennam_t14.csv',
 'tk_ttn_quanaotrungniennam_t15.csv',
 'tk_ttn_quanaotrungniennam_t16.csv',
 'tk_ttn_quanaotrungniennam_t17.csv',
 'tk_ttn_quanaotrungniennam_t18.csv',
 'tk_ttn_quanaotrungniennam_t19.csv',
 'tk_ttn_quanaotrungniennam_t2.csv',
 'tk_ttn_quanaotrungniennam_t20.csv',
 'tk_ttn_quanaotrungniennam_t21.csv',
 'tk_ttn_quanaotrungniennam_t22.csv',
 'tk_ttn_quanaotrungniennam_t3.csv',
 'tk_ttn_quanaotrungniennam_t4.csv',
 'tk_ttn_quanaotrungniennam_t5.csv',
 'tk_ttn_quanaotrungniennam_t6.csv',
 'tk_ttn_quanaotrungniennam_t7.csv',
 'tk_ttn_quanaotrungniennam_t8.csv',
 'tk_ttn_quanaotrungniennam_t9.csv',
 'tk_ttn_tttn_npage.ipynb']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_quanaotrungnien_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales,category
0,áo khoác nam trung niên ẢNH THẬT 2 lớp không n...,339.000₫,https://tiki.vn/ao-khoac-nam-trung-nien-anh-th...,1,NaN,Đã bán 16,quanaotrungniennam
1,Áo Khoác Nam Trung Niên Lót Lông Cho Bố - Áo K...,285.000₫,https://tiki.vn/ao-khoac-nam-trung-nien-lot-lo...,2,NaN,Đã bán 10,quanaotrungniennam
2,Bộ quần áo đại gia cổ tàu chất mềm mát cho các...,336.300₫,https://tiki.vn/bo-quan-ao-dai-gia-co-tau-chat...,3,NaN,Đã bán 4,quanaotrungniennam
3,Quần thô KAKI thô nam trung niên ẢNH THẬT hàng...,179.000₫,https://tiki.vn/quan-tho-kaki-tho-nam-trung-ni...,4,NaN,Đã bán 5,quanaotrungniennam
4,đồ bộ mặc nhà nam trung niên cho bố_ sét bộ đũ...,250.000₫,https://tiki.vn/do-bo-mac-nha-nam-trung-nien-c...,5,NaN,Đã bán 15,quanaotrungniennam
...,...,...,...,...,...,...,...
35,NaN,NaN,https://tiki.vn/ao-kieu-trung-nien-tay-coc-cha...,36,NaN,NaN,quanaotrungniennam
36,Quần Áo cho mẹ (bộ),59.950₫,https://tiki.vn/quan-ao-cho-me-bo-p88085979.ht...,37,NaN,Đã bán 3,quanaotrungniennam
37,( HÀNG SẴN) Áo Voan Trung Niên Tay Lỡ Đẹp SM54...,225.000₫,https://tiki.vn/hang-san-ao-voan-trung-nien-ta...,38,NaN,Đã bán 3,quanaotrungniennam
38,( HÀNG SẴN) Bộ Đồ Lụa Mặc Nhà Phối Ren Trung N...,285.000₫,https://tiki.vn/hang-san-bo-do-lua-mac-nha-pho...,39,NaN,NaN,quanaotrungniennam
39,Áo khoác len trung niên nữ áo len thu đông cho...,199.000,https://tiki.vn/ao-khoac-len-trung-nien-nu-ao-...,40,NaN,NaN,quanaotrungniennam

1. Xử lý dữ liệu

In [5]:
df_all = df_all.drop('index', axis=1)

In [6]:
df_all.dropna(subset=['sales'], inplace=True)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales,category
0,áo khoác nam trung niên ẢNH THẬT 2 lớp không n...,339.000₫,https://tiki.vn/ao-khoac-nam-trung-nien-anh-th...,NaN,Đã bán 16,quanaotrungniennam
1,Áo Khoác Nam Trung Niên Lót Lông Cho Bố - Áo K...,285.000₫,https://tiki.vn/ao-khoac-nam-trung-nien-lot-lo...,NaN,Đã bán 10,quanaotrungniennam
2,Bộ quần áo đại gia cổ tàu chất mềm mát cho các...,336.300₫,https://tiki.vn/bo-quan-ao-dai-gia-co-tau-chat...,NaN,Đã bán 4,quanaotrungniennam
3,Quần thô KAKI thô nam trung niên ẢNH THẬT hàng...,179.000₫,https://tiki.vn/quan-tho-kaki-tho-nam-trung-ni...,NaN,Đã bán 5,quanaotrungniennam
4,đồ bộ mặc nhà nam trung niên cho bố_ sét bộ đũ...,250.000₫,https://tiki.vn/do-bo-mac-nha-nam-trung-nien-c...,NaN,Đã bán 15,quanaotrungniennam
...,...,...,...,...,...,...
234,Đầm xòe thiết kế trung niên cao cấp sang trọng...,480.000₫,https://tiki.vn/dam-xoe-thiet-ke-trung-nien-ca...,NaN,Đã bán 1,quanaotrungniennam
235,Bộ Đũi Trung Niên Hoa Thêu Cực Đẹp Vải Mát Đườ...,235.000,https://tiki.vn/bo-dui-trung-nien-hoa-theu-cuc...,NaN,Đã bán 1,quanaotrungniennam
236,Bộ quần áo trung niên nữ_ đồ bộ mặc nhà chất v...,149.000₫,https://tiki.vn/bo-quan-ao-trung-nien-nu_-do-b...,NaN,Đã bán 3,quanaotrungniennam
237,Quần Áo cho mẹ (bộ),59.950₫,https://tiki.vn/quan-ao-cho-me-bo-p88085979.ht...,NaN,Đã bán 3,quanaotrungniennam
238,( HÀNG SẴN) Áo Voan Trung Niên Tay Lỡ Đẹp SM54...,225.000₫,https://tiki.vn/hang-san-ao-voan-trung-nien-ta...,NaN,Đã bán 3,quanaotrungniennam

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0      339000
1      285000
2      336300
3      179000
4      250000
        ...
234    480000
235    235000
236    149000
237     59950
238    225000
Name: price, Length: 239, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0      16.0
1      10.0
2       4.0
3       5.0
4      15.0
       ...
234     1.0
235     1.0
236     3.0
237     3.0
238     3.0
Name: sales, Length: 239, dtype: float64

In [11]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0      5424000.0
1      2850000.0
2      1345200.0
3       895000.0
4      3750000.0
         ...
234     480000.0
235     235000.0
236     447000.0
237     179850.0
238     675000.0
Name: revenue, Length: 239, dtype: float64

In [12]:
total = df_all["revenue"].sum()

In [13]:
print("Tổng doanh số quanaotrungnien: ", total)
print("So mat hang da ban: ", len(df_all["title"])) # san pham da ban
print("So san pham da ban: ", df_all["sales"].sum()) # san pham co luot ban

Tổng doanh số quanaotrungnien:  376813032.0
So mat hang da ban:  239
So san pham da ban:  1451.0

In [14]:
df_all

,title,price,link_item,discount,sales,category,revenue
0,áo khoác nam trung niên ẢNH THẬT 2 lớp không n...,339000,https://tiki.vn/ao-khoac-nam-trung-nien-anh-th...,NaN,16.0,quanaotrungniennam,5424000.0
1,Áo Khoác Nam Trung Niên Lót Lông Cho Bố - Áo K...,285000,https://tiki.vn/ao-khoac-nam-trung-nien-lot-lo...,NaN,10.0,quanaotrungniennam,2850000.0
2,Bộ quần áo đại gia cổ tàu chất mềm mát cho các...,336300,https://tiki.vn/bo-quan-ao-dai-gia-co-tau-chat...,NaN,4.0,quanaotrungniennam,1345200.0
3,Quần thô KAKI thô nam trung niên ẢNH THẬT hàng...,179000,https://tiki.vn/quan-tho-kaki-tho-nam-trung-ni...,NaN,5.0,quanaotrungniennam,895000.0
4,đồ bộ mặc nhà nam trung niên cho bố_ sét bộ đũ...,250000,https://tiki.vn/do-bo-mac-nha-nam-trung-nien-c...,NaN,15.0,quanaotrungniennam,3750000.0
...,...,...,...,...,...,...,...
234,Đầm xòe thiết kế trung niên cao cấp sang trọng...,480000,https://tiki.vn/dam-xoe-thiet-ke-trung-nien-ca...,NaN,1.0,quanaotrungniennam,480000.0
235,Bộ Đũi Trung Niên Hoa Thêu Cực Đẹp Vải Mát Đườ...,235000,https://tiki.vn/bo-dui-trung-nien-hoa-theu-cuc...,NaN,1.0,quanaotrungniennam,235000.0
236,Bộ quần áo trung niên nữ_ đồ bộ mặc nhà chất v...,149000,https://tiki.vn/bo-quan-ao-trung-nien-nu_-do-b...,NaN,3.0,quanaotrungniennam,447000.0
237,Quần Áo cho mẹ (bộ),59950,https://tiki.vn/quan-ao-cho-me-bo-p88085979.ht...,NaN,3.0,quanaotrungniennam,179850.0
238,( HÀNG SẴN) Áo Voan Trung Niên Tay Lỡ Đẹp SM54...,225000,https://tiki.vn/hang-san-ao-voan-trung-nien-ta...,NaN,3.0,quanaotrungniennam,675000.0

In [15]:
df_all.to_csv("tk_quanaotrungnien_all_ed.csv")