In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_170124(12htrua) - Copy (2)\thoitrangnam\quannam"
os.listdir(path)

['tk_quannam_all.ipynb',
 'tk_ttn_qn.ipynb',
 'tk_ttn_qn_npage.ipynb',
 'tk_ttn_quannam_t10.csv',
 'tk_ttn_quannam_t11.csv',
 'tk_ttn_quannam_t12.csv',
 'tk_ttn_quannam_t13.csv',
 'tk_ttn_quannam_t14.csv',
 'tk_ttn_quannam_t15.csv',
 'tk_ttn_quannam_t16.csv',
 'tk_ttn_quannam_t17.csv',
 'tk_ttn_quannam_t18.csv',
 'tk_ttn_quannam_t19.csv',
 'tk_ttn_quannam_t2.csv',
 'tk_ttn_quannam_t20.csv',
 'tk_ttn_quannam_t21.csv',
 'tk_ttn_quannam_t22.csv',
 'tk_ttn_quannam_t23.csv',
 'tk_ttn_quannam_t24.csv',
 'tk_ttn_quannam_t25.csv',
 'tk_ttn_quannam_t26.csv',
 'tk_ttn_quannam_t27.csv',
 'tk_ttn_quannam_t28.csv',
 'tk_ttn_quannam_t29.csv',
 'tk_ttn_quannam_t3.csv',
 'tk_ttn_quannam_t30.csv',
 'tk_ttn_quannam_t31.csv',
 'tk_ttn_quannam_t32.csv',
 'tk_ttn_quannam_t33.csv',
 'tk_ttn_quannam_t34.csv',
 'tk_ttn_quannam_t35.csv',
 'tk_ttn_quannam_t36.csv',
 'tk_ttn_quannam_t37.csv',
 'tk_ttn_quannam_t38.csv',
 'tk_ttn_quannam_t39.csv',
 'tk_ttn_quannam_t4.csv',
 'tk_ttn_quannam_t40.csv',
 'tk_ttn_quannam_t41.csv',
 'tk_ttn_quannam_t42.csv',
 'tk_ttn_quannam_t43.csv',
 'tk_ttn_quannam_t44.csv',
 'tk_ttn_quannam_t45.csv',
 'tk_ttn_quannam_t46.csv',
 'tk_ttn_quannam_t47.csv',
 'tk_ttn_quannam_t48.csv',
 'tk_ttn_quannam_t49.csv',
 'tk_ttn_quannam_t5.csv',
 'tk_ttn_quannam_t50.csv',
 'tk_ttn_quannam_t6.csv',
 'tk_ttn_quannam_t7.csv',
 'tk_ttn_quannam_t8.csv',
 'tk_ttn_quannam_t9.csv']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_quannam_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales,category
0,Quần Jean Nam Trắng Trơn cao cấp thương hiệu C...,169.000₫,https://tiki.vn/quan-jean-nam-trang-tron-cao-c...,1,-44%,Đã bán 1,quannam
1,"Quần jogger nam kaki dáng ôm body trẻ trung, ố...",85.000₫,https://tiki.vn/quan-jogger-nam-kaki-dang-om-b...,2,-46%,Đã bán 6,quannam
2,Quần short nam tập gym thể thao QSHOP QS619,180.000₫,https://tiki.vn/quan-short-nam-tap-gym-the-tha...,3,-20%,Đã bán 4,quannam
3,QUẦN TÂY NAM CO GIÃN CAO CẤP DN20010510 - đen ...,85.000₫,https://tiki.vn/quan-tay-nam-co-gian-cao-cap-d...,4,NaN,NaN,quannam
4,NaN,NaN,https://tiki.vn/quan-baggy-nam-nu-ong-suong-ar...,5,-37%,NaN,quannam
...,...,...,...,...,...,...,...
35,NaN,NaN,https://tiki.vn/quan-jean-nam-leman-xanh-bac-r...,36,NaN,NaN,quannam
36,Bộ Đồ Nam - Bộ Nỉ Nam Thu Đông Thể Thao Chất N...,300.000₫,https://tiki.vn/bo-do-nam-bo-ni-nam-thu-dong-t...,37,NaN,Đã bán 3,quannam
37,Quần Jean Nam màu xanh thương hiệu Julido Stor...,169.000₫,https://tiki.vn/quan-jean-nam-mau-xanh-thuong-...,38,NaN,Đã bán 221,quannam
38,Quần Tây Nam Dáng Ôm Chất Liệu Vải Mềm Mịn Khh...,93.000₫,https://tiki.vn/quan-tay-nam-dang-om-chat-lieu...,39,NaN,Đã bán 144,quannam
39,Viettien - Quần Jeans nam dài Regular fit Màu ...,823.200,https://tiki.vn/viettien-quan-jeans-nam-dai-re...,40,NaN,NaN,quannam

1. Xử lý dữ liệu

In [5]:
df_all = df_all.drop('index', axis=1)

In [6]:
df_all.dropna(subset=['sales'], inplace=True)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales,category
0,Quần Jean Nam Trắng Trơn cao cấp thương hiệu C...,169.000₫,https://tiki.vn/quan-jean-nam-trang-tron-cao-c...,-44%,Đã bán 1,quannam
1,"Quần jogger nam kaki dáng ôm body trẻ trung, ố...",85.000₫,https://tiki.vn/quan-jogger-nam-kaki-dang-om-b...,-46%,Đã bán 6,quannam
2,Quần short nam tập gym thể thao QSHOP QS619,180.000₫,https://tiki.vn/quan-short-nam-tap-gym-the-tha...,-20%,Đã bán 4,quannam
3,Quần đũi phối màu nam thời trang SZone SQ502A,129.000₫,https://tiki.vn/quan-dui-phoi-mau-nam-thoi-tra...,NaN,Đã bán 1,quannam
4,Quần Jean nam hàng cao cấp kiểu rách bụi ống ô...,294.000₫,https://tiki.vn/quan-jean-nam-hang-cao-cap-kie...,NaN,Đã bán 2,quannam
...,...,...,...,...,...,...
961,Quần Jean Nam Co Giãn Kiểu Dáng Trẻ Trung Đơn ...,169.000₫,https://tiki.vn/quan-jean-nam-co-gian-kieu-dan...,NaN,Đã bán 5,quannam
962,QUẦN JEAN NAM TRẮNG CAO CẤP - VẢI TRẮNG TINH C...,150.000₫,https://tiki.vn/quan-jean-nam-trang-cao-cap-va...,NaN,Đã bán 1,quannam
963,Bộ Đồ Nam - Bộ Nỉ Nam Thu Đông Thể Thao Chất N...,300.000₫,https://tiki.vn/bo-do-nam-bo-ni-nam-thu-dong-t...,NaN,Đã bán 3,quannam
964,Quần Jean Nam màu xanh thương hiệu Julido Stor...,169.000₫,https://tiki.vn/quan-jean-nam-mau-xanh-thuong-...,NaN,Đã bán 221,quannam
965,Quần Tây Nam Dáng Ôm Chất Liệu Vải Mềm Mịn Khh...,93.000₫,https://tiki.vn/quan-tay-nam-dang-om-chat-lieu...,NaN,Đã bán 144,quannam

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0      169000
1       85000
2      180000
3      129000
4      294000
        ...
961    169000
962    150000
963    300000
964    169000
965     93000
Name: price, Length: 966, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0        1.0
1        6.0
2        4.0
3        1.0
4        2.0
       ...
961      5.0
962      1.0
963      3.0
964    221.0
965    144.0
Name: sales, Length: 966, dtype: float64

In [11]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0        169000.0
1        510000.0
2        720000.0
3        129000.0
4        588000.0
          ...
961      845000.0
962      150000.0
963      900000.0
964    37349000.0
965    13392000.0
Name: revenue, Length: 966, dtype: float64

In [12]:
total = df_all["revenue"].sum()

In [13]:
print("Tổng doanh số quannam: ", total)
print("So mat hang da ban: ", len(df_all["title"])) # san pham da ban
print("So san pham da ban: ", df_all["sales"].sum()) # san pham co luot ban

Tổng doanh số quannam:  8379067516.0
So mat hang da ban:  966
So san pham da ban:  60146.0

In [14]:
df_all

,title,price,link_item,discount,sales,category,revenue
0,Quần Jean Nam Trắng Trơn cao cấp thương hiệu C...,169000,https://tiki.vn/quan-jean-nam-trang-tron-cao-c...,-44%,1.0,quannam,169000.0
1,"Quần jogger nam kaki dáng ôm body trẻ trung, ố...",85000,https://tiki.vn/quan-jogger-nam-kaki-dang-om-b...,-46%,6.0,quannam,510000.0
2,Quần short nam tập gym thể thao QSHOP QS619,180000,https://tiki.vn/quan-short-nam-tap-gym-the-tha...,-20%,4.0,quannam,720000.0
3,Quần đũi phối màu nam thời trang SZone SQ502A,129000,https://tiki.vn/quan-dui-phoi-mau-nam-thoi-tra...,NaN,1.0,quannam,129000.0
4,Quần Jean nam hàng cao cấp kiểu rách bụi ống ô...,294000,https://tiki.vn/quan-jean-nam-hang-cao-cap-kie...,NaN,2.0,quannam,588000.0
...,...,...,...,...,...,...,...
961,Quần Jean Nam Co Giãn Kiểu Dáng Trẻ Trung Đơn ...,169000,https://tiki.vn/quan-jean-nam-co-gian-kieu-dan...,NaN,5.0,quannam,845000.0
962,QUẦN JEAN NAM TRẮNG CAO CẤP - VẢI TRẮNG TINH C...,150000,https://tiki.vn/quan-jean-nam-trang-cao-cap-va...,NaN,1.0,quannam,150000.0
963,Bộ Đồ Nam - Bộ Nỉ Nam Thu Đông Thể Thao Chất N...,300000,https://tiki.vn/bo-do-nam-bo-ni-nam-thu-dong-t...,NaN,3.0,quannam,900000.0
964,Quần Jean Nam màu xanh thương hiệu Julido Stor...,169000,https://tiki.vn/quan-jean-nam-mau-xanh-thuong-...,NaN,221.0,quannam,37349000.0
965,Quần Tây Nam Dáng Ôm Chất Liệu Vải Mềm Mịn Khh...,93000,https://tiki.vn/quan-tay-nam-dang-om-chat-lieu...,NaN,144.0,quannam,13392000.0

In [15]:
df_all.to_csv("tk_quannam_all_ed.csv")