In [1]:
import pandas as pd
import os

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_190124(12htrua) - Copy (6)\thoitrangnam"
os.listdir(path)

['aohoodie',
 'aoni',
 'aosomi',
 'aothunnam',
 'aovest',
 'brand',
 'category.ipynb',
 'doboi',
 'dodoi',
 'dolot',
 'dongu',
 'quanaokichcolon',
 'quanaotrungnien',
 'quannam',
 'tk_aohoodie_all_ed.csv',
 'tk_aoni_all_ed.csv',
 'tk_aosomi_all_ed.csv',
 'tk_aothunnam_all_ed.csv',
 'tk_aovest_all_ed.csv',
 'tk_doboi_all_ed.csv',
 'tk_dodoi_all_ed.csv',
 'tk_dolot_all_ed.csv',
 'tk_dongu_all_ed.csv',
 'tk_quanaokichcolon_all_ed.csv',
 'tk_quanaotrungnien_all_ed.csv',
 'tk_quannam_all_ed.csv']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df = result

In [4]:
df

,Unnamed: 0,title,price,link_item,discount,sales,category,revenue
0,0,Áo hoodie nam nữ form rộng Unisex một màu in h...,179000,https://tka.tiki.vn/pixel/pixel?data=LnxjNKD0W...,-10%,925.0,aohoodie,165575000.0
1,1,Áo hoodie nam nữ form rộng Unisex một màu in h...,179000,https://tiki.vn/ao-hoodie-nam-nu-form-rong-uni...,-30%,925.0,aohoodie,165575000.0
2,2,Áo hoodie nỉ bông unisex Homies liền mũ có túi...,100000,https://tiki.vn/ao-hoodie-ni-bong-unisex-homie...,-30%,143.0,aohoodie,14300000.0
3,3,"Áo hoodie nam nữ form rộng siêu xinh , Áo khoá...",110000,https://tiki.vn/ao-hoodie-nam-nu-form-rong-sie...,-30%,23.0,aohoodie,2530000.0
4,4,Áo khoác hoodie nam nữ vải nỉ xịn quảng châu m...,115000,https://tiki.vn/ao-khoac-hoodie-nam-nu-vai-ni-...,-30%,2.0,aohoodie,230000.0
...,...,...,...,...,...,...,...,...
1002,1002,Quần dài thể thao nam Jogger 3 sọc ống xuông t...,89000,https://tiki.vn/quan-dai-the-thao-nam-jogger-3...,NaN,89.0,quannam,7921000.0
1003,1003,Quần Jean Nam Xanh Đậm Hàn Quốc XANHDAM52 - Xa...,134000,https://tiki.vn/quan-jean-nam-xanh-dam-han-quo...,NaN,75.0,quannam,10050000.0
1004,1004,Quần kaki dài nam (Tặng 1 dây nịt cao cấp) chấ...,255000,https://tiki.vn/quan-kaki-dai-nam-tang-1-day-n...,NaN,1.0,quannam,255000.0
1005,1005,Quần body nam Quần short jean nam có giãn shor...,115000,https://tiki.vn/quan-body-nam-quan-short-jean-...,NaN,4.0,quannam,460000.0
1006,1006,Quần jean nam co giãn dáng suông đẹp màu xanh ...,240000,https://tiki.vn/quan-jean-nam-co-gian-dang-suo...,NaN,2.0,quannam,480000.0

In [5]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [6]:
df.rename(columns={'category': 'item_list'}, inplace=True)

In [7]:
df.insert(6, "category", "thoitrangnam")

In [8]:
df

,title,price,link_item,discount,sales,item_list,category,revenue
0,Áo hoodie nam nữ form rộng Unisex một màu in h...,179000,https://tka.tiki.vn/pixel/pixel?data=LnxjNKD0W...,-10%,925.0,aohoodie,thoitrangnam,165575000.0
1,Áo hoodie nam nữ form rộng Unisex một màu in h...,179000,https://tiki.vn/ao-hoodie-nam-nu-form-rong-uni...,-30%,925.0,aohoodie,thoitrangnam,165575000.0
2,Áo hoodie nỉ bông unisex Homies liền mũ có túi...,100000,https://tiki.vn/ao-hoodie-ni-bong-unisex-homie...,-30%,143.0,aohoodie,thoitrangnam,14300000.0
3,"Áo hoodie nam nữ form rộng siêu xinh , Áo khoá...",110000,https://tiki.vn/ao-hoodie-nam-nu-form-rong-sie...,-30%,23.0,aohoodie,thoitrangnam,2530000.0
4,Áo khoác hoodie nam nữ vải nỉ xịn quảng châu m...,115000,https://tiki.vn/ao-khoac-hoodie-nam-nu-vai-ni-...,-30%,2.0,aohoodie,thoitrangnam,230000.0
...,...,...,...,...,...,...,...,...
1002,Quần dài thể thao nam Jogger 3 sọc ống xuông t...,89000,https://tiki.vn/quan-dai-the-thao-nam-jogger-3...,NaN,89.0,quannam,thoitrangnam,7921000.0
1003,Quần Jean Nam Xanh Đậm Hàn Quốc XANHDAM52 - Xa...,134000,https://tiki.vn/quan-jean-nam-xanh-dam-han-quo...,NaN,75.0,quannam,thoitrangnam,10050000.0
1004,Quần kaki dài nam (Tặng 1 dây nịt cao cấp) chấ...,255000,https://tiki.vn/quan-kaki-dai-nam-tang-1-day-n...,NaN,1.0,quannam,thoitrangnam,255000.0
1005,Quần body nam Quần short jean nam có giãn shor...,115000,https://tiki.vn/quan-body-nam-quan-short-jean-...,NaN,4.0,quannam,thoitrangnam,460000.0
1006,Quần jean nam co giãn dáng suông đẹp màu xanh ...,240000,https://tiki.vn/quan-jean-nam-co-gian-dang-suo...,NaN,2.0,quannam,thoitrangnam,480000.0

In [9]:
df.to_csv('tk_thoitrangnam_all_ed.csv', index=False, encoding='utf-8')