In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_170124(12htrua) - Copy (2)\dochoi_mevabe\thoitrangmevabe"
os.listdir(path)

['.ipynb_checkpoints',
 'tk_mvb_thoitrangmevabe.ipynb',
 'tk_mvb_thoitrangmevabe_npage.ipynb',
 'tk_thoitrangmevabe_all.ipynb',
 'tk_thoitrangmevabe_t1.csv',
 'tk_thoitrangmevabe_t10.csv',
 'tk_thoitrangmevabe_t11.csv',
 'tk_thoitrangmevabe_t12.csv',
 'tk_thoitrangmevabe_t13.csv',
 'tk_thoitrangmevabe_t14.csv',
 'tk_thoitrangmevabe_t15.csv',
 'tk_thoitrangmevabe_t16.csv',
 'tk_thoitrangmevabe_t17.csv',
 'tk_thoitrangmevabe_t18.csv',
 'tk_thoitrangmevabe_t19.csv',
 'tk_thoitrangmevabe_t2.csv',
 'tk_thoitrangmevabe_t20.csv',
 'tk_thoitrangmevabe_t21.csv',
 'tk_thoitrangmevabe_t22.csv',
 'tk_thoitrangmevabe_t23.csv',
 'tk_thoitrangmevabe_t24.csv',
 'tk_thoitrangmevabe_t25.csv',
 'tk_thoitrangmevabe_t26.csv',
 'tk_thoitrangmevabe_t27.csv',
 'tk_thoitrangmevabe_t28.csv',
 'tk_thoitrangmevabe_t29.csv',
 'tk_thoitrangmevabe_t3.csv',
 'tk_thoitrangmevabe_t30.csv',
 'tk_thoitrangmevabe_t31.csv',
 'tk_thoitrangmevabe_t32.csv',
 'tk_thoitrangmevabe_t33.csv',
 'tk_thoitrangmevabe_t34.csv',
 'tk_thoitrangmevabe_t35.csv',
 'tk_thoitrangmevabe_t36.csv',
 'tk_thoitrangmevabe_t37.csv',
 'tk_thoitrangmevabe_t38.csv',
 'tk_thoitrangmevabe_t39.csv',
 'tk_thoitrangmevabe_t4.csv',
 'tk_thoitrangmevabe_t40.csv',
 'tk_thoitrangmevabe_t41.csv',
 'tk_thoitrangmevabe_t42.csv',
 'tk_thoitrangmevabe_t43.csv',
 'tk_thoitrangmevabe_t44.csv',
 'tk_thoitrangmevabe_t45.csv',
 'tk_thoitrangmevabe_t46.csv',
 'tk_thoitrangmevabe_t47.csv',
 'tk_thoitrangmevabe_t48.csv',
 'tk_thoitrangmevabe_t49.csv',
 'tk_thoitrangmevabe_t5.csv',
 'tk_thoitrangmevabe_t50.csv',
 'tk_thoitrangmevabe_t6.csv',
 'tk_thoitrangmevabe_t7.csv',
 'tk_thoitrangmevabe_t8.csv',
 'tk_thoitrangmevabe_t9.csv']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_thoitrangmevabe_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales,category
0,Quần áo trẻ em Quần đùi short Bé gái nhiều họa...,39.000₫,https://tka.tiki.vn/pixel/pixel?data=_VuNTrwKa...,1,-30%,Đã bán 16,thoitrangmevabe
1,Vali Kéo Du Lịch Trẻ Em Hình Thú Ngộ Nghĩnh T09,279.000₫,https://tka.tiki.vn/pixel/pixel?data=2L-_3JLB5...,2,-30%,Đã bán 3,thoitrangmevabe
2,"The Cycling Lion, mã G73. Áo thun đẹp cho cả g...",179.000₫,https://tka.tiki.vn/pixel/pixel?data=oqaQRN4aN...,3,-30%,NaN,thoitrangmevabe
3,Dép trẻ em Sneaker Buzz Single Slide Easy-On 3...,280.000₫,https://tka.tiki.vn/pixel/pixel?data=7u3RndH-J...,4,-13%,NaN,thoitrangmevabe
4,Dép trẻ em Sneaker Buzz Clog Famility 8SBK234408,280.000₫,https://tka.tiki.vn/pixel/pixel?data=UtqUovEOs...,5,-30%,NaN,thoitrangmevabe
...,...,...,...,...,...,...,...
35,Bộ đồ ngủ hình thú pikachu vàng liền thân lông...,229.000₫,https://tiki.vn/bo-do-ngu-hinh-thu-pikachu-van...,36,NaN,Đã bán 42,thoitrangmevabe
36,Bộ kẹp tóc và cột tóc dành cho bé gái siêu dễ ...,39.000₫,https://tiki.vn/bo-kep-toc-va-cot-toc-danh-cho...,37,NaN,Đã bán 32,thoitrangmevabe
37,Đồ bộ bé trai vải thun hiệu MIMYKID in hình 3D...,42.000₫,https://tiki.vn/do-bo-be-trai-vai-thun-hieu-mi...,38,NaN,Đã bán 23,thoitrangmevabe
38,ÁO THUN CHO BÉ TRAI BÉ GÁI MẪU THE SHARK,39.000₫,https://tiki.vn/ao-thun-cho-be-trai-be-gai-mau...,39,NaN,Đã bán 47,thoitrangmevabe
39,"Bộ, Set Vest Đen, Xanh Cho Bé Trai, Trẻ Em, Co...",590.000₫,https://tiki.vn/bo-set-vest-den-xanh-cho-be-tr...,40,NaN,Đã bán 15,thoitrangmevabe

1. Xử lý dữ liệu

In [5]:
df_all = df_all.drop('index', axis=1)

In [6]:
df_all.dropna(subset=['sales'], inplace=True)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales,category
0,Quần áo trẻ em Quần đùi short Bé gái nhiều họa...,39.000₫,https://tka.tiki.vn/pixel/pixel?data=_VuNTrwKa...,-30%,Đã bán 16,thoitrangmevabe
1,Vali Kéo Du Lịch Trẻ Em Hình Thú Ngộ Nghĩnh T09,279.000₫,https://tka.tiki.vn/pixel/pixel?data=2L-_3JLB5...,-30%,Đã bán 3,thoitrangmevabe
2,VALI MINION MẮT TO - VUÔNG,385.000₫,https://tiki.vn/vali-minion-mat-to-vuong-p1746...,-30%,Đã bán 156,thoitrangmevabe
3,BA LÔ CHỐNG GÙ HÌNH GẤU CHO BÉ,109.000₫,https://tiki.vn/ba-lo-chong-gu-hinh-gau-cho-be...,-30%,Đã bán 38,thoitrangmevabe
4,BALO HỌC SINH MR VUI 883 CHO BÉ GÁI VÀ BÉ TRAI...,360.000₫,https://tiki.vn/balo-hoc-sinh-mr-vui-883-cho-b...,-25%,Đã bán 6,thoitrangmevabe
...,...,...,...,...,...,...
1829,Bộ đồ ngủ hình thú pikachu vàng liền thân lông...,229.000₫,https://tiki.vn/bo-do-ngu-hinh-thu-pikachu-van...,NaN,Đã bán 42,thoitrangmevabe
1830,Bộ kẹp tóc và cột tóc dành cho bé gái siêu dễ ...,39.000₫,https://tiki.vn/bo-kep-toc-va-cot-toc-danh-cho...,NaN,Đã bán 32,thoitrangmevabe
1831,Đồ bộ bé trai vải thun hiệu MIMYKID in hình 3D...,42.000₫,https://tiki.vn/do-bo-be-trai-vai-thun-hieu-mi...,NaN,Đã bán 23,thoitrangmevabe
1832,ÁO THUN CHO BÉ TRAI BÉ GÁI MẪU THE SHARK,39.000₫,https://tiki.vn/ao-thun-cho-be-trai-be-gai-mau...,NaN,Đã bán 47,thoitrangmevabe
1833,"Bộ, Set Vest Đen, Xanh Cho Bé Trai, Trẻ Em, Co...",590.000₫,https://tiki.vn/bo-set-vest-den-xanh-cho-be-tr...,NaN,Đã bán 15,thoitrangmevabe

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0        39000
1       279000
2       385000
3       109000
4       360000
         ...
1829    229000
1830     39000
1831     42000
1832     39000
1833    590000
Name: price, Length: 1834, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0        16.0
1         3.0
2       156.0
3        38.0
4         6.0
        ...
1829     42.0
1830     32.0
1831     23.0
1832     47.0
1833     15.0
Name: sales, Length: 1834, dtype: float64

In [11]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0         624000.0
1         837000.0
2       60060000.0
3        4142000.0
4        2160000.0
           ...
1829     9618000.0
1830     1248000.0
1831      966000.0
1832     1833000.0
1833     8850000.0
Name: revenue, Length: 1834, dtype: float64

In [12]:
total = df_all["revenue"].sum()

In [13]:
print("Tổng doanh số thoitrangmevabe: ", total)
print("So mat hang da ban: ", len(df_all["title"])) # san pham da ban
print("So san pham da ban: ", df_all["sales"].sum()) # san pham co luot ban

Tổng doanh số thoitrangmevabe:  8088452092.0
So mat hang da ban:  1834
So san pham da ban:  67496.0

In [14]:
df_all

,title,price,link_item,discount,sales,category,revenue
0,Quần áo trẻ em Quần đùi short Bé gái nhiều họa...,39000,https://tka.tiki.vn/pixel/pixel?data=_VuNTrwKa...,-30%,16.0,thoitrangmevabe,624000.0
1,Vali Kéo Du Lịch Trẻ Em Hình Thú Ngộ Nghĩnh T09,279000,https://tka.tiki.vn/pixel/pixel?data=2L-_3JLB5...,-30%,3.0,thoitrangmevabe,837000.0
2,VALI MINION MẮT TO - VUÔNG,385000,https://tiki.vn/vali-minion-mat-to-vuong-p1746...,-30%,156.0,thoitrangmevabe,60060000.0
3,BA LÔ CHỐNG GÙ HÌNH GẤU CHO BÉ,109000,https://tiki.vn/ba-lo-chong-gu-hinh-gau-cho-be...,-30%,38.0,thoitrangmevabe,4142000.0
4,BALO HỌC SINH MR VUI 883 CHO BÉ GÁI VÀ BÉ TRAI...,360000,https://tiki.vn/balo-hoc-sinh-mr-vui-883-cho-b...,-25%,6.0,thoitrangmevabe,2160000.0
...,...,...,...,...,...,...,...
1829,Bộ đồ ngủ hình thú pikachu vàng liền thân lông...,229000,https://tiki.vn/bo-do-ngu-hinh-thu-pikachu-van...,NaN,42.0,thoitrangmevabe,9618000.0
1830,Bộ kẹp tóc và cột tóc dành cho bé gái siêu dễ ...,39000,https://tiki.vn/bo-kep-toc-va-cot-toc-danh-cho...,NaN,32.0,thoitrangmevabe,1248000.0
1831,Đồ bộ bé trai vải thun hiệu MIMYKID in hình 3D...,42000,https://tiki.vn/do-bo-be-trai-vai-thun-hieu-mi...,NaN,23.0,thoitrangmevabe,966000.0
1832,ÁO THUN CHO BÉ TRAI BÉ GÁI MẪU THE SHARK,39000,https://tiki.vn/ao-thun-cho-be-trai-be-gai-mau...,NaN,47.0,thoitrangmevabe,1833000.0
1833,"Bộ, Set Vest Đen, Xanh Cho Bé Trai, Trẻ Em, Co...",590000,https://tiki.vn/bo-set-vest-den-xanh-cho-be-tr...,NaN,15.0,thoitrangmevabe,8850000.0

In [15]:
df_all.to_csv("tk_thoitrangmevabe_all_ed.csv")