In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_160124(12hdem)\thoitrangnu\dolot"
os.listdir(path)

['.ipynb_checkpoints',
 'tk_dolotnu.csv',
 'tk_dolot_all.ipynb',
 'tk_ttn_dl.ipynb',
 'tk_ttn_dl_npage.ipynb',
 'tk_ttn_dolotnu_t10.csv',
 'tk_ttn_dolotnu_t11.csv',
 'tk_ttn_dolotnu_t12.csv',
 'tk_ttn_dolotnu_t13.csv',
 'tk_ttn_dolotnu_t14.csv',
 'tk_ttn_dolotnu_t15.csv',
 'tk_ttn_dolotnu_t16.csv',
 'tk_ttn_dolotnu_t17.csv',
 'tk_ttn_dolotnu_t18.csv',
 'tk_ttn_dolotnu_t19.csv',
 'tk_ttn_dolotnu_t2.csv',
 'tk_ttn_dolotnu_t20.csv',
 'tk_ttn_dolotnu_t21.csv',
 'tk_ttn_dolotnu_t22.csv',
 'tk_ttn_dolotnu_t23.csv',
 'tk_ttn_dolotnu_t24.csv',
 'tk_ttn_dolotnu_t25.csv',
 'tk_ttn_dolotnu_t26.csv',
 'tk_ttn_dolotnu_t27.csv',
 'tk_ttn_dolotnu_t28.csv',
 'tk_ttn_dolotnu_t29.csv',
 'tk_ttn_dolotnu_t3.csv',
 'tk_ttn_dolotnu_t30.csv',
 'tk_ttn_dolotnu_t31.csv',
 'tk_ttn_dolotnu_t32.csv',
 'tk_ttn_dolotnu_t33.csv',
 'tk_ttn_dolotnu_t34.csv',
 'tk_ttn_dolotnu_t35.csv',
 'tk_ttn_dolotnu_t36.csv',
 'tk_ttn_dolotnu_t37.csv',
 'tk_ttn_dolotnu_t38.csv',
 'tk_ttn_dolotnu_t39.csv',
 'tk_ttn_dolotnu_t4.csv',
 'tk_ttn_dolotnu_t40.csv',
 'tk_ttn_dolotnu_t41.csv',
 'tk_ttn_dolotnu_t42.csv',
 'tk_ttn_dolotnu_t43.csv',
 'tk_ttn_dolotnu_t44.csv',
 'tk_ttn_dolotnu_t45.csv',
 'tk_ttn_dolotnu_t46.csv',
 'tk_ttn_dolotnu_t47.csv',
 'tk_ttn_dolotnu_t48.csv',
 'tk_ttn_dolotnu_t49.csv',
 'tk_ttn_dolotnu_t5.csv',
 'tk_ttn_dolotnu_t50.csv',
 'tk_ttn_dolotnu_t6.csv',
 'tk_ttn_dolotnu_t7.csv',
 'tk_ttn_dolotnu_t8.csv',
 'tk_ttn_dolotnu_t9.csv']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_dolot_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales,category
0,Áo ngực có gọng mút vừa T-Shirt smothie iBasic...,199.000₫,https://tka.tiki.vn/pixel/pixel?data=FnxS2csFi...,1,-33%,Đã bán 86,dolotnu
1,Áo ngực học sinh tròng cổ viền ren iBasic BRAT005,129.000₫,https://tka.tiki.vn/pixel/pixel?data=Lsmzn6gLL...,2,-41%,Đã bán 79,dolotnu
2,Áo ngực mút mỏng không gọng iBasic VA029,219.000₫,https://tka.tiki.vn/pixel/pixel?data=F59wcYjIZ...,3,-8%,Đã bán 281,dolotnu
3,Áo ngực không gọng mút mỏng ren phối dây Tshir...,199.000₫,https://tka.tiki.vn/pixel/pixel?data=IUM6LhiXA...,4,-75%,Đã bán 6,dolotnu
4,Combo 3 áo lót học sinh ngắn không mút iBasic ...,180.000₫,https://tka.tiki.vn/pixel/pixel?data=UMRsIfFNB...,5,-13%,Đã bán 37,dolotnu
...,...,...,...,...,...,...,...
35,NaN,NaN,https://tiki.vn/quan-lot-nu-nang-mong-thoang-m...,36,NaN,NaN,dolotnu
36,Combo 10 Quần lót nữ cotton trơn cao cấp Vicci...,450.000₫,https://tiki.vn/combo-10-quan-lot-nu-cotton-tr...,37,NaN,Đã bán 2,dolotnu
37,Bộ 5 Quần Lót Ren phối nơ cực sexy thương hiệu...,294.000₫,https://tiki.vn/bo-5-quan-lot-ren-phoi-no-cuc-...,38,NaN,Đã bán 1,dolotnu
38,Áo Ngực Su Hình Lá Nâng Ngực Không Gọng Đệm 3c...,88.000₫,https://tiki.vn/ao-nguc-su-hinh-la-nang-nguc-k...,39,NaN,Đã bán 456,dolotnu
39,Quần su mặc trong váy đùi đúc thông hơi COCO LAND,39.000₫,https://tiki.vn/quan-su-mac-trong-vay-dui-duc-...,40,NaN,Đã bán 1,dolotnu

1. Xử lý dữ liệu

In [5]:
df_all = df_all.drop('index', axis=1)

In [6]:
df_all.dropna(subset=['sales'], inplace=True)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales,category
0,Áo ngực có gọng mút vừa T-Shirt smothie iBasic...,199.000₫,https://tka.tiki.vn/pixel/pixel?data=FnxS2csFi...,-33%,Đã bán 86,dolotnu
1,Áo ngực học sinh tròng cổ viền ren iBasic BRAT005,129.000₫,https://tka.tiki.vn/pixel/pixel?data=Lsmzn6gLL...,-41%,Đã bán 79,dolotnu
2,Áo ngực mút mỏng không gọng iBasic VA029,219.000₫,https://tka.tiki.vn/pixel/pixel?data=F59wcYjIZ...,-8%,Đã bán 281,dolotnu
3,Áo ngực không gọng mút mỏng ren phối dây Tshir...,199.000₫,https://tka.tiki.vn/pixel/pixel?data=IUM6LhiXA...,-75%,Đã bán 6,dolotnu
4,Combo 3 áo lót học sinh ngắn không mút iBasic ...,180.000₫,https://tka.tiki.vn/pixel/pixel?data=UMRsIfFNB...,-13%,Đã bán 37,dolotnu
...,...,...,...,...,...,...
1179,Quần lót lọt khe ren 2 dây chéo mông cách điệu,29.000₫,https://tiki.vn/quan-lot-lot-khe-ren-2-day-che...,NaN,Đã bán 4,dolotnu
1180,Combo 10 Quần lót nữ cotton trơn cao cấp Vicci...,450.000₫,https://tiki.vn/combo-10-quan-lot-nu-cotton-tr...,NaN,Đã bán 2,dolotnu
1181,Bộ 5 Quần Lót Ren phối nơ cực sexy thương hiệu...,294.000₫,https://tiki.vn/bo-5-quan-lot-ren-phoi-no-cuc-...,NaN,Đã bán 1,dolotnu
1182,Áo Ngực Su Hình Lá Nâng Ngực Không Gọng Đệm 3c...,88.000₫,https://tiki.vn/ao-nguc-su-hinh-la-nang-nguc-k...,NaN,Đã bán 456,dolotnu
1183,Quần su mặc trong váy đùi đúc thông hơi COCO LAND,39.000₫,https://tiki.vn/quan-su-mac-trong-vay-dui-duc-...,NaN,Đã bán 1,dolotnu

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0       199000
1       129000
2       219000
3       199000
4       180000
         ...
1179     29000
1180    450000
1181    294000
1182     88000
1183     39000
Name: price, Length: 1184, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0        86.0
1        79.0
2       281.0
3         6.0
4        37.0
        ...
1179      4.0
1180      2.0
1181      1.0
1182    456.0
1183      1.0
Name: sales, Length: 1184, dtype: float64

In [11]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0       17114000.0
1       10191000.0
2       61539000.0
3        1194000.0
4        6660000.0
           ...
1179      116000.0
1180      900000.0
1181      294000.0
1182    40128000.0
1183       39000.0
Name: revenue, Length: 1184, dtype: float64

In [12]:
total = df_all["revenue"].sum()

In [13]:
print("Tổng doanh số dolot: ", total)
print("So mat hang da ban: ", len(df_all["title"])) # san pham da ban
print("So san pham da ban: ", df_all["sales"].sum()) # san pham co luot ban

Tổng doanh số dolot:  9549871749.0
So mat hang da ban:  1184
So san pham da ban:  77383.0

In [14]:
df_all

,title,price,link_item,discount,sales,category,revenue
0,Áo ngực có gọng mút vừa T-Shirt smothie iBasic...,199000,https://tka.tiki.vn/pixel/pixel?data=FnxS2csFi...,-33%,86.0,dolotnu,17114000.0
1,Áo ngực học sinh tròng cổ viền ren iBasic BRAT005,129000,https://tka.tiki.vn/pixel/pixel?data=Lsmzn6gLL...,-41%,79.0,dolotnu,10191000.0
2,Áo ngực mút mỏng không gọng iBasic VA029,219000,https://tka.tiki.vn/pixel/pixel?data=F59wcYjIZ...,-8%,281.0,dolotnu,61539000.0
3,Áo ngực không gọng mút mỏng ren phối dây Tshir...,199000,https://tka.tiki.vn/pixel/pixel?data=IUM6LhiXA...,-75%,6.0,dolotnu,1194000.0
4,Combo 3 áo lót học sinh ngắn không mút iBasic ...,180000,https://tka.tiki.vn/pixel/pixel?data=UMRsIfFNB...,-13%,37.0,dolotnu,6660000.0
...,...,...,...,...,...,...,...
1179,Quần lót lọt khe ren 2 dây chéo mông cách điệu,29000,https://tiki.vn/quan-lot-lot-khe-ren-2-day-che...,NaN,4.0,dolotnu,116000.0
1180,Combo 10 Quần lót nữ cotton trơn cao cấp Vicci...,450000,https://tiki.vn/combo-10-quan-lot-nu-cotton-tr...,NaN,2.0,dolotnu,900000.0
1181,Bộ 5 Quần Lót Ren phối nơ cực sexy thương hiệu...,294000,https://tiki.vn/bo-5-quan-lot-ren-phoi-no-cuc-...,NaN,1.0,dolotnu,294000.0
1182,Áo Ngực Su Hình Lá Nâng Ngực Không Gọng Đệm 3c...,88000,https://tiki.vn/ao-nguc-su-hinh-la-nang-nguc-k...,NaN,456.0,dolotnu,40128000.0
1183,Quần su mặc trong váy đùi đúc thông hơi COCO LAND,39000,https://tiki.vn/quan-su-mac-trong-vay-dui-duc-...,NaN,1.0,dolotnu,39000.0

In [15]:
df_all.to_csv("tk_dolot_all_ed.csv")