In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_160124(12hdem)\thoitrangnam\dolot"
os.listdir(path)

['tk_dolotnam.csv',
 'tk_dolotnam.ipynb',
 'tk_dolot_all.ipynb',
 'tk_ttn_dolotnam_npage.ipynb',
 'tk_ttn_dolotnam_t10.csv',
 'tk_ttn_dolotnam_t11.csv',
 'tk_ttn_dolotnam_t12.csv',
 'tk_ttn_dolotnam_t13.csv',
 'tk_ttn_dolotnam_t14.csv',
 'tk_ttn_dolotnam_t15.csv',
 'tk_ttn_dolotnam_t16.csv',
 'tk_ttn_dolotnam_t17.csv',
 'tk_ttn_dolotnam_t18.csv',
 'tk_ttn_dolotnam_t19.csv',
 'tk_ttn_dolotnam_t2.csv',
 'tk_ttn_dolotnam_t20.csv',
 'tk_ttn_dolotnam_t21.csv',
 'tk_ttn_dolotnam_t22.csv',
 'tk_ttn_dolotnam_t23.csv',
 'tk_ttn_dolotnam_t24.csv',
 'tk_ttn_dolotnam_t25.csv',
 'tk_ttn_dolotnam_t26.csv',
 'tk_ttn_dolotnam_t27.csv',
 'tk_ttn_dolotnam_t28.csv',
 'tk_ttn_dolotnam_t29.csv',
 'tk_ttn_dolotnam_t3.csv',
 'tk_ttn_dolotnam_t30.csv',
 'tk_ttn_dolotnam_t31.csv',
 'tk_ttn_dolotnam_t32.csv',
 'tk_ttn_dolotnam_t33.csv',
 'tk_ttn_dolotnam_t34.csv',
 'tk_ttn_dolotnam_t35.csv',
 'tk_ttn_dolotnam_t36.csv',
 'tk_ttn_dolotnam_t37.csv',
 'tk_ttn_dolotnam_t38.csv',
 'tk_ttn_dolotnam_t39.csv',
 'tk_ttn_dolotnam_t4.csv',
 'tk_ttn_dolotnam_t40.csv',
 'tk_ttn_dolotnam_t41.csv',
 'tk_ttn_dolotnam_t42.csv',
 'tk_ttn_dolotnam_t43.csv',
 'tk_ttn_dolotnam_t44.csv',
 'tk_ttn_dolotnam_t45.csv',
 'tk_ttn_dolotnam_t46.csv',
 'tk_ttn_dolotnam_t47.csv',
 'tk_ttn_dolotnam_t48.csv',
 'tk_ttn_dolotnam_t49.csv',
 'tk_ttn_dolotnam_t5.csv',
 'tk_ttn_dolotnam_t6.csv',
 'tk_ttn_dolotnam_t7.csv',
 'tk_ttn_dolotnam_t8.csv',
 'tk_ttn_dolotnam_t9.csv']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_dolot_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales,category
0,Combo 4 quần lót nam Boxer sợi cạp 1cm sợ...,245.000₫,https://tka.tiki.vn/pixel/pixel?data=yMhW02Fj3...,1,-28%,Đã bán 5.0k,dolotnam
1,Combo 4 quần lót nam tam giác Bamboo Organi...,239.000₫,https://tka.tiki.vn/pixel/pixel?data=q1XadWR1F...,2,-30%,Đã bán 3.2k,dolotnam
2,SET 5 Chiếc Quần Lót Nam Không đường may cao c...,280.000₫,https://tka.tiki.vn/pixel/pixel?data=jQJVjQmbw...,3,-11%,Đã bán 9,dolotnam
3,"Quần Lót Nam Không đường may cao cấp BADBIRD, ...",67.000₫,https://tka.tiki.vn/pixel/pixel?data=6Doqc7fY2...,4,-11%,Đã bán 7,dolotnam
4,SET 3 Chiếc Quần Lót Nam Không đường may cao c...,177.000₫,https://tka.tiki.vn/pixel/pixel?data=vuyF_oav1...,5,-11%,Đã bán 6,dolotnam
...,...,...,...,...,...,...,...
35,NaN,NaN,https://tiki.vn/quan-lot-nam-sexy-day-coac-2-b...,36,NaN,NaN,dolotnam
36,Quần lót lọt khe dây gợi cảm,23.000₫,https://tiki.vn/quan-lot-lot-khe-day-goi-cam-p...,37,NaN,NaN,dolotnam
37,Quần lót nam lọt khe hình bướm chữ G,45.000₫,https://tiki.vn/quan-lot-nam-lot-khe-hinh-buom...,38,NaN,NaN,dolotnam
38,Quần lót nam ren lưới thoáng mát - QL06A,95.000₫,https://tiki.vn/quan-lot-nam-ren-luoi-thoang-m...,39,NaN,Đã bán 15,dolotnam
39,Combo 4 Quần Lót Nam Quần Sịp Nam Sợi Cotton C...,239.000,https://tiki.vn/combo-4-quan-sip-nam-quan-lot-...,40,NaN,NaN,dolotnam

1. Xử lý dữ liệu

In [5]:
df_all = df_all.drop('index', axis=1)

In [6]:
df_all.dropna(subset=['sales'], inplace=True)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales,category
0,Combo 4 quần lót nam Boxer sợi cạp 1cm sợ...,245.000₫,https://tka.tiki.vn/pixel/pixel?data=yMhW02Fj3...,-28%,Đã bán 5.0k,dolotnam
1,Combo 4 quần lót nam tam giác Bamboo Organi...,239.000₫,https://tka.tiki.vn/pixel/pixel?data=q1XadWR1F...,-30%,Đã bán 3.2k,dolotnam
2,SET 5 Chiếc Quần Lót Nam Không đường may cao c...,280.000₫,https://tka.tiki.vn/pixel/pixel?data=jQJVjQmbw...,-11%,Đã bán 9,dolotnam
3,"Quần Lót Nam Không đường may cao cấp BADBIRD, ...",67.000₫,https://tka.tiki.vn/pixel/pixel?data=6Doqc7fY2...,-11%,Đã bán 7,dolotnam
4,SET 3 Chiếc Quần Lót Nam Không đường may cao c...,177.000₫,https://tka.tiki.vn/pixel/pixel?data=vuyF_oav1...,-11%,Đã bán 6,dolotnam
...,...,...,...,...,...,...
714,Quần lót nam lưng thấp dạng dây thiết kế siêu ...,45.000₫,https://tiki.vn/quan-lot-nam-lung-thap-dang-da...,NaN,Đã bán 24,dolotnam
715,Quần lót nam Thong Sexy Vải Ren Manvenbeck MK0...,65.000₫,https://tiki.vn/quan-lot-nam-thong-sexy-vai-re...,NaN,Đã bán 8,dolotnam
716,Quần lót nam sét 4 quần cao cấp đủ size 35-> 85kg,150.000₫,https://tiki.vn/quan-lot-nam-set-4-quan-cao-ca...,NaN,Đã bán 3,dolotnam
717,LÓT NAM-MS:6043(Freeman)cotton lụa 4 chiều,47.610₫,https://tiki.vn/lot-nam-ms-6043-freeman-cotton...,NaN,Đã bán 4,dolotnam
718,Quần lót nam ren lưới thoáng mát - QL06A,95.000₫,https://tiki.vn/quan-lot-nam-ren-luoi-thoang-m...,NaN,Đã bán 15,dolotnam

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0      245000
1      239000
2      280000
3       67000
4      177000
        ...
714     45000
715     65000
716    150000
717     47610
718     95000
Name: price, Length: 719, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0      5000.0
1      3200.0
2         9.0
3         7.0
4         6.0
        ...
714      24.0
715       8.0
716       3.0
717       4.0
718      15.0
Name: sales, Length: 719, dtype: float64

In [11]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0      1.225000e+09
1      7.648000e+08
2      2.520000e+06
3      4.690000e+05
4      1.062000e+06
           ...
714    1.080000e+06
715    5.200000e+05
716    4.500000e+05
717    1.904400e+05
718    1.425000e+06
Name: revenue, Length: 719, dtype: float64

In [12]:
total = df_all["revenue"].sum()

In [13]:
print("Tổng doanh số dolot: ", total)
print("So mat hang da ban: ", len(df_all["title"])) # san pham da ban
print("So san pham da ban: ", df_all["sales"].sum()) # san pham co luot ban

Tổng doanh số dolot:  13654617918.0
So mat hang da ban:  719
So san pham da ban:  101746.0

In [14]:
df_all

,title,price,link_item,discount,sales,category,revenue
0,Combo 4 quần lót nam Boxer sợi cạp 1cm sợ...,245000,https://tka.tiki.vn/pixel/pixel?data=yMhW02Fj3...,-28%,5000.0,dolotnam,1.225000e+09
1,Combo 4 quần lót nam tam giác Bamboo Organi...,239000,https://tka.tiki.vn/pixel/pixel?data=q1XadWR1F...,-30%,3200.0,dolotnam,7.648000e+08
2,SET 5 Chiếc Quần Lót Nam Không đường may cao c...,280000,https://tka.tiki.vn/pixel/pixel?data=jQJVjQmbw...,-11%,9.0,dolotnam,2.520000e+06
3,"Quần Lót Nam Không đường may cao cấp BADBIRD, ...",67000,https://tka.tiki.vn/pixel/pixel?data=6Doqc7fY2...,-11%,7.0,dolotnam,4.690000e+05
4,SET 3 Chiếc Quần Lót Nam Không đường may cao c...,177000,https://tka.tiki.vn/pixel/pixel?data=vuyF_oav1...,-11%,6.0,dolotnam,1.062000e+06
...,...,...,...,...,...,...,...
714,Quần lót nam lưng thấp dạng dây thiết kế siêu ...,45000,https://tiki.vn/quan-lot-nam-lung-thap-dang-da...,NaN,24.0,dolotnam,1.080000e+06
715,Quần lót nam Thong Sexy Vải Ren Manvenbeck MK0...,65000,https://tiki.vn/quan-lot-nam-thong-sexy-vai-re...,NaN,8.0,dolotnam,5.200000e+05
716,Quần lót nam sét 4 quần cao cấp đủ size 35-> 85kg,150000,https://tiki.vn/quan-lot-nam-set-4-quan-cao-ca...,NaN,3.0,dolotnam,4.500000e+05
717,LÓT NAM-MS:6043(Freeman)cotton lụa 4 chiều,47610,https://tiki.vn/lot-nam-ms-6043-freeman-cotton...,NaN,4.0,dolotnam,1.904400e+05
718,Quần lót nam ren lưới thoáng mát - QL06A,95000,https://tiki.vn/quan-lot-nam-ren-luoi-thoang-m...,NaN,15.0,dolotnam,1.425000e+06

In [15]:
df_all.to_csv("tk_dolot_all_ed.csv")