In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_190124(12htrua) - Copy (6)\thoitrangnu\quannu"
os.listdir(path)

['.ipynb_checkpoints',
 'tk_quannu_all.ipynb',
 'tk_ttn_qn.ipynb',
 'tk_ttn_qn_npage.ipynb',
 'tk_ttn_qn_t1.csv',
 'tk_ttn_qn_t10.csv',
 'tk_ttn_qn_t11.csv',
 'tk_ttn_qn_t12.csv',
 'tk_ttn_qn_t13.csv',
 'tk_ttn_qn_t14.csv',
 'tk_ttn_qn_t15.csv',
 'tk_ttn_qn_t16.csv',
 'tk_ttn_qn_t17.csv',
 'tk_ttn_qn_t18.csv',
 'tk_ttn_qn_t19.csv',
 'tk_ttn_qn_t2.csv',
 'tk_ttn_qn_t20.csv',
 'tk_ttn_qn_t21.csv',
 'tk_ttn_qn_t22.csv',
 'tk_ttn_qn_t23.csv',
 'tk_ttn_qn_t24.csv',
 'tk_ttn_qn_t25.csv',
 'tk_ttn_qn_t26.csv',
 'tk_ttn_qn_t27.csv',
 'tk_ttn_qn_t28.csv',
 'tk_ttn_qn_t29.csv',
 'tk_ttn_qn_t3.csv',
 'tk_ttn_qn_t30.csv',
 'tk_ttn_qn_t31.csv',
 'tk_ttn_qn_t32.csv',
 'tk_ttn_qn_t33.csv',
 'tk_ttn_qn_t34.csv',
 'tk_ttn_qn_t35.csv',
 'tk_ttn_qn_t36.csv',
 'tk_ttn_qn_t37.csv',
 'tk_ttn_qn_t38.csv',
 'tk_ttn_qn_t39.csv',
 'tk_ttn_qn_t4.csv',
 'tk_ttn_qn_t40.csv',
 'tk_ttn_qn_t41.csv',
 'tk_ttn_qn_t42.csv',
 'tk_ttn_qn_t43.csv',
 'tk_ttn_qn_t44.csv',
 'tk_ttn_qn_t45.csv',
 'tk_ttn_qn_t46.csv',
 'tk_ttn_qn_t47.csv',
 'tk_ttn_qn_t48.csv',
 'tk_ttn_qn_t49.csv',
 'tk_ttn_qn_t5.csv',
 'tk_ttn_qn_t50.csv',
 'tk_ttn_qn_t6.csv',
 'tk_ttn_qn_t7.csv',
 'tk_ttn_qn_t8.csv',
 'tk_ttn_qn_t9.csv']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_quannu_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales,category
0,"Quần short kaki nữ GOKING, lưng thun và dây rú...",185.000₫,https://tka.tiki.vn/pixel/pixel?data=sK5ekYKEj...,1,-8%,Đã bán 268,quannu
1,Quần Lengging Lửng Nữ Chất Thun Co Dãn 4 Chiều...,45.000₫,https://tka.tiki.vn/pixel/pixel?data=ySoIiYu13...,2,NaN,Đã bán 265,quannu
2,Quần Legging nâng mông gen bụng chất su đúc fu...,165.000₫,https://tka.tiki.vn/pixel/pixel?data=RC8JXSTNK...,3,NaN,Đã bán 4,quannu
3,Quần Legging Nữ Dài Cạp Cao Đẹp Cao Cấp PINKAH...,215.000,https://tka.tiki.vn/pixel/pixel?data=PqdSnIUIv...,4,-50%,NaN,quannu
4,NaN,NaN,https://tka.tiki.vn/pixel/pixel?data=CxwTmIR7W...,5,-21%,NaN,quannu
...,...,...,...,...,...,...,...
35,NaN,NaN,https://tiki.vn/quan-dui-nu-cap-chun-banamo-qu...,36,NaN,NaN,quannu
36,"Quần ống sớ, quần nữ dáng suông ống rộng khóa ...",159.000₫,https://tiki.vn/quan-ong-so-quan-nu-dang-suong...,37,NaN,Đã bán 89,quannu
37,Quần ống rộng gân tăm đai nơ chất cotton co giãn,79.000₫,https://tiki.vn/quan-ong-rong-gan-tam-dai-no-c...,38,NaN,Đã bán 66,quannu
38,Quần DirtyCoins Khaki Work Shorts,399.000₫,https://tiki.vn/quan-dirtycoins-khaki-work-sho...,39,NaN,NaN,quannu
39,Quần JOGGER Nữ Thể Thao Chất Vải Thun Lạnh Mềm...,198.000,https://tiki.vn/quan-jogger-nu-the-thao-chat-v...,40,NaN,NaN,quannu

1. Xử lý dữ liệu

In [5]:
df_all = df_all.drop('index', axis=1)

In [6]:
df_all.dropna(subset=['sales'], inplace=True)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales,category
0,"Quần short kaki nữ GOKING, lưng thun và dây rú...",185.000₫,https://tka.tiki.vn/pixel/pixel?data=sK5ekYKEj...,-8%,Đã bán 268,quannu
1,Quần Lengging Lửng Nữ Chất Thun Co Dãn 4 Chiều...,45.000₫,https://tka.tiki.vn/pixel/pixel?data=ySoIiYu13...,NaN,Đã bán 265,quannu
2,Quần Legging nâng mông gen bụng chất su đúc fu...,165.000₫,https://tka.tiki.vn/pixel/pixel?data=RC8JXSTNK...,NaN,Đã bán 4,quannu
3,"Quần Đùi Nữ Mặc Nhà Chất vải Lụa Hàn Quốc ,Mịn...",39.500₫,https://tiki.vn/quan-dui-nu-mac-nha-quan-dui-n...,NaN,Đã bán 239,quannu
4,"Quần ống rộng nữ, quần ống suông đũi Gu chun l...",69.000₫,https://tiki.vn/quan-ong-rong-nu-quan-ong-suon...,-9%,Đã bán 148,quannu
...,...,...,...,...,...,...
811,"Quần Jean nữ Suông mẫu basic QJ280, Thanh lịch...",199.000₫,https://tiki.vn/quan-jean-nu-suong-mau-basic-q...,NaN,Đã bán 1,quannu
812,Quần nữ thời trang kiểu Hàn Quốc Thu Hà chất l...,149.000₫,https://tiki.vn/quan-nu-thoi-trang-kieu-han-qu...,NaN,Đã bán 3,quannu
813,Quần Jean Nữ ỐNg Loe Lưng CAo Co Giãn Tôn Dáng...,199.900₫,https://tiki.vn/quan-jean-nu-ong-loe-lung-cao-...,NaN,Đã bán 1,quannu
814,"Quần ống sớ, quần nữ dáng suông ống rộng khóa ...",159.000₫,https://tiki.vn/quan-ong-so-quan-nu-dang-suong...,NaN,Đã bán 89,quannu
815,Quần ống rộng gân tăm đai nơ chất cotton co giãn,79.000₫,https://tiki.vn/quan-ong-rong-gan-tam-dai-no-c...,NaN,Đã bán 66,quannu

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0      185000
1       45000
2      165000
3       39500
4       69000
        ...
811    199000
812    149000
813    199900
814    159000
815     79000
Name: price, Length: 816, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0      268.0
1      265.0
2        4.0
3      239.0
4      148.0
       ...
811      1.0
812      3.0
813      1.0
814     89.0
815     66.0
Name: sales, Length: 816, dtype: float64

In [11]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0      49580000.0
1      11925000.0
2        660000.0
3       9440500.0
4      10212000.0
          ...
811      199000.0
812      447000.0
813      199900.0
814    14151000.0
815     5214000.0
Name: revenue, Length: 816, dtype: float64

In [12]:
total = df_all["revenue"].sum()

In [13]:
print("Tổng doanh số quannu: ", total)
print("So mat hang da ban: ", len(df_all["title"])) # san pham da ban
print("So san pham da ban: ", df_all["sales"].sum()) # san pham co luot ban

Tổng doanh số quannu:  3497163505.0
So mat hang da ban:  816
So san pham da ban:  26039.0

In [14]:
df_all

,title,price,link_item,discount,sales,category,revenue
0,"Quần short kaki nữ GOKING, lưng thun và dây rú...",185000,https://tka.tiki.vn/pixel/pixel?data=sK5ekYKEj...,-8%,268.0,quannu,49580000.0
1,Quần Lengging Lửng Nữ Chất Thun Co Dãn 4 Chiều...,45000,https://tka.tiki.vn/pixel/pixel?data=ySoIiYu13...,NaN,265.0,quannu,11925000.0
2,Quần Legging nâng mông gen bụng chất su đúc fu...,165000,https://tka.tiki.vn/pixel/pixel?data=RC8JXSTNK...,NaN,4.0,quannu,660000.0
3,"Quần Đùi Nữ Mặc Nhà Chất vải Lụa Hàn Quốc ,Mịn...",39500,https://tiki.vn/quan-dui-nu-mac-nha-quan-dui-n...,NaN,239.0,quannu,9440500.0
4,"Quần ống rộng nữ, quần ống suông đũi Gu chun l...",69000,https://tiki.vn/quan-ong-rong-nu-quan-ong-suon...,-9%,148.0,quannu,10212000.0
...,...,...,...,...,...,...,...
811,"Quần Jean nữ Suông mẫu basic QJ280, Thanh lịch...",199000,https://tiki.vn/quan-jean-nu-suong-mau-basic-q...,NaN,1.0,quannu,199000.0
812,Quần nữ thời trang kiểu Hàn Quốc Thu Hà chất l...,149000,https://tiki.vn/quan-nu-thoi-trang-kieu-han-qu...,NaN,3.0,quannu,447000.0
813,Quần Jean Nữ ỐNg Loe Lưng CAo Co Giãn Tôn Dáng...,199900,https://tiki.vn/quan-jean-nu-ong-loe-lung-cao-...,NaN,1.0,quannu,199900.0
814,"Quần ống sớ, quần nữ dáng suông ống rộng khóa ...",159000,https://tiki.vn/quan-ong-so-quan-nu-dang-suong...,NaN,89.0,quannu,14151000.0
815,Quần ống rộng gân tăm đai nơ chất cotton co giãn,79000,https://tiki.vn/quan-ong-rong-gan-tam-dai-no-c...,NaN,66.0,quannu,5214000.0

In [15]:
df_all.to_csv("tk_quannu_all_ed.csv")