In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_180124(12htrua) - Copy (4)\thoitrangnu\quannu"
os.listdir(path)

['.ipynb_checkpoints',
 'tk_quannu.csv',
 'tk_quannu_all.ipynb',
 'tk_ttn_qn.ipynb',
 'tk_ttn_qn_npage.ipynb',
 'tk_ttn_qn_t10.csv',
 'tk_ttn_qn_t11.csv',
 'tk_ttn_qn_t12.csv',
 'tk_ttn_qn_t13.csv',
 'tk_ttn_qn_t14.csv',
 'tk_ttn_qn_t15.csv',
 'tk_ttn_qn_t16.csv',
 'tk_ttn_qn_t17.csv',
 'tk_ttn_qn_t18.csv',
 'tk_ttn_qn_t19.csv',
 'tk_ttn_qn_t2.csv',
 'tk_ttn_qn_t20.csv',
 'tk_ttn_qn_t21.csv',
 'tk_ttn_qn_t22.csv',
 'tk_ttn_qn_t23.csv',
 'tk_ttn_qn_t24.csv',
 'tk_ttn_qn_t25.csv',
 'tk_ttn_qn_t26.csv',
 'tk_ttn_qn_t27.csv',
 'tk_ttn_qn_t28.csv',
 'tk_ttn_qn_t29.csv',
 'tk_ttn_qn_t3.csv',
 'tk_ttn_qn_t30.csv',
 'tk_ttn_qn_t31.csv',
 'tk_ttn_qn_t32.csv',
 'tk_ttn_qn_t33.csv',
 'tk_ttn_qn_t34.csv',
 'tk_ttn_qn_t35.csv',
 'tk_ttn_qn_t36.csv',
 'tk_ttn_qn_t37.csv',
 'tk_ttn_qn_t38.csv',
 'tk_ttn_qn_t39.csv',
 'tk_ttn_qn_t4.csv',
 'tk_ttn_qn_t40.csv',
 'tk_ttn_qn_t41.csv',
 'tk_ttn_qn_t42.csv',
 'tk_ttn_qn_t43.csv',
 'tk_ttn_qn_t44.csv',
 'tk_ttn_qn_t45.csv',
 'tk_ttn_qn_t46.csv',
 'tk_ttn_qn_t47.csv',
 'tk_ttn_qn_t48.csv',
 'tk_ttn_qn_t49.csv',
 'tk_ttn_qn_t5.csv',
 'tk_ttn_qn_t50.csv',
 'tk_ttn_qn_t6.csv',
 'tk_ttn_qn_t7.csv',
 'tk_ttn_qn_t8.csv',
 'tk_ttn_qn_t9.csv']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_quannu_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales,category
0,"Quần short kaki nữ GOKING, lưng thun và dây rú...",185.000₫,https://tka.tiki.vn/pixel/pixel?data=h_PLOBlOu...,1,-42%,Đã bán 268,quannu
1,Quần Lengging Lửng Nữ Chất Thun Co Dãn 4 Chiều...,45.000₫,https://tka.tiki.vn/pixel/pixel?data=cScKafo2b...,2,-44%,Đã bán 263,quannu
2,QUẦN ỐNG RỘNG NỮ BIGSIZE CẠP CAO TÔN DÁNG KÉO ...,175.000₫,https://tka.tiki.vn/pixel/pixel?data=cV7034IWS...,3,-12%,Đã bán 124,quannu
3,Quần short nữ ống rộng lưng cao có túi độc đáo...,139.000₫,https://tka.tiki.vn/pixel/pixel?data=l3w5wNuXT...,4,-50%,Đã bán 18,quannu
4,Quần Legging nâng mông gen bụng chất su đúc fu...,158.000₫,https://tka.tiki.vn/pixel/pixel?data=5ca21Nmob...,5,-21%,Đã bán 4,quannu
...,...,...,...,...,...,...,...
35,NaN,NaN,https://tiki.vn/quan-dui-nu-cap-chun-banamo-qu...,36,NaN,NaN,quannu
36,"Quần ống sớ, quần nữ dáng suông ống rộng khóa ...",140.000₫,https://tiki.vn/quan-ong-so-quan-nu-dang-suong...,37,NaN,Đã bán 89,quannu
37,Quần ống rộng gân tăm đai nơ chất cotton co giãn,79.000₫,https://tiki.vn/quan-ong-rong-gan-tam-dai-no-c...,38,NaN,Đã bán 66,quannu
38,Quần DirtyCoins Khaki Work Shorts,299.000₫,https://tiki.vn/quan-dirtycoins-khaki-work-sho...,39,NaN,NaN,quannu
39,Quần JOGGER Nữ Thể Thao Chất Vải Thun Lạnh Mềm...,198.000,https://tiki.vn/quan-jogger-nu-the-thao-chat-v...,40,NaN,NaN,quannu

1. Xử lý dữ liệu

In [5]:
df_all = df_all.drop('index', axis=1)

In [6]:
df_all.dropna(subset=['sales'], inplace=True)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales,category
0,"Quần short kaki nữ GOKING, lưng thun và dây rú...",185.000₫,https://tka.tiki.vn/pixel/pixel?data=h_PLOBlOu...,-42%,Đã bán 268,quannu
1,Quần Lengging Lửng Nữ Chất Thun Co Dãn 4 Chiều...,45.000₫,https://tka.tiki.vn/pixel/pixel?data=cScKafo2b...,-44%,Đã bán 263,quannu
2,QUẦN ỐNG RỘNG NỮ BIGSIZE CẠP CAO TÔN DÁNG KÉO ...,175.000₫,https://tka.tiki.vn/pixel/pixel?data=cV7034IWS...,-12%,Đã bán 124,quannu
3,Quần short nữ ống rộng lưng cao có túi độc đáo...,139.000₫,https://tka.tiki.vn/pixel/pixel?data=l3w5wNuXT...,-50%,Đã bán 18,quannu
4,Quần Legging nâng mông gen bụng chất su đúc fu...,158.000₫,https://tka.tiki.vn/pixel/pixel?data=5ca21Nmob...,-21%,Đã bán 4,quannu
...,...,...,...,...,...,...
836,"Quần Jean nữ Suông mẫu basic QJ280, Thanh lịch...",199.000₫,https://tiki.vn/quan-jean-nu-suong-mau-basic-q...,NaN,Đã bán 1,quannu
837,Quần nữ thời trang kiểu Hàn Quốc Thu Hà chất l...,149.000₫,https://tiki.vn/quan-nu-thoi-trang-kieu-han-qu...,NaN,Đã bán 3,quannu
838,Quần Jean Nữ ỐNg Loe Lưng CAo Co Giãn Tôn Dáng...,199.900₫,https://tiki.vn/quan-jean-nu-ong-loe-lung-cao-...,NaN,Đã bán 1,quannu
839,"Quần ống sớ, quần nữ dáng suông ống rộng khóa ...",140.000₫,https://tiki.vn/quan-ong-so-quan-nu-dang-suong...,NaN,Đã bán 89,quannu
840,Quần ống rộng gân tăm đai nơ chất cotton co giãn,79.000₫,https://tiki.vn/quan-ong-rong-gan-tam-dai-no-c...,NaN,Đã bán 66,quannu

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0      185000
1       45000
2      175000
3      139000
4      158000
        ...
836    199000
837    149000
838    199900
839    140000
840     79000
Name: price, Length: 841, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0      268.0
1      263.0
2      124.0
3       18.0
4        4.0
       ...
836      1.0
837      3.0
838      1.0
839     89.0
840     66.0
Name: sales, Length: 841, dtype: float64

In [11]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0      49580000.0
1      11835000.0
2      21700000.0
3       2502000.0
4        632000.0
          ...
836      199000.0
837      447000.0
838      199900.0
839    12460000.0
840     5214000.0
Name: revenue, Length: 841, dtype: float64

In [12]:
total = df_all["revenue"].sum()

In [13]:
print("Tổng doanh số quannu: ", total)
print("So mat hang da ban: ", len(df_all["title"])) # san pham da ban
print("So san pham da ban: ", df_all["sales"].sum()) # san pham co luot ban

Tổng doanh số quannu:  3497297670.0
So mat hang da ban:  841
So san pham da ban:  26470.0

In [14]:
df_all

,title,price,link_item,discount,sales,category,revenue
0,"Quần short kaki nữ GOKING, lưng thun và dây rú...",185000,https://tka.tiki.vn/pixel/pixel?data=h_PLOBlOu...,-42%,268.0,quannu,49580000.0
1,Quần Lengging Lửng Nữ Chất Thun Co Dãn 4 Chiều...,45000,https://tka.tiki.vn/pixel/pixel?data=cScKafo2b...,-44%,263.0,quannu,11835000.0
2,QUẦN ỐNG RỘNG NỮ BIGSIZE CẠP CAO TÔN DÁNG KÉO ...,175000,https://tka.tiki.vn/pixel/pixel?data=cV7034IWS...,-12%,124.0,quannu,21700000.0
3,Quần short nữ ống rộng lưng cao có túi độc đáo...,139000,https://tka.tiki.vn/pixel/pixel?data=l3w5wNuXT...,-50%,18.0,quannu,2502000.0
4,Quần Legging nâng mông gen bụng chất su đúc fu...,158000,https://tka.tiki.vn/pixel/pixel?data=5ca21Nmob...,-21%,4.0,quannu,632000.0
...,...,...,...,...,...,...,...
836,"Quần Jean nữ Suông mẫu basic QJ280, Thanh lịch...",199000,https://tiki.vn/quan-jean-nu-suong-mau-basic-q...,NaN,1.0,quannu,199000.0
837,Quần nữ thời trang kiểu Hàn Quốc Thu Hà chất l...,149000,https://tiki.vn/quan-nu-thoi-trang-kieu-han-qu...,NaN,3.0,quannu,447000.0
838,Quần Jean Nữ ỐNg Loe Lưng CAo Co Giãn Tôn Dáng...,199900,https://tiki.vn/quan-jean-nu-ong-loe-lung-cao-...,NaN,1.0,quannu,199900.0
839,"Quần ống sớ, quần nữ dáng suông ống rộng khóa ...",140000,https://tiki.vn/quan-ong-so-quan-nu-dang-suong...,NaN,89.0,quannu,12460000.0
840,Quần ống rộng gân tăm đai nơ chất cotton co giãn,79000,https://tiki.vn/quan-ong-rong-gan-tam-dai-no-c...,NaN,66.0,quannu,5214000.0

In [15]:
df_all.to_csv("tk_quannu_all_ed.csv")