In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_170124(12htrua) - Copy (2)\thoitrangnam\dolot"
os.listdir(path)

['tk_dolotnam.ipynb',
 'tk_dolot_all.ipynb',
 'tk_ttn_dolotnam_npage.ipynb',
 'tk_ttn_dolotnam_t10.csv',
 'tk_ttn_dolotnam_t11.csv',
 'tk_ttn_dolotnam_t12.csv',
 'tk_ttn_dolotnam_t13.csv',
 'tk_ttn_dolotnam_t14.csv',
 'tk_ttn_dolotnam_t15.csv',
 'tk_ttn_dolotnam_t16.csv',
 'tk_ttn_dolotnam_t17.csv',
 'tk_ttn_dolotnam_t18.csv',
 'tk_ttn_dolotnam_t19.csv',
 'tk_ttn_dolotnam_t2.csv',
 'tk_ttn_dolotnam_t20.csv',
 'tk_ttn_dolotnam_t21.csv',
 'tk_ttn_dolotnam_t22.csv',
 'tk_ttn_dolotnam_t23.csv',
 'tk_ttn_dolotnam_t24.csv',
 'tk_ttn_dolotnam_t25.csv',
 'tk_ttn_dolotnam_t26.csv',
 'tk_ttn_dolotnam_t27.csv',
 'tk_ttn_dolotnam_t28.csv',
 'tk_ttn_dolotnam_t29.csv',
 'tk_ttn_dolotnam_t3.csv',
 'tk_ttn_dolotnam_t30.csv',
 'tk_ttn_dolotnam_t31.csv',
 'tk_ttn_dolotnam_t32.csv',
 'tk_ttn_dolotnam_t33.csv',
 'tk_ttn_dolotnam_t34.csv',
 'tk_ttn_dolotnam_t35.csv',
 'tk_ttn_dolotnam_t36.csv',
 'tk_ttn_dolotnam_t37.csv',
 'tk_ttn_dolotnam_t38.csv',
 'tk_ttn_dolotnam_t39.csv',
 'tk_ttn_dolotnam_t4.csv',
 'tk_ttn_dolotnam_t40.csv',
 'tk_ttn_dolotnam_t41.csv',
 'tk_ttn_dolotnam_t42.csv',
 'tk_ttn_dolotnam_t43.csv',
 'tk_ttn_dolotnam_t44.csv',
 'tk_ttn_dolotnam_t45.csv',
 'tk_ttn_dolotnam_t46.csv',
 'tk_ttn_dolotnam_t47.csv',
 'tk_ttn_dolotnam_t48.csv',
 'tk_ttn_dolotnam_t49.csv',
 'tk_ttn_dolotnam_t5.csv',
 'tk_ttn_dolotnam_t50.csv',
 'tk_ttn_dolotnam_t6.csv',
 'tk_ttn_dolotnam_t7.csv',
 'tk_ttn_dolotnam_t8.csv',
 'tk_ttn_dolotnam_t9.csv']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_dolot_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales,category
0,Quần lót nam ren lưới thoáng mát - QL06A,95.000₫,https://tiki.vn/quan-lot-nam-ren-luoi-thoang-m...,1,-30%,Đã bán 15,dolotnam
1,Combo 4 Quần Lót Nam Quần Sịp Nam Sợi Cotton C...,239.000₫,https://tiki.vn/combo-4-quan-sip-nam-quan-lot-...,2,-53%,Đã bán 20,dolotnam
2,Quần lót nam 274,29.000₫,https://tiki.vn/quan-lot-nam-274-p101949478.ht...,3,-44%,Đã bán 2,dolotnam
3,Quần lót mềm mại thoáng khí đáy chữ U lưng thấ...,49.000₫,https://tiki.vn/quan-lot-mem-mai-thoang-khi-da...,4,NaN,NaN,dolotnam
4,NaN,NaN,https://tiki.vn/quan-lot-boxer-nam-luoi-thun-t...,5,-20%,NaN,dolotnam
...,...,...,...,...,...,...,...
35,NaN,NaN,https://tiki.vn/quan-lot-nam-dang-luoi-co-gian...,36,NaN,NaN,dolotnam
36,Quần lót Nam Cotton thời trang - L ( 59 - 65kg),99.000₫,https://tiki.vn/quan-lot-nam-cotton-thoi-trang...,37,NaN,NaN,dolotnam
37,Quần lót nam sexy dây coặc 2 bên mạnh mẽ - 1 cái,45.000₫,https://tiki.vn/quan-lot-nam-sexy-day-coac-2-b...,38,NaN,Đã bán 10,dolotnam
38,Quần lót lọt khe dây gợi cảm,23.000₫,https://tiki.vn/quan-lot-lot-khe-day-goi-cam-p...,39,NaN,NaN,dolotnam
39,Quần lót nam lọt khe hình bướm chữ G,45.000₫,https://tiki.vn/quan-lot-nam-lot-khe-hinh-buom...,40,NaN,NaN,dolotnam

1. Xử lý dữ liệu

In [5]:
df_all = df_all.drop('index', axis=1)

In [6]:
df_all.dropna(subset=['sales'], inplace=True)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales,category
0,Quần lót nam ren lưới thoáng mát - QL06A,95.000₫,https://tiki.vn/quan-lot-nam-ren-luoi-thoang-m...,-30%,Đã bán 15,dolotnam
1,Combo 4 Quần Lót Nam Quần Sịp Nam Sợi Cotton C...,239.000₫,https://tiki.vn/combo-4-quan-sip-nam-quan-lot-...,-53%,Đã bán 20,dolotnam
2,Quần lót nam 274,29.000₫,https://tiki.vn/quan-lot-nam-274-p101949478.ht...,-44%,Đã bán 2,dolotnam
3,Combo 5 Quần Sịp Đùi Nam Thông Hơi Nhật Bản - ...,78.000₫,https://tiki.vn/combo-5-quan-sip-dui-nam-thong...,NaN,Đã bán 39,dolotnam
4,Áo ba lỗ mặc nhà thể thao nam Chất Thun Co Giã...,32.000₫,https://tiki.vn/ao-ba-lo-mac-nha-the-thao-nam-...,NaN,Đã bán 4,dolotnam
...,...,...,...,...,...,...
663,Quần lót nam lưng thấp dạng dây thiết kế siêu ...,45.000₫,https://tiki.vn/quan-lot-nam-lung-thap-dang-da...,NaN,Đã bán 24,dolotnam
664,"Quần Lót Nam, Quần Ngủ Nam",99.000₫,https://tiki.vn/quan-lot-nam-quan-ngu-nam-p162...,NaN,Đã bán 61,dolotnam
665,Quần lót nam Body thun lạnh,50.000₫,https://tiki.vn/quan-lot-nam-body-thun-lanh-p1...,NaN,Đã bán 11,dolotnam
666,LÓT NAM-MS:6043(Freeman)cotton lụa 4 chiều,47.610₫,https://tiki.vn/lot-nam-ms-6043-freeman-cotton...,NaN,Đã bán 4,dolotnam
667,Quần lót nam sexy dây coặc 2 bên mạnh mẽ - 1 cái,45.000₫,https://tiki.vn/quan-lot-nam-sexy-day-coac-2-b...,NaN,Đã bán 10,dolotnam

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0       95000
1      239000
2       29000
3       78000
4       32000
        ...
663     45000
664     99000
665     50000
666     47610
667     45000
Name: price, Length: 668, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0      15.0
1      20.0
2       2.0
3      39.0
4       4.0
       ...
663    24.0
664    61.0
665    11.0
666     4.0
667    10.0
Name: sales, Length: 668, dtype: float64

In [11]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0      1425000.0
1      4780000.0
2        58000.0
3      3042000.0
4       128000.0
         ...
663    1080000.0
664    6039000.0
665     550000.0
666     190440.0
667     450000.0
Name: revenue, Length: 668, dtype: float64

In [12]:
total = df_all["revenue"].sum()

In [13]:
print("Tổng doanh số dolot: ", total)
print("So mat hang da ban: ", len(df_all["title"])) # san pham da ban
print("So san pham da ban: ", df_all["sales"].sum()) # san pham co luot ban

Tổng doanh số dolot:  7361184481.0
So mat hang da ban:  668
So san pham da ban:  60296.0

In [14]:
df_all

,title,price,link_item,discount,sales,category,revenue
0,Quần lót nam ren lưới thoáng mát - QL06A,95000,https://tiki.vn/quan-lot-nam-ren-luoi-thoang-m...,-30%,15.0,dolotnam,1425000.0
1,Combo 4 Quần Lót Nam Quần Sịp Nam Sợi Cotton C...,239000,https://tiki.vn/combo-4-quan-sip-nam-quan-lot-...,-53%,20.0,dolotnam,4780000.0
2,Quần lót nam 274,29000,https://tiki.vn/quan-lot-nam-274-p101949478.ht...,-44%,2.0,dolotnam,58000.0
3,Combo 5 Quần Sịp Đùi Nam Thông Hơi Nhật Bản - ...,78000,https://tiki.vn/combo-5-quan-sip-dui-nam-thong...,NaN,39.0,dolotnam,3042000.0
4,Áo ba lỗ mặc nhà thể thao nam Chất Thun Co Giã...,32000,https://tiki.vn/ao-ba-lo-mac-nha-the-thao-nam-...,NaN,4.0,dolotnam,128000.0
...,...,...,...,...,...,...,...
663,Quần lót nam lưng thấp dạng dây thiết kế siêu ...,45000,https://tiki.vn/quan-lot-nam-lung-thap-dang-da...,NaN,24.0,dolotnam,1080000.0
664,"Quần Lót Nam, Quần Ngủ Nam",99000,https://tiki.vn/quan-lot-nam-quan-ngu-nam-p162...,NaN,61.0,dolotnam,6039000.0
665,Quần lót nam Body thun lạnh,50000,https://tiki.vn/quan-lot-nam-body-thun-lanh-p1...,NaN,11.0,dolotnam,550000.0
666,LÓT NAM-MS:6043(Freeman)cotton lụa 4 chiều,47610,https://tiki.vn/lot-nam-ms-6043-freeman-cotton...,NaN,4.0,dolotnam,190440.0
667,Quần lót nam sexy dây coặc 2 bên mạnh mẽ - 1 cái,45000,https://tiki.vn/quan-lot-nam-sexy-day-coac-2-b...,NaN,10.0,dolotnam,450000.0

In [15]:
df_all.to_csv("tk_dolot_all_ed.csv")