In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_170124(12hdem) - Copy\dienthoai_maytinhbang\maydocsach"
os.listdir(path)

['.ipynb_checkpoints',
 'tk_dienthoai_maytinhbang_maydocsach.ipynb',
 'tk_dienthoai_maytinhbang_maydocsach_t2.ipynb',
 'tk_maydocsach_all.ipynb',
 'tk_maydocsach_t1.csv',
 'tk_maydocsach_t2.csv']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_maydocsach_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales,category
0,Máy đọc sách New Kindle 11th 2022 (16GB) - Hàn...,2.680.000₫,https://tka.tiki.vn/pixel/pixel?data=1Hp8fS6vu...,1,-14%,Đã bán 3,maydocsach
1,Máy đọc sách Kindle 2022 (11th) - All new kind...,2.680.000₫,https://tka.tiki.vn/pixel/pixel?data=qM9urDJFL...,2,-4%,Đã bán 8,maydocsach
2,Máy đọc sách All New Kindle Oasis 3 - Hàng nhậ...,6.690.000₫,https://tka.tiki.vn/pixel/pixel?data=dsEBUVJYP...,3,-11%,Đã bán 52,maydocsach
3,Máy đọc sách Kindle Oasis 3 (2019) - Amazon - ...,5.790.000₫,https://tka.tiki.vn/pixel/pixel?data=I8H2sLxGi...,4,-21%,Đã bán 35,maydocsach
4,Máy Đọc Sách Kindle Oasis (10th Gen) 2019- 8GB...,5.831.008₫,https://tka.tiki.vn/pixel/pixel?data=QNAB6U2ll...,5,-4%,Đã bán 3,maydocsach
...,...,...,...,...,...,...,...
13,Combo Máy đọc sách All New Kindle Paperwhite 5...,3.830.000₫,https://tka.tiki.vn/pixel/pixel?data=VXkgDuiMO...,14,NaN,Đã bán 7,maydocsach
14,Máy đọc sách Kindle Oasis 3 (2019) - Amazon - ...,5.790.000₫,https://tka.tiki.vn/pixel/pixel?data=eiEnO_gPD...,15,NaN,Đã bán 35,maydocsach
15,Bút học tiếng Anh i-Tek Venus 2023 (HÀNG CHÍNH...,560.000₫,https://tiki.vn/but-hoc-tieng-anh-i-tek-chinh-...,16,NaN,Đã bán 1,maydocsach
16,Máy đọc sách All new Paperwhite Gen 5 (11th) m...,3.490.000₫,https://tiki.vn/may-doc-sach-all-new-paperwhit...,17,NaN,NaN,maydocsach
17,Máy đọc sách Kobo Nia - Hàng nhập khẩu,2.680.000₫,https://tiki.vn/may-doc-sach-kobo-nia-p1487018...,18,NaN,NaN,maydocsach

1. Xử lý dữ liệu

In [5]:
df_all = df_all.drop('index', axis=1)

In [6]:
df_all.dropna(subset=['sales'], inplace=True)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales,category
0,Máy đọc sách New Kindle 11th 2022 (16GB) - Hàn...,2.680.000₫,https://tka.tiki.vn/pixel/pixel?data=1Hp8fS6vu...,-14%,Đã bán 3,maydocsach
1,Máy đọc sách Kindle 2022 (11th) - All new kind...,2.680.000₫,https://tka.tiki.vn/pixel/pixel?data=qM9urDJFL...,-4%,Đã bán 8,maydocsach
2,Máy đọc sách All New Kindle Oasis 3 - Hàng nhậ...,6.690.000₫,https://tka.tiki.vn/pixel/pixel?data=dsEBUVJYP...,-11%,Đã bán 52,maydocsach
3,Máy đọc sách Kindle Oasis 3 (2019) - Amazon - ...,5.790.000₫,https://tka.tiki.vn/pixel/pixel?data=I8H2sLxGi...,-21%,Đã bán 35,maydocsach
4,Máy Đọc Sách Kindle Oasis (10th Gen) 2019- 8GB...,5.831.008₫,https://tka.tiki.vn/pixel/pixel?data=QNAB6U2ll...,-4%,Đã bán 3,maydocsach
...,...,...,...,...,...,...
60,Combo Máy đọc sách All New Kindle Paperwhite 5...,3.790.000₫,https://tka.tiki.vn/pixel/pixel?data=zpCVgwVO0...,NaN,Đã bán 3,maydocsach
61,Combo Máy đọc sách All New Kindle Paperwhite 5...,3.360.000₫,https://tka.tiki.vn/pixel/pixel?data=Tdd4VkMiq...,NaN,Đã bán 454,maydocsach
62,Combo Máy đọc sách All New Kindle Paperwhite 5...,3.830.000₫,https://tka.tiki.vn/pixel/pixel?data=VXkgDuiMO...,NaN,Đã bán 7,maydocsach
63,Máy đọc sách Kindle Oasis 3 (2019) - Amazon - ...,5.790.000₫,https://tka.tiki.vn/pixel/pixel?data=eiEnO_gPD...,NaN,Đã bán 35,maydocsach
64,Bút học tiếng Anh i-Tek Venus 2023 (HÀNG CHÍNH...,560.000₫,https://tiki.vn/but-hoc-tieng-anh-i-tek-chinh-...,NaN,Đã bán 1,maydocsach

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0     2680000
1     2680000
2     6690000
3     5790000
4     5831008
       ...
60    3790000
61    3360000
62    3830000
63    5790000
64     560000
Name: price, Length: 65, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0       3.0
1       8.0
2      52.0
3      35.0
4       3.0
      ...
60      3.0
61    454.0
62      7.0
63     35.0
64      1.0
Name: sales, Length: 65, dtype: float64

In [11]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0     8.040000e+06
1     2.144000e+07
2     3.478800e+08
3     2.026500e+08
4     1.749302e+07
          ...
60    1.137000e+07
61    1.525440e+09
62    2.681000e+07
63    2.026500e+08
64    5.600000e+05
Name: revenue, Length: 65, dtype: float64

In [12]:
total = df_all["revenue"].sum()

In [13]:
print("Tổng doanh số maydocsach: ", total)
print("So mat hang da ban: ", len(df_all["title"])) # san pham da ban
print("So san pham da ban: ", df_all["sales"].sum()) # san pham co luot ban

Tổng doanh số maydocsach:  29173131924.0
So mat hang da ban:  65
So san pham da ban:  8138.0

In [14]:
df_all

,title,price,link_item,discount,sales,category,revenue
0,Máy đọc sách New Kindle 11th 2022 (16GB) - Hàn...,2680000,https://tka.tiki.vn/pixel/pixel?data=1Hp8fS6vu...,-14%,3.0,maydocsach,8.040000e+06
1,Máy đọc sách Kindle 2022 (11th) - All new kind...,2680000,https://tka.tiki.vn/pixel/pixel?data=qM9urDJFL...,-4%,8.0,maydocsach,2.144000e+07
2,Máy đọc sách All New Kindle Oasis 3 - Hàng nhậ...,6690000,https://tka.tiki.vn/pixel/pixel?data=dsEBUVJYP...,-11%,52.0,maydocsach,3.478800e+08
3,Máy đọc sách Kindle Oasis 3 (2019) - Amazon - ...,5790000,https://tka.tiki.vn/pixel/pixel?data=I8H2sLxGi...,-21%,35.0,maydocsach,2.026500e+08
4,Máy Đọc Sách Kindle Oasis (10th Gen) 2019- 8GB...,5831008,https://tka.tiki.vn/pixel/pixel?data=QNAB6U2ll...,-4%,3.0,maydocsach,1.749302e+07
...,...,...,...,...,...,...,...
60,Combo Máy đọc sách All New Kindle Paperwhite 5...,3790000,https://tka.tiki.vn/pixel/pixel?data=zpCVgwVO0...,NaN,3.0,maydocsach,1.137000e+07
61,Combo Máy đọc sách All New Kindle Paperwhite 5...,3360000,https://tka.tiki.vn/pixel/pixel?data=Tdd4VkMiq...,NaN,454.0,maydocsach,1.525440e+09
62,Combo Máy đọc sách All New Kindle Paperwhite 5...,3830000,https://tka.tiki.vn/pixel/pixel?data=VXkgDuiMO...,NaN,7.0,maydocsach,2.681000e+07
63,Máy đọc sách Kindle Oasis 3 (2019) - Amazon - ...,5790000,https://tka.tiki.vn/pixel/pixel?data=eiEnO_gPD...,NaN,35.0,maydocsach,2.026500e+08
64,Bút học tiếng Anh i-Tek Venus 2023 (HÀNG CHÍNH...,560000,https://tiki.vn/but-hoc-tieng-anh-i-tek-chinh-...,NaN,1.0,maydocsach,5.600000e+05

In [15]:
df_all.to_csv("tk_maydocsach_all_ed.csv")