In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_190124(12hdem) - Copy (5)\thoitrangnu\quannu"
os.listdir(path)

['.ipynb_checkpoints',
 'tk_quannu_all.ipynb',
 'tk_ttn_qn.ipynb',
 'tk_ttn_qn_npage.ipynb',
 'tk_ttn_qn_t1.csv',
 'tk_ttn_qn_t10.csv',
 'tk_ttn_qn_t11.csv',
 'tk_ttn_qn_t12.csv',
 'tk_ttn_qn_t13.csv',
 'tk_ttn_qn_t14.csv',
 'tk_ttn_qn_t15.csv',
 'tk_ttn_qn_t16.csv',
 'tk_ttn_qn_t17.csv',
 'tk_ttn_qn_t18.csv',
 'tk_ttn_qn_t19.csv',
 'tk_ttn_qn_t2.csv',
 'tk_ttn_qn_t20.csv',
 'tk_ttn_qn_t21.csv',
 'tk_ttn_qn_t22.csv',
 'tk_ttn_qn_t23.csv',
 'tk_ttn_qn_t24.csv',
 'tk_ttn_qn_t25.csv',
 'tk_ttn_qn_t26.csv',
 'tk_ttn_qn_t27.csv',
 'tk_ttn_qn_t28.csv',
 'tk_ttn_qn_t29.csv',
 'tk_ttn_qn_t3.csv',
 'tk_ttn_qn_t30.csv',
 'tk_ttn_qn_t31.csv',
 'tk_ttn_qn_t32.csv',
 'tk_ttn_qn_t33.csv',
 'tk_ttn_qn_t34.csv',
 'tk_ttn_qn_t35.csv',
 'tk_ttn_qn_t36.csv',
 'tk_ttn_qn_t37.csv',
 'tk_ttn_qn_t38.csv',
 'tk_ttn_qn_t39.csv',
 'tk_ttn_qn_t4.csv',
 'tk_ttn_qn_t40.csv',
 'tk_ttn_qn_t41.csv',
 'tk_ttn_qn_t42.csv',
 'tk_ttn_qn_t43.csv',
 'tk_ttn_qn_t44.csv',
 'tk_ttn_qn_t45.csv',
 'tk_ttn_qn_t46.csv',
 'tk_ttn_qn_t47.csv',
 'tk_ttn_qn_t48.csv',
 'tk_ttn_qn_t49.csv',
 'tk_ttn_qn_t5.csv',
 'tk_ttn_qn_t50.csv',
 'tk_ttn_qn_t6.csv',
 'tk_ttn_qn_t7.csv',
 'tk_ttn_qn_t8.csv',
 'tk_ttn_qn_t9.csv']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_quannu_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales,category
0,"Quần short kaki nữ GOKING, lưng thun và dây rú...",185.000₫,https://tka.tiki.vn/pixel/pixel?data=BSTblGowc...,1,-8%,Đã bán 268,quannu
1,Quần Lengging Lửng Nữ Chất Thun Co Dãn 4 Chiều...,45.000₫,https://tka.tiki.vn/pixel/pixel?data=9ChykHJQZ...,2,NaN,Đã bán 265,quannu
2,Quần Legging nâng mông gen bụng chất su đúc fu...,165.000₫,https://tka.tiki.vn/pixel/pixel?data=ANYca8mo1...,3,NaN,Đã bán 4,quannu
3,Quần Legging Nữ Dài Cạp Cao Đẹp Cao Cấp PINKAH...,215.000,https://tka.tiki.vn/pixel/pixel?data=v22owqIyr...,4,-50%,NaN,quannu
4,NaN,NaN,https://tka.tiki.vn/pixel/pixel?data=CfgS1S-q2...,5,-21%,NaN,quannu
...,...,...,...,...,...,...,...
35,NaN,NaN,https://tiki.vn/quan-ong-so-quan-nu-dang-suong...,36,NaN,NaN,quannu
36,Quần ống rộng gân tăm đai nơ chất cotton co giãn,79.000₫,https://tiki.vn/quan-ong-rong-gan-tam-dai-no-c...,37,NaN,Đã bán 66,quannu
37,Quần DirtyCoins Khaki Work Shorts,399.000₫,https://tiki.vn/quan-dirtycoins-khaki-work-sho...,38,NaN,Đã bán 1,quannu
38,Quần JOGGER Nữ Thể Thao Chất Vải Thun Lạnh Mềm...,198.000₫,https://tiki.vn/quan-jogger-nu-the-thao-chat-v...,39,NaN,Đã bán 4,quannu
39,Quần ống rộng lửng vải đũi cạp khoá may chuẩn,58.000₫,https://tiki.vn/quan-ong-rong-lung-vai-dui-cap...,40,NaN,NaN,quannu

1. Xử lý dữ liệu

In [5]:
df_all = df_all.drop('index', axis=1)

In [6]:
df_all.dropna(subset=['sales'], inplace=True)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales,category
0,"Quần short kaki nữ GOKING, lưng thun và dây rú...",185.000₫,https://tka.tiki.vn/pixel/pixel?data=BSTblGowc...,-8%,Đã bán 268,quannu
1,Quần Lengging Lửng Nữ Chất Thun Co Dãn 4 Chiều...,45.000₫,https://tka.tiki.vn/pixel/pixel?data=9ChykHJQZ...,NaN,Đã bán 265,quannu
2,Quần Legging nâng mông gen bụng chất su đúc fu...,165.000₫,https://tka.tiki.vn/pixel/pixel?data=ANYca8mo1...,NaN,Đã bán 4,quannu
3,"Quần Đùi Nữ Mặc Nhà Chất vải Lụa Hàn Quốc ,Mịn...",39.500₫,https://tiki.vn/quan-dui-nu-mac-nha-quan-dui-n...,NaN,Đã bán 239,quannu
4,"Quần ống rộng nữ, quần ống suông đũi Gu chun l...",69.000₫,https://tiki.vn/quan-ong-rong-nu-quan-ong-suon...,-9%,Đã bán 148,quannu
...,...,...,...,...,...,...
824,Quần Jean Nữ ỐNg Loe Lưng CAo Co Giãn Tôn Dáng...,199.900₫,https://tiki.vn/quan-jean-nu-ong-loe-lung-cao-...,NaN,Đã bán 1,quannu
825,Quần ống rộng cạp chun Qt05,87.000₫,https://tiki.vn/quan-ong-rong-cap-chun-2-tui-q...,NaN,Đã bán 47,quannu
826,Quần ống rộng gân tăm đai nơ chất cotton co giãn,79.000₫,https://tiki.vn/quan-ong-rong-gan-tam-dai-no-c...,NaN,Đã bán 66,quannu
827,Quần DirtyCoins Khaki Work Shorts,399.000₫,https://tiki.vn/quan-dirtycoins-khaki-work-sho...,NaN,Đã bán 1,quannu
828,Quần JOGGER Nữ Thể Thao Chất Vải Thun Lạnh Mềm...,198.000₫,https://tiki.vn/quan-jogger-nu-the-thao-chat-v...,NaN,Đã bán 4,quannu

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0      185000
1       45000
2      165000
3       39500
4       69000
        ...
824    199900
825     87000
826     79000
827    399000
828    198000
Name: price, Length: 829, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0      268.0
1      265.0
2        4.0
3      239.0
4      148.0
       ...
824      1.0
825     47.0
826     66.0
827      1.0
828      4.0
Name: sales, Length: 829, dtype: float64

In [11]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0      49580000.0
1      11925000.0
2        660000.0
3       9440500.0
4      10212000.0
          ...
824      199900.0
825     4089000.0
826     5214000.0
827      399000.0
828      792000.0
Name: revenue, Length: 829, dtype: float64

In [12]:
total = df_all["revenue"].sum()

In [13]:
print("Tổng doanh số quannu: ", total)
print("So mat hang da ban: ", len(df_all["title"])) # san pham da ban
print("So san pham da ban: ", df_all["sales"].sum()) # san pham co luot ban

Tổng doanh số quannu:  2922722620.0
So mat hang da ban:  829
So san pham da ban:  24296.0

In [14]:
df_all

,title,price,link_item,discount,sales,category,revenue
0,"Quần short kaki nữ GOKING, lưng thun và dây rú...",185000,https://tka.tiki.vn/pixel/pixel?data=BSTblGowc...,-8%,268.0,quannu,49580000.0
1,Quần Lengging Lửng Nữ Chất Thun Co Dãn 4 Chiều...,45000,https://tka.tiki.vn/pixel/pixel?data=9ChykHJQZ...,NaN,265.0,quannu,11925000.0
2,Quần Legging nâng mông gen bụng chất su đúc fu...,165000,https://tka.tiki.vn/pixel/pixel?data=ANYca8mo1...,NaN,4.0,quannu,660000.0
3,"Quần Đùi Nữ Mặc Nhà Chất vải Lụa Hàn Quốc ,Mịn...",39500,https://tiki.vn/quan-dui-nu-mac-nha-quan-dui-n...,NaN,239.0,quannu,9440500.0
4,"Quần ống rộng nữ, quần ống suông đũi Gu chun l...",69000,https://tiki.vn/quan-ong-rong-nu-quan-ong-suon...,-9%,148.0,quannu,10212000.0
...,...,...,...,...,...,...,...
824,Quần Jean Nữ ỐNg Loe Lưng CAo Co Giãn Tôn Dáng...,199900,https://tiki.vn/quan-jean-nu-ong-loe-lung-cao-...,NaN,1.0,quannu,199900.0
825,Quần ống rộng cạp chun Qt05,87000,https://tiki.vn/quan-ong-rong-cap-chun-2-tui-q...,NaN,47.0,quannu,4089000.0
826,Quần ống rộng gân tăm đai nơ chất cotton co giãn,79000,https://tiki.vn/quan-ong-rong-gan-tam-dai-no-c...,NaN,66.0,quannu,5214000.0
827,Quần DirtyCoins Khaki Work Shorts,399000,https://tiki.vn/quan-dirtycoins-khaki-work-sho...,NaN,1.0,quannu,399000.0
828,Quần JOGGER Nữ Thể Thao Chất Vải Thun Lạnh Mềm...,198000,https://tiki.vn/quan-jogger-nu-the-thao-chat-v...,NaN,4.0,quannu,792000.0

In [15]:
df_all.to_csv("tk_quannu_all_ed.csv")