In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_180124(12htrua) - Copy (4)\dienthoai_maytinhbang\maydocsach"
os.listdir(path)

['.ipynb_checkpoints',
 'tk_dienthoai_maytinhbang_maydocsach.ipynb',
 'tk_dienthoai_maytinhbang_maydocsach_t2.ipynb',
 'tk_maydocsach_all.ipynb',
 'tk_maydocsach_t1.csv',
 'tk_maydocsach_t2.csv']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_maydocsach_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales,category
0,Máy đọc sách New Kindle 11th 2022 (16GB) - Hàn...,2.680.000₫,https://tka.tiki.vn/pixel/pixel?data=UlYJoOOpa...,1,-4%,Đã bán 3,maydocsach
1,Máy đọc sách All New Kindle Oasis 3 - Hàng nhậ...,6.896.000₫,https://tka.tiki.vn/pixel/pixel?data=xNEDbZm8j...,2,-11%,Đã bán 16,maydocsach
2,Máy đọc sách Kindle Scribe – thế hệ đầu tiên c...,11.390.000₫,https://tka.tiki.vn/pixel/pixel?data=6uqwK8lFZ...,3,-11%,Đã bán 3,maydocsach
3,Máy đọc sách Kindle Oasis 3 (2019) - Amazon - ...,5.790.000₫,https://tka.tiki.vn/pixel/pixel?data=y-0ddluuF...,4,-14%,Đã bán 35,maydocsach
4,Máy đọc sách Kindle 2022 (11th) - All new kind...,2.680.000₫,https://tka.tiki.vn/pixel/pixel?data=BU04cM7xi...,5,-3%,Đã bán 8,maydocsach
...,...,...,...,...,...,...,...
13,Máy đọc sách New Kindle 11th 2022 (16GB) - Hàn...,2.680.000₫,https://tka.tiki.vn/pixel/pixel?data=PXlBHvit3...,14,NaN,Đã bán 3,maydocsach
14,Combo Máy đọc sách All New Kindle Paperwhite 5...,3.830.000₫,https://tka.tiki.vn/pixel/pixel?data=37DY15CvQ...,15,NaN,Đã bán 7,maydocsach
15,Bút học tiếng Anh i-Tek Venus 2023 (HÀNG CHÍNH...,560.000₫,https://tiki.vn/but-hoc-tieng-anh-i-tek-chinh-...,16,NaN,Đã bán 1,maydocsach
16,Máy đọc sách All new Paperwhite Gen 5 (11th) m...,3.490.000₫,https://tiki.vn/may-doc-sach-all-new-paperwhit...,17,NaN,NaN,maydocsach
17,Máy đọc sách Kobo Nia - Hàng nhập khẩu,2.680.000₫,https://tiki.vn/may-doc-sach-kobo-nia-p1487018...,18,NaN,NaN,maydocsach

1. Xử lý dữ liệu

In [5]:
df_all = df_all.drop('index', axis=1)

In [6]:
df_all.dropna(subset=['sales'], inplace=True)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales,category
0,Máy đọc sách New Kindle 11th 2022 (16GB) - Hàn...,2.680.000₫,https://tka.tiki.vn/pixel/pixel?data=UlYJoOOpa...,-4%,Đã bán 3,maydocsach
1,Máy đọc sách All New Kindle Oasis 3 - Hàng nhậ...,6.896.000₫,https://tka.tiki.vn/pixel/pixel?data=xNEDbZm8j...,-11%,Đã bán 16,maydocsach
2,Máy đọc sách Kindle Scribe – thế hệ đầu tiên c...,11.390.000₫,https://tka.tiki.vn/pixel/pixel?data=6uqwK8lFZ...,-11%,Đã bán 3,maydocsach
3,Máy đọc sách Kindle Oasis 3 (2019) - Amazon - ...,5.790.000₫,https://tka.tiki.vn/pixel/pixel?data=y-0ddluuF...,-14%,Đã bán 35,maydocsach
4,Máy đọc sách Kindle 2022 (11th) - All new kind...,2.680.000₫,https://tka.tiki.vn/pixel/pixel?data=BU04cM7xi...,-3%,Đã bán 8,maydocsach
...,...,...,...,...,...,...
60,Combo Máy đọc sách All New Kindle Paperwhite 5...,3.380.000₫,https://tka.tiki.vn/pixel/pixel?data=AMclUjJmh...,NaN,Đã bán 4,maydocsach
61,Máy đọc sách Kindle Scribe - Hàng nhập khẩu,12.590.000₫,https://tka.tiki.vn/pixel/pixel?data=aAG5JkwW-...,NaN,Đã bán 5,maydocsach
62,Máy đọc sách New Kindle 11th 2022 (16GB) - Hàn...,2.680.000₫,https://tka.tiki.vn/pixel/pixel?data=PXlBHvit3...,NaN,Đã bán 3,maydocsach
63,Combo Máy đọc sách All New Kindle Paperwhite 5...,3.830.000₫,https://tka.tiki.vn/pixel/pixel?data=37DY15CvQ...,NaN,Đã bán 7,maydocsach
64,Bút học tiếng Anh i-Tek Venus 2023 (HÀNG CHÍNH...,560.000₫,https://tiki.vn/but-hoc-tieng-anh-i-tek-chinh-...,NaN,Đã bán 1,maydocsach

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0      2680000
1      6896000
2     11390000
3      5790000
4      2680000
        ...
60     3380000
61    12590000
62     2680000
63     3830000
64      560000
Name: price, Length: 65, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0      3.0
1     16.0
2      3.0
3     35.0
4      8.0
      ...
60     4.0
61     5.0
62     3.0
63     7.0
64     1.0
Name: sales, Length: 65, dtype: float64

In [11]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0       8040000.0
1     110336000.0
2      34170000.0
3     202650000.0
4      21440000.0
         ...
60     13520000.0
61     62950000.0
62      8040000.0
63     26810000.0
64       560000.0
Name: revenue, Length: 65, dtype: float64

In [12]:
total = df_all["revenue"].sum()

In [13]:
print("Tổng doanh số maydocsach: ", total)
print("So mat hang da ban: ", len(df_all["title"])) # san pham da ban
print("So san pham da ban: ", df_all["sales"].sum()) # san pham co luot ban

Tổng doanh số maydocsach:  27804882924.0
So mat hang da ban:  65
So san pham da ban:  7658.0

In [14]:
df_all

,title,price,link_item,discount,sales,category,revenue
0,Máy đọc sách New Kindle 11th 2022 (16GB) - Hàn...,2680000,https://tka.tiki.vn/pixel/pixel?data=UlYJoOOpa...,-4%,3.0,maydocsach,8040000.0
1,Máy đọc sách All New Kindle Oasis 3 - Hàng nhậ...,6896000,https://tka.tiki.vn/pixel/pixel?data=xNEDbZm8j...,-11%,16.0,maydocsach,110336000.0
2,Máy đọc sách Kindle Scribe – thế hệ đầu tiên c...,11390000,https://tka.tiki.vn/pixel/pixel?data=6uqwK8lFZ...,-11%,3.0,maydocsach,34170000.0
3,Máy đọc sách Kindle Oasis 3 (2019) - Amazon - ...,5790000,https://tka.tiki.vn/pixel/pixel?data=y-0ddluuF...,-14%,35.0,maydocsach,202650000.0
4,Máy đọc sách Kindle 2022 (11th) - All new kind...,2680000,https://tka.tiki.vn/pixel/pixel?data=BU04cM7xi...,-3%,8.0,maydocsach,21440000.0
...,...,...,...,...,...,...,...
60,Combo Máy đọc sách All New Kindle Paperwhite 5...,3380000,https://tka.tiki.vn/pixel/pixel?data=AMclUjJmh...,NaN,4.0,maydocsach,13520000.0
61,Máy đọc sách Kindle Scribe - Hàng nhập khẩu,12590000,https://tka.tiki.vn/pixel/pixel?data=aAG5JkwW-...,NaN,5.0,maydocsach,62950000.0
62,Máy đọc sách New Kindle 11th 2022 (16GB) - Hàn...,2680000,https://tka.tiki.vn/pixel/pixel?data=PXlBHvit3...,NaN,3.0,maydocsach,8040000.0
63,Combo Máy đọc sách All New Kindle Paperwhite 5...,3830000,https://tka.tiki.vn/pixel/pixel?data=37DY15CvQ...,NaN,7.0,maydocsach,26810000.0
64,Bút học tiếng Anh i-Tek Venus 2023 (HÀNG CHÍNH...,560000,https://tiki.vn/but-hoc-tieng-anh-i-tek-chinh-...,NaN,1.0,maydocsach,560000.0

In [15]:
df_all.to_csv("tk_maydocsach_all_ed.csv")