In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_170124(12hdem) - Copy\thoitrangnu\quannu"
os.listdir(path)

['.ipynb_checkpoints',
 'tk_quannu.csv',
 'tk_quannu_all.ipynb',
 'tk_ttn_qn.ipynb',
 'tk_ttn_qn_npage.ipynb',
 'tk_ttn_qn_t10.csv',
 'tk_ttn_qn_t11.csv',
 'tk_ttn_qn_t12.csv',
 'tk_ttn_qn_t13.csv',
 'tk_ttn_qn_t14.csv',
 'tk_ttn_qn_t15.csv',
 'tk_ttn_qn_t16.csv',
 'tk_ttn_qn_t17.csv',
 'tk_ttn_qn_t18.csv',
 'tk_ttn_qn_t19.csv',
 'tk_ttn_qn_t2.csv',
 'tk_ttn_qn_t20.csv',
 'tk_ttn_qn_t21.csv',
 'tk_ttn_qn_t22.csv',
 'tk_ttn_qn_t23.csv',
 'tk_ttn_qn_t24.csv',
 'tk_ttn_qn_t25.csv',
 'tk_ttn_qn_t26.csv',
 'tk_ttn_qn_t27.csv',
 'tk_ttn_qn_t28.csv',
 'tk_ttn_qn_t29.csv',
 'tk_ttn_qn_t3.csv',
 'tk_ttn_qn_t30.csv',
 'tk_ttn_qn_t31.csv',
 'tk_ttn_qn_t32.csv',
 'tk_ttn_qn_t33.csv',
 'tk_ttn_qn_t34.csv',
 'tk_ttn_qn_t35.csv',
 'tk_ttn_qn_t36.csv',
 'tk_ttn_qn_t37.csv',
 'tk_ttn_qn_t38.csv',
 'tk_ttn_qn_t39.csv',
 'tk_ttn_qn_t4.csv',
 'tk_ttn_qn_t40.csv',
 'tk_ttn_qn_t41.csv',
 'tk_ttn_qn_t42.csv',
 'tk_ttn_qn_t43.csv',
 'tk_ttn_qn_t44.csv',
 'tk_ttn_qn_t45.csv',
 'tk_ttn_qn_t46.csv',
 'tk_ttn_qn_t47.csv',
 'tk_ttn_qn_t48.csv',
 'tk_ttn_qn_t49.csv',
 'tk_ttn_qn_t5.csv',
 'tk_ttn_qn_t50.csv',
 'tk_ttn_qn_t6.csv',
 'tk_ttn_qn_t7.csv',
 'tk_ttn_qn_t8.csv',
 'tk_ttn_qn_t9.csv']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_quannu_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales,category
0,"Quần short kaki nữ GOKING, lưng thun và dây rú...",185.000₫,https://tka.tiki.vn/pixel/pixel?data=bX7qFC01U...,1,-42%,Đã bán 268,quannu
1,QUẦN ỐNG RỘNG NỮ BIGSIZE CẠP CAO TÔN DÁNG KÉO ...,175.000₫,https://tka.tiki.vn/pixel/pixel?data=oXhb4t0Rk...,2,-44%,Đã bán 124,quannu
2,Quần short nữ ống rộng lưng cao có túi độc đáo...,139.000₫,https://tka.tiki.vn/pixel/pixel?data=Jb_rKniRw...,3,-50%,Đã bán 18,quannu
3,"Quần đùi nữ , Quần short nữ vải Thái có Big Si...",49.500₫,https://tka.tiki.vn/pixel/pixel?data=MT8cyrySo...,4,-50%,Đã bán 288,quannu
4,Quần short nữ ống rộng cạp cao vắt chéo xếp ly...,250.000₫,https://tka.tiki.vn/pixel/pixel?data=o2kCTCYmw...,5,-21%,Đã bán 115,quannu
...,...,...,...,...,...,...,...
35,NaN,NaN,https://tiki.vn/quan-jean-nu-ong-loe-lung-cao-...,36,NaN,NaN,quannu
36,Quần ống rộng cạp chun Qt05,87.000₫,https://tiki.vn/quan-ong-rong-cap-chun-2-tui-q...,37,NaN,Đã bán 47,quannu
37,Quần đũi nữ cạp chun Banamo quần baggy đũi lưn...,65.000₫,https://tiki.vn/quan-dui-nu-cap-chun-banamo-qu...,38,NaN,Đã bán 13,quannu
38,"Quần ống sớ, quần nữ dáng suông ống rộng khóa ...",140.000₫,https://tiki.vn/quan-ong-so-quan-nu-dang-suong...,39,NaN,Đã bán 89,quannu
39,Quần ống rộng gân tăm đai nơ chất cotton co giãn,79.000₫,https://tiki.vn/quan-ong-rong-gan-tam-dai-no-c...,40,NaN,NaN,quannu

1. Xử lý dữ liệu

In [5]:
df_all = df_all.drop('index', axis=1)

In [6]:
df_all.dropna(subset=['sales'], inplace=True)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales,category
0,"Quần short kaki nữ GOKING, lưng thun và dây rú...",185.000₫,https://tka.tiki.vn/pixel/pixel?data=bX7qFC01U...,-42%,Đã bán 268,quannu
1,QUẦN ỐNG RỘNG NỮ BIGSIZE CẠP CAO TÔN DÁNG KÉO ...,175.000₫,https://tka.tiki.vn/pixel/pixel?data=oXhb4t0Rk...,-44%,Đã bán 124,quannu
2,Quần short nữ ống rộng lưng cao có túi độc đáo...,139.000₫,https://tka.tiki.vn/pixel/pixel?data=Jb_rKniRw...,-50%,Đã bán 18,quannu
3,"Quần đùi nữ , Quần short nữ vải Thái có Big Si...",49.500₫,https://tka.tiki.vn/pixel/pixel?data=MT8cyrySo...,-50%,Đã bán 288,quannu
4,Quần short nữ ống rộng cạp cao vắt chéo xếp ly...,250.000₫,https://tka.tiki.vn/pixel/pixel?data=o2kCTCYmw...,-21%,Đã bán 115,quannu
...,...,...,...,...,...,...
838,"Quần Jean nữ Suông mẫu basic QJ280, Thanh lịch...",199.000₫,https://tiki.vn/quan-jean-nu-suong-mau-basic-q...,NaN,Đã bán 1,quannu
839,Quần nữ thời trang kiểu Hàn Quốc Thu Hà chất l...,149.000,https://tiki.vn/quan-nu-thoi-trang-kieu-han-qu...,NaN,Đã bán 3,quannu
840,Quần ống rộng cạp chun Qt05,87.000₫,https://tiki.vn/quan-ong-rong-cap-chun-2-tui-q...,NaN,Đã bán 47,quannu
841,Quần đũi nữ cạp chun Banamo quần baggy đũi lưn...,65.000₫,https://tiki.vn/quan-dui-nu-cap-chun-banamo-qu...,NaN,Đã bán 13,quannu
842,"Quần ống sớ, quần nữ dáng suông ống rộng khóa ...",140.000₫,https://tiki.vn/quan-ong-so-quan-nu-dang-suong...,NaN,Đã bán 89,quannu

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0      185000
1      175000
2      139000
3       49500
4      250000
        ...
838    199000
839    149000
840     87000
841     65000
842    140000
Name: price, Length: 843, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0      268.0
1      124.0
2       18.0
3      288.0
4      115.0
       ...
838      1.0
839      3.0
840     47.0
841     13.0
842     89.0
Name: sales, Length: 843, dtype: float64

In [11]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0      49580000.0
1      21700000.0
2       2502000.0
3      14256000.0
4      28750000.0
          ...
838      199000.0
839      447000.0
840     4089000.0
841      845000.0
842    12460000.0
Name: revenue, Length: 843, dtype: float64

In [12]:
total = df_all["revenue"].sum()

In [13]:
print("Tổng doanh số quannu: ", total)
print("So mat hang da ban: ", len(df_all["title"])) # san pham da ban
print("So san pham da ban: ", df_all["sales"].sum()) # san pham co luot ban

Tổng doanh số quannu:  3462266473.0
So mat hang da ban:  843
So san pham da ban:  24653.0

In [14]:
df_all

,title,price,link_item,discount,sales,category,revenue
0,"Quần short kaki nữ GOKING, lưng thun và dây rú...",185000,https://tka.tiki.vn/pixel/pixel?data=bX7qFC01U...,-42%,268.0,quannu,49580000.0
1,QUẦN ỐNG RỘNG NỮ BIGSIZE CẠP CAO TÔN DÁNG KÉO ...,175000,https://tka.tiki.vn/pixel/pixel?data=oXhb4t0Rk...,-44%,124.0,quannu,21700000.0
2,Quần short nữ ống rộng lưng cao có túi độc đáo...,139000,https://tka.tiki.vn/pixel/pixel?data=Jb_rKniRw...,-50%,18.0,quannu,2502000.0
3,"Quần đùi nữ , Quần short nữ vải Thái có Big Si...",49500,https://tka.tiki.vn/pixel/pixel?data=MT8cyrySo...,-50%,288.0,quannu,14256000.0
4,Quần short nữ ống rộng cạp cao vắt chéo xếp ly...,250000,https://tka.tiki.vn/pixel/pixel?data=o2kCTCYmw...,-21%,115.0,quannu,28750000.0
...,...,...,...,...,...,...,...
838,"Quần Jean nữ Suông mẫu basic QJ280, Thanh lịch...",199000,https://tiki.vn/quan-jean-nu-suong-mau-basic-q...,NaN,1.0,quannu,199000.0
839,Quần nữ thời trang kiểu Hàn Quốc Thu Hà chất l...,149000,https://tiki.vn/quan-nu-thoi-trang-kieu-han-qu...,NaN,3.0,quannu,447000.0
840,Quần ống rộng cạp chun Qt05,87000,https://tiki.vn/quan-ong-rong-cap-chun-2-tui-q...,NaN,47.0,quannu,4089000.0
841,Quần đũi nữ cạp chun Banamo quần baggy đũi lưn...,65000,https://tiki.vn/quan-dui-nu-cap-chun-banamo-qu...,NaN,13.0,quannu,845000.0
842,"Quần ống sớ, quần nữ dáng suông ống rộng khóa ...",140000,https://tiki.vn/quan-ong-so-quan-nu-dang-suong...,NaN,89.0,quannu,12460000.0

In [15]:
df_all.to_csv("tk_quannu_all_ed.csv")