In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_190124(12htrua) - Copy (6)\dochoi_mevabe\thoitrangmevabe"
os.listdir(path)

['.ipynb_checkpoints',
 'tk_mvb_thoitrangmevabe.ipynb',
 'tk_mvb_thoitrangmevabe_npage.ipynb',
 'tk_thoitrangmevabe.csv',
 'tk_thoitrangmevabe_all.ipynb',
 'tk_thoitrangmevabe_t10.csv',
 'tk_thoitrangmevabe_t11.csv',
 'tk_thoitrangmevabe_t12.csv',
 'tk_thoitrangmevabe_t13.csv',
 'tk_thoitrangmevabe_t14.csv',
 'tk_thoitrangmevabe_t15.csv',
 'tk_thoitrangmevabe_t16.csv',
 'tk_thoitrangmevabe_t17.csv',
 'tk_thoitrangmevabe_t18.csv',
 'tk_thoitrangmevabe_t19.csv',
 'tk_thoitrangmevabe_t2.csv',
 'tk_thoitrangmevabe_t20.csv',
 'tk_thoitrangmevabe_t21.csv',
 'tk_thoitrangmevabe_t22.csv',
 'tk_thoitrangmevabe_t23.csv',
 'tk_thoitrangmevabe_t24.csv',
 'tk_thoitrangmevabe_t25.csv',
 'tk_thoitrangmevabe_t26.csv',
 'tk_thoitrangmevabe_t27.csv',
 'tk_thoitrangmevabe_t28.csv',
 'tk_thoitrangmevabe_t29.csv',
 'tk_thoitrangmevabe_t3.csv',
 'tk_thoitrangmevabe_t30.csv',
 'tk_thoitrangmevabe_t31.csv',
 'tk_thoitrangmevabe_t32.csv',
 'tk_thoitrangmevabe_t33.csv',
 'tk_thoitrangmevabe_t34.csv',
 'tk_thoitrangmevabe_t35.csv',
 'tk_thoitrangmevabe_t36.csv',
 'tk_thoitrangmevabe_t37.csv',
 'tk_thoitrangmevabe_t38.csv',
 'tk_thoitrangmevabe_t39.csv',
 'tk_thoitrangmevabe_t4.csv',
 'tk_thoitrangmevabe_t40.csv',
 'tk_thoitrangmevabe_t41.csv',
 'tk_thoitrangmevabe_t42.csv',
 'tk_thoitrangmevabe_t43.csv',
 'tk_thoitrangmevabe_t44.csv',
 'tk_thoitrangmevabe_t45.csv',
 'tk_thoitrangmevabe_t46.csv',
 'tk_thoitrangmevabe_t47.csv',
 'tk_thoitrangmevabe_t48.csv',
 'tk_thoitrangmevabe_t49.csv',
 'tk_thoitrangmevabe_t5.csv',
 'tk_thoitrangmevabe_t50.csv',
 'tk_thoitrangmevabe_t6.csv',
 'tk_thoitrangmevabe_t7.csv',
 'tk_thoitrangmevabe_t8.csv',
 'tk_thoitrangmevabe_t9.csv']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_thoitrangmevabe_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales,category
0,Vali Kéo Du Lịch Trẻ Em Hình Thú Ngộ Nghĩnh T09,279.000₫,https://tka.tiki.vn/pixel/pixel?data=2CIKEVvLj...,1,-30%,Đã bán 3,thoitrangmevabe
1,Quần áo trẻ em Đồ bộ bé gái lửng chấm bi thun ...,115.000₫,https://tka.tiki.vn/pixel/pixel?data=v_w3M-uFH...,2,-19%,Đã bán 13,thoitrangmevabe
2,Quần áo trẻ em Quần đùi short Bé gái nhiều họa...,39.000₫,https://tka.tiki.vn/pixel/pixel?data=4WDQilEOH...,3,-13%,Đã bán 16,thoitrangmevabe
3,[MUA 1 TẶNG 2] Đồ Chơi Điện Thoại Cho Bé Có Nh...,89.000₫,https://tka.tiki.vn/pixel/pixel?data=enuFYIBxX...,4,-30%,NaN,thoitrangmevabe
4,BALO CHO BÉ BBLUV PAK,290.275₫,https://tka.tiki.vn/pixel/pixel?data=xPuvLXDWV...,5,-30%,Đã bán 1,thoitrangmevabe
...,...,...,...,...,...,...,...
35,ÁO THUN CHO BÉ TRAI BÉ GÁI MẪU THE SHARK,39.000₫,https://tiki.vn/ao-thun-cho-be-trai-be-gai-mau...,36,NaN,Đã bán 50,thoitrangmevabe
36,"Bộ, Set Vest Đen, Xanh Cho Bé Trai, Trẻ Em, Co...",590.000₫,https://tiki.vn/bo-set-vest-den-xanh-cho-be-tr...,37,NaN,Đã bán 15,thoitrangmevabe
37,Đồng hồ trẻ em bé trai bé gái SKMEI 1451 Chống...,129.000₫,https://tiki.vn/dong-ho-tre-em-be-trai-be-gai-...,38,NaN,Đã bán 27,thoitrangmevabe
38,Vali Kéo Du Lịch Trẻ Em Hình Thú Ngộ Nghĩnh T09,279.000₫,https://tiki.vn/vali-keo-du-lich-tre-em-hinh-t...,39,NaN,Đã bán 3,thoitrangmevabe
39,Balo cặp vải cho bé mầm non đi học nhà trẻ mẫu...,119.000₫,https://tiki.vn/balo-cap-vai-cho-be-mam-non-di...,40,NaN,Đã bán 16,thoitrangmevabe

1. Xử lý dữ liệu

In [5]:
df_all = df_all.drop('index', axis=1)

In [6]:
df_all.dropna(subset=['sales'], inplace=True)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales,category
0,Vali Kéo Du Lịch Trẻ Em Hình Thú Ngộ Nghĩnh T09,279.000₫,https://tka.tiki.vn/pixel/pixel?data=2CIKEVvLj...,-30%,Đã bán 3,thoitrangmevabe
1,Quần áo trẻ em Đồ bộ bé gái lửng chấm bi thun ...,115.000₫,https://tka.tiki.vn/pixel/pixel?data=v_w3M-uFH...,-19%,Đã bán 13,thoitrangmevabe
2,Quần áo trẻ em Quần đùi short Bé gái nhiều họa...,39.000₫,https://tka.tiki.vn/pixel/pixel?data=4WDQilEOH...,-13%,Đã bán 16,thoitrangmevabe
3,BALO CHO BÉ BBLUV PAK,290.275₫,https://tka.tiki.vn/pixel/pixel?data=xPuvLXDWV...,-30%,Đã bán 1,thoitrangmevabe
4,VALI MINION MẮT TO - VUÔNG,385.000₫,https://tiki.vn/vali-minion-mat-to-vuong-p1746...,-30%,Đã bán 156,thoitrangmevabe
...,...,...,...,...,...,...
1828,ÁO THUN CHO BÉ TRAI BÉ GÁI MẪU THE SHARK,39.000₫,https://tiki.vn/ao-thun-cho-be-trai-be-gai-mau...,NaN,Đã bán 50,thoitrangmevabe
1829,"Bộ, Set Vest Đen, Xanh Cho Bé Trai, Trẻ Em, Co...",590.000₫,https://tiki.vn/bo-set-vest-den-xanh-cho-be-tr...,NaN,Đã bán 15,thoitrangmevabe
1830,Đồng hồ trẻ em bé trai bé gái SKMEI 1451 Chống...,129.000₫,https://tiki.vn/dong-ho-tre-em-be-trai-be-gai-...,NaN,Đã bán 27,thoitrangmevabe
1831,Vali Kéo Du Lịch Trẻ Em Hình Thú Ngộ Nghĩnh T09,279.000₫,https://tiki.vn/vali-keo-du-lich-tre-em-hinh-t...,NaN,Đã bán 3,thoitrangmevabe
1832,Balo cặp vải cho bé mầm non đi học nhà trẻ mẫu...,119.000₫,https://tiki.vn/balo-cap-vai-cho-be-mam-non-di...,NaN,Đã bán 16,thoitrangmevabe

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0       279000
1       115000
2        39000
3       290275
4       385000
         ...
1828     39000
1829    590000
1830    129000
1831    279000
1832    119000
Name: price, Length: 1833, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0         3.0
1        13.0
2        16.0
3         1.0
4       156.0
        ...
1828     50.0
1829     15.0
1830     27.0
1831      3.0
1832     16.0
Name: sales, Length: 1833, dtype: float64

In [11]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0         837000.0
1        1495000.0
2         624000.0
3         290275.0
4       60060000.0
           ...
1828     1950000.0
1829     8850000.0
1830     3483000.0
1831      837000.0
1832     1904000.0
Name: revenue, Length: 1833, dtype: float64

In [12]:
total = df_all["revenue"].sum()

In [13]:
print("Tổng doanh số thoitrangmevabe: ", total)
print("So mat hang da ban: ", len(df_all["title"])) # san pham da ban
print("So san pham da ban: ", df_all["sales"].sum()) # san pham co luot ban

Tổng doanh số thoitrangmevabe:  8339412910.0
So mat hang da ban:  1833
So san pham da ban:  70024.0

In [14]:
df_all

,title,price,link_item,discount,sales,category,revenue
0,Vali Kéo Du Lịch Trẻ Em Hình Thú Ngộ Nghĩnh T09,279000,https://tka.tiki.vn/pixel/pixel?data=2CIKEVvLj...,-30%,3.0,thoitrangmevabe,837000.0
1,Quần áo trẻ em Đồ bộ bé gái lửng chấm bi thun ...,115000,https://tka.tiki.vn/pixel/pixel?data=v_w3M-uFH...,-19%,13.0,thoitrangmevabe,1495000.0
2,Quần áo trẻ em Quần đùi short Bé gái nhiều họa...,39000,https://tka.tiki.vn/pixel/pixel?data=4WDQilEOH...,-13%,16.0,thoitrangmevabe,624000.0
3,BALO CHO BÉ BBLUV PAK,290275,https://tka.tiki.vn/pixel/pixel?data=xPuvLXDWV...,-30%,1.0,thoitrangmevabe,290275.0
4,VALI MINION MẮT TO - VUÔNG,385000,https://tiki.vn/vali-minion-mat-to-vuong-p1746...,-30%,156.0,thoitrangmevabe,60060000.0
...,...,...,...,...,...,...,...
1828,ÁO THUN CHO BÉ TRAI BÉ GÁI MẪU THE SHARK,39000,https://tiki.vn/ao-thun-cho-be-trai-be-gai-mau...,NaN,50.0,thoitrangmevabe,1950000.0
1829,"Bộ, Set Vest Đen, Xanh Cho Bé Trai, Trẻ Em, Co...",590000,https://tiki.vn/bo-set-vest-den-xanh-cho-be-tr...,NaN,15.0,thoitrangmevabe,8850000.0
1830,Đồng hồ trẻ em bé trai bé gái SKMEI 1451 Chống...,129000,https://tiki.vn/dong-ho-tre-em-be-trai-be-gai-...,NaN,27.0,thoitrangmevabe,3483000.0
1831,Vali Kéo Du Lịch Trẻ Em Hình Thú Ngộ Nghĩnh T09,279000,https://tiki.vn/vali-keo-du-lich-tre-em-hinh-t...,NaN,3.0,thoitrangmevabe,837000.0
1832,Balo cặp vải cho bé mầm non đi học nhà trẻ mẫu...,119000,https://tiki.vn/balo-cap-vai-cho-be-mam-non-di...,NaN,16.0,thoitrangmevabe,1904000.0

In [15]:
df_all.to_csv("tk_thoitrangmevabe_all_ed.csv")