In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_180124(12htrua) - Copy (4)\thoitrangnam\doboi"
os.listdir(path)

['tk_doboi.csv',
 'tk_doboi.ipynb',
 'tk_doboi_all.ipynb',
 'tk_ttn_doboi_npage.ipynb',
 'tk_ttn_doboi_t1.csv',
 'tk_ttn_doboi_t10.csv',
 'tk_ttn_doboi_t11.csv',
 'tk_ttn_doboi_t2.csv',
 'tk_ttn_doboi_t3.csv',
 'tk_ttn_doboi_t4.csv',
 'tk_ttn_doboi_t5.csv',
 'tk_ttn_doboi_t6.csv',
 'tk_ttn_doboi_t7.csv',
 'tk_ttn_doboi_t8.csv',
 'tk_ttn_doboi_t9.csv']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_doboi_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales,category
0,Quần Bơi Nam Thiết Kế Vảy Cá Mập Cleacco Chống...,110.000₫,https://tka.tiki.vn/pixel/pixel?data=fI65miFoe...,1,-45%,Đã bán 697,doboi
1,Quần Bơi Nam Boxer Có Túi CLEACCO DEENYT Chất ...,219.000₫,https://tka.tiki.vn/pixel/pixel?data=6k7kHrPGL...,2,-32%,Đã bán 395,doboi
2,Quần Bơi Nam Thiết Kế Vảy Cá Mập Cleacco Chống...,110.000₫,https://tiki.vn/quan-boi-nam-thiet-ke-vay-ca-m...,3,-45%,Đã bán 697,doboi
3,"Quần bơi, áo bơi nam dạng dài tay ôm sát body ...",220.000₫,https://tiki.vn/quan-boi-ao-boi-nam-dang-dai-t...,4,-42%,Đã bán 7,doboi
4,Quần bơi nam phổ thông,89.000₫,https://tiki.vn/quan-boi-nam-pho-thong-p233676...,5,-30%,Đã bán 15,doboi
...,...,...,...,...,...,...,...
35,NaN,NaN,https://tiki.vn/quan-di-bien-nam-oneill-hyperf...,36,NaN,NaN,doboi
36,Quần đi biển nam Oneill Hyperfreak Heat Stripe...,999.000₫,https://tiki.vn/quan-di-bien-nam-oneill-hyperf...,37,NaN,NaN,doboi
37,"Quần đi biển nam dáng rộng, chất thun bơi lạnh...",260.000₫,https://tiki.vn/quan-di-bien-nam-dang-rong-cha...,38,NaN,Đã bán 3,doboi
38,Quần Short Đi Biển Nam IZOD Swim Shorts - SIZE M,350.000₫,https://tiki.vn/quan-short-tap-gym-nam-izod-sw...,39,NaN,NaN,doboi
39,Quần Tắm Nam Cao Cấp,160.000,https://tiki.vn/quan-tam-nam-cao-cap-p6055663....,40,NaN,NaN,doboi

1. Xử lý dữ liệu

In [5]:
df_all = df_all.drop('index', axis=1)

In [6]:
df_all.dropna(subset=['sales'], inplace=True)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales,category
0,Quần Bơi Nam Thiết Kế Vảy Cá Mập Cleacco Chống...,110.000₫,https://tka.tiki.vn/pixel/pixel?data=fI65miFoe...,-45%,Đã bán 697,doboi
1,Quần Bơi Nam Boxer Có Túi CLEACCO DEENYT Chất ...,219.000₫,https://tka.tiki.vn/pixel/pixel?data=6k7kHrPGL...,-32%,Đã bán 395,doboi
2,Quần Bơi Nam Thiết Kế Vảy Cá Mập Cleacco Chống...,110.000₫,https://tiki.vn/quan-boi-nam-thiet-ke-vay-ca-m...,-45%,Đã bán 697,doboi
3,"Quần bơi, áo bơi nam dạng dài tay ôm sát body ...",220.000₫,https://tiki.vn/quan-boi-ao-boi-nam-dang-dai-t...,-42%,Đã bán 7,doboi
4,Quần bơi nam phổ thông,89.000₫,https://tiki.vn/quan-boi-nam-pho-thong-p233676...,-30%,Đã bán 15,doboi
...,...,...,...,...,...,...
154,Quần short nam vải dù cao cấp QSHOP QS569,350.000₫,https://tiki.vn/quan-short-nam-vai-du-cao-cap-...,NaN,Đã bán 1,doboi
155,QUẦN SHORT ĐI BIỂN MẪU MỚI QS396,250.000₫,https://tiki.vn/quan-short-di-bien-mau-moi-qs3...,NaN,Đã bán 1,doboi
156,Quần bơi cao cấp may 2 lớp chắc chắn chất thun...,119.000₫,https://tiki.vn/quan-boi-cao-cap-may-2-lop-cha...,NaN,Đã bán 1,doboi
157,Quần đi biển nam họa tiết mẫu mới 2022,55.000₫,https://tiki.vn/quan-di-bien-nam-hoa-tiet-mau-...,NaN,Đã bán 1,doboi
158,"Quần đi biển nam dáng rộng, chất thun bơi lạnh...",260.000₫,https://tiki.vn/quan-di-bien-nam-dang-rong-cha...,NaN,Đã bán 3,doboi

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0      110000
1      219000
2      110000
3      220000
4       89000
        ...
154    350000
155    250000
156    119000
157     55000
158    260000
Name: price, Length: 159, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0      697.0
1      395.0
2      697.0
3        7.0
4       15.0
       ...
154      1.0
155      1.0
156      1.0
157      1.0
158      3.0
Name: sales, Length: 159, dtype: float64

In [11]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0      76670000.0
1      86505000.0
2      76670000.0
3       1540000.0
4       1335000.0
          ...
154      350000.0
155      250000.0
156      119000.0
157       55000.0
158      780000.0
Name: revenue, Length: 159, dtype: float64

In [12]:
total = df_all["revenue"].sum()

In [13]:
print("Tổng doanh số doboi: ", total)
print("So mat hang da ban: ", len(df_all["title"])) # san pham da ban
print("So san pham da ban: ", df_all["sales"].sum()) # san pham co luot ban

Tổng doanh số doboi:  1432916830.0
So mat hang da ban:  159
So san pham da ban:  9241.0

In [14]:
df_all

,title,price,link_item,discount,sales,category,revenue
0,Quần Bơi Nam Thiết Kế Vảy Cá Mập Cleacco Chống...,110000,https://tka.tiki.vn/pixel/pixel?data=fI65miFoe...,-45%,697.0,doboi,76670000.0
1,Quần Bơi Nam Boxer Có Túi CLEACCO DEENYT Chất ...,219000,https://tka.tiki.vn/pixel/pixel?data=6k7kHrPGL...,-32%,395.0,doboi,86505000.0
2,Quần Bơi Nam Thiết Kế Vảy Cá Mập Cleacco Chống...,110000,https://tiki.vn/quan-boi-nam-thiet-ke-vay-ca-m...,-45%,697.0,doboi,76670000.0
3,"Quần bơi, áo bơi nam dạng dài tay ôm sát body ...",220000,https://tiki.vn/quan-boi-ao-boi-nam-dang-dai-t...,-42%,7.0,doboi,1540000.0
4,Quần bơi nam phổ thông,89000,https://tiki.vn/quan-boi-nam-pho-thong-p233676...,-30%,15.0,doboi,1335000.0
...,...,...,...,...,...,...,...
154,Quần short nam vải dù cao cấp QSHOP QS569,350000,https://tiki.vn/quan-short-nam-vai-du-cao-cap-...,NaN,1.0,doboi,350000.0
155,QUẦN SHORT ĐI BIỂN MẪU MỚI QS396,250000,https://tiki.vn/quan-short-di-bien-mau-moi-qs3...,NaN,1.0,doboi,250000.0
156,Quần bơi cao cấp may 2 lớp chắc chắn chất thun...,119000,https://tiki.vn/quan-boi-cao-cap-may-2-lop-cha...,NaN,1.0,doboi,119000.0
157,Quần đi biển nam họa tiết mẫu mới 2022,55000,https://tiki.vn/quan-di-bien-nam-hoa-tiet-mau-...,NaN,1.0,doboi,55000.0
158,"Quần đi biển nam dáng rộng, chất thun bơi lạnh...",260000,https://tiki.vn/quan-di-bien-nam-dang-rong-cha...,NaN,3.0,doboi,780000.0

In [15]:
df_all.to_csv("tk_doboi_all_ed.csv")