In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_190124(12hdem) - Copy (5)\thoitrangnu\doboi"
os.listdir(path)

['.ipynb_checkpoints',
 'tk_doboi_all.ipynb',
 'tk_ttn_doboi.ipynb',
 'tk_ttn_doboinu_t1.csv',
 'tk_ttn_doboinu_t10.csv',
 'tk_ttn_doboinu_t11.csv',
 'tk_ttn_doboinu_t12.csv',
 'tk_ttn_doboinu_t13.csv',
 'tk_ttn_doboinu_t14.csv',
 'tk_ttn_doboinu_t15.csv',
 'tk_ttn_doboinu_t16.csv',
 'tk_ttn_doboinu_t17.csv',
 'tk_ttn_doboinu_t18.csv',
 'tk_ttn_doboinu_t19.csv',
 'tk_ttn_doboinu_t2.csv',
 'tk_ttn_doboinu_t20.csv',
 'tk_ttn_doboinu_t21.csv',
 'tk_ttn_doboinu_t22.csv',
 'tk_ttn_doboinu_t23.csv',
 'tk_ttn_doboinu_t24.csv',
 'tk_ttn_doboinu_t25.csv',
 'tk_ttn_doboinu_t26.csv',
 'tk_ttn_doboinu_t27.csv',
 'tk_ttn_doboinu_t28.csv',
 'tk_ttn_doboinu_t29.csv',
 'tk_ttn_doboinu_t3.csv',
 'tk_ttn_doboinu_t30.csv',
 'tk_ttn_doboinu_t31.csv',
 'tk_ttn_doboinu_t32.csv',
 'tk_ttn_doboinu_t33.csv',
 'tk_ttn_doboinu_t34.csv',
 'tk_ttn_doboinu_t35.csv',
 'tk_ttn_doboinu_t36.csv',
 'tk_ttn_doboinu_t37.csv',
 'tk_ttn_doboinu_t38.csv',
 'tk_ttn_doboinu_t39.csv',
 'tk_ttn_doboinu_t4.csv',
 'tk_ttn_doboinu_t40.csv',
 'tk_ttn_doboinu_t41.csv',
 'tk_ttn_doboinu_t42.csv',
 'tk_ttn_doboinu_t43.csv',
 'tk_ttn_doboinu_t44.csv',
 'tk_ttn_doboinu_t45.csv',
 'tk_ttn_doboinu_t46.csv',
 'tk_ttn_doboinu_t47.csv',
 'tk_ttn_doboinu_t48.csv',
 'tk_ttn_doboinu_t49.csv',
 'tk_ttn_doboinu_t5.csv',
 'tk_ttn_doboinu_t50.csv',
 'tk_ttn_doboinu_t6.csv',
 'tk_ttn_doboinu_t7.csv',
 'tk_ttn_doboinu_t8.csv',
 'tk_ttn_doboinu_t9.csv',
 'tk_ttn_doboi_npage.ipynb']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_doboi_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales,category
0,"Đồ bơi nữ dài tay, chân váy may liền quần sooc...",392.000₫,https://tka.tiki.vn/pixel/pixel?data=95pKbTiQb...,1,-12%,Đã bán 1,doboinu
1,Bộ đồ bơi cho nữ chân váy rời size từ 40kg đến...,319.000₫,https://tka.tiki.vn/pixel/pixel?data=Ez2fz-pPo...,2,-12%,NaN,doboinu
2,Đồ bơi nữ tay dài - Im the girl,307.000₫,https://tka.tiki.vn/pixel/pixel?data=h3Y2Ysp4Z...,3,-12%,Đã bán 1,doboinu
3,Đồ bơi cho nữ quần Short size từ 40kg đến 64kg,317.000₫,https://tka.tiki.vn/pixel/pixel?data=HKp2n4gjw...,4,-12%,Đã bán 1,doboinu
4,Bikini đi biển QUEEN BIKINI Đồ bơi nữ kín đáo ...,349.000₫,https://tka.tiki.vn/pixel/pixel?data=dc4yof39g...,5,-2%,Đã bán 94,doboinu
...,...,...,...,...,...,...,...
35,"Áo tắm liền thân quần đùi dài nữ, thiết kế dấu...",390.000₫,https://tiki.vn/ao-tam-lien-than-quan-dui-dai-...,36,NaN,NaN,doboinu
36,Váy Tắm nữ Thời Trang Đi Biển Đi Bơi,380.000₫,https://tiki.vn/vay-tam-nu-thoi-trang-di-bien-...,37,NaN,NaN,doboinu
37,Bộ đồ bơi bikini nữ 1 mảnh kín đáo đi tắm biển...,150.000₫,https://tiki.vn/bo-do-boi-bikini-nu-1-manh-kin...,38,NaN,NaN,doboinu
38,Váy Đi Biển Đi Bơi Cao Cấp,392.000₫,https://tiki.vn/vay-di-bien-di-boi-cao-cap-p19...,39,NaN,NaN,doboinu
39,Bikini liền mảnh màu đen tay dài 1 bên che bụn...,375.000₫,https://tiki.vn/bikini-lien-manh-mau-den-tay-d...,40,NaN,NaN,doboinu

1. Xử lý dữ liệu

In [5]:
df_all = df_all.drop('index', axis=1)

In [6]:
df_all.dropna(subset=['sales'], inplace=True)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales,category
0,"Đồ bơi nữ dài tay, chân váy may liền quần sooc...",392.000₫,https://tka.tiki.vn/pixel/pixel?data=95pKbTiQb...,-12%,Đã bán 1,doboinu
1,Đồ bơi nữ tay dài - Im the girl,307.000₫,https://tka.tiki.vn/pixel/pixel?data=h3Y2Ysp4Z...,-12%,Đã bán 1,doboinu
2,Đồ bơi cho nữ quần Short size từ 40kg đến 64kg,317.000₫,https://tka.tiki.vn/pixel/pixel?data=HKp2n4gjw...,-12%,Đã bán 1,doboinu
3,Bikini đi biển QUEEN BIKINI Đồ bơi nữ kín đáo ...,349.000₫,https://tka.tiki.vn/pixel/pixel?data=dc4yof39g...,-2%,Đã bán 94,doboinu
4,Đồ Bơi Nữ Hai Mảnh Đa Năng AT168 MayHomes Áo B...,161.700₫,https://tiki.vn/do-boi-nu-hai-manh-da-nang-at1...,-2%,Đã bán 1.1k,doboinu
...,...,...,...,...,...,...
654,Bikini 2 Mảnh Sexy B132,290.000₫,https://tiki.vn/bikini-2-manh-sexy-b132-p20072...,NaN,Đã bán 1,doboinu
655,Bộ đồ bơi đôi dài tay nam nữ khoá kéo đen lườn...,550.000₫,https://tiki.vn/bo-do-boi-doi-dai-tay-nam-nu-k...,NaN,Đã bán 1,doboinu
656,"Set bơi 3 chi tiết cao cấp, họa tiết lá xanh h...",550.000₫,https://tiki.vn/set-boi-3-chi-tiet-cao-cap-hoa...,NaN,Đã bán 9,doboinu
657,Đồ bơi nữ liền thân năng động,369.000₫,https://tiki.vn/do-boi-nu-lien-than-nang-dong-...,NaN,Đã bán 6,doboinu
658,"Đồ bơi nữ, chất vải co giãn 4 chiều, liền thân...",429.000₫,https://tiki.vn/do-boi-nu-chat-vai-co-gian-4-c...,NaN,Đã bán 1,doboinu

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0      392000
1      307000
2      317000
3      349000
4      161700
        ...
654    290000
655    550000
656    550000
657    369000
658    429000
Name: price, Length: 659, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0         1.0
1         1.0
2         1.0
3        94.0
4      1100.0
        ...
654       1.0
655       1.0
656       9.0
657       6.0
658       1.0
Name: sales, Length: 659, dtype: float64

In [11]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0         392000.0
1         307000.0
2         317000.0
3       32806000.0
4      177870000.0
          ...
654       290000.0
655       550000.0
656      4950000.0
657      2214000.0
658       429000.0
Name: revenue, Length: 659, dtype: float64

In [12]:
total = df_all["revenue"].sum()

In [13]:
print("Tổng doanh số doboi: ", total)
print("So mat hang da ban: ", len(df_all["title"])) # san pham da ban
print("So san pham da ban: ", df_all["sales"].sum()) # san pham co luot ban

Tổng doanh số doboi:  2618240101.0
So mat hang da ban:  659
So san pham da ban:  10889.0

In [14]:
df_all

,title,price,link_item,discount,sales,category,revenue
0,"Đồ bơi nữ dài tay, chân váy may liền quần sooc...",392000,https://tka.tiki.vn/pixel/pixel?data=95pKbTiQb...,-12%,1.0,doboinu,392000.0
1,Đồ bơi nữ tay dài - Im the girl,307000,https://tka.tiki.vn/pixel/pixel?data=h3Y2Ysp4Z...,-12%,1.0,doboinu,307000.0
2,Đồ bơi cho nữ quần Short size từ 40kg đến 64kg,317000,https://tka.tiki.vn/pixel/pixel?data=HKp2n4gjw...,-12%,1.0,doboinu,317000.0
3,Bikini đi biển QUEEN BIKINI Đồ bơi nữ kín đáo ...,349000,https://tka.tiki.vn/pixel/pixel?data=dc4yof39g...,-2%,94.0,doboinu,32806000.0
4,Đồ Bơi Nữ Hai Mảnh Đa Năng AT168 MayHomes Áo B...,161700,https://tiki.vn/do-boi-nu-hai-manh-da-nang-at1...,-2%,1100.0,doboinu,177870000.0
...,...,...,...,...,...,...,...
654,Bikini 2 Mảnh Sexy B132,290000,https://tiki.vn/bikini-2-manh-sexy-b132-p20072...,NaN,1.0,doboinu,290000.0
655,Bộ đồ bơi đôi dài tay nam nữ khoá kéo đen lườn...,550000,https://tiki.vn/bo-do-boi-doi-dai-tay-nam-nu-k...,NaN,1.0,doboinu,550000.0
656,"Set bơi 3 chi tiết cao cấp, họa tiết lá xanh h...",550000,https://tiki.vn/set-boi-3-chi-tiet-cao-cap-hoa...,NaN,9.0,doboinu,4950000.0
657,Đồ bơi nữ liền thân năng động,369000,https://tiki.vn/do-boi-nu-lien-than-nang-dong-...,NaN,6.0,doboinu,2214000.0
658,"Đồ bơi nữ, chất vải co giãn 4 chiều, liền thân...",429000,https://tiki.vn/do-boi-nu-chat-vai-co-gian-4-c...,NaN,1.0,doboinu,429000.0

In [15]:
df_all.to_csv("tk_doboi_all_ed.csv")