In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_190124(12htrua) - Copy (6)\thoitrangnam\aosomi"
os.listdir(path)

['.ipynb_checkpoints',
 'tk_aosomi_all.ipynb',
 'tk_ttnam_aosomi.ipynb',
 'tk_ttnam_aosomi_npage.ipynb',
 'tk_ttnam_aosomi_t1.csv',
 'tk_ttnam_aosomi_t10.csv',
 'tk_ttnam_aosomi_t11.csv',
 'tk_ttnam_aosomi_t12.csv',
 'tk_ttnam_aosomi_t13.csv',
 'tk_ttnam_aosomi_t14.csv',
 'tk_ttnam_aosomi_t15.csv',
 'tk_ttnam_aosomi_t16.csv',
 'tk_ttnam_aosomi_t17.csv',
 'tk_ttnam_aosomi_t18.csv',
 'tk_ttnam_aosomi_t19.csv',
 'tk_ttnam_aosomi_t2.csv',
 'tk_ttnam_aosomi_t20.csv',
 'tk_ttnam_aosomi_t21.csv',
 'tk_ttnam_aosomi_t22.csv',
 'tk_ttnam_aosomi_t23.csv',
 'tk_ttnam_aosomi_t24.csv',
 'tk_ttnam_aosomi_t25.csv',
 'tk_ttnam_aosomi_t26.csv',
 'tk_ttnam_aosomi_t27.csv',
 'tk_ttnam_aosomi_t28.csv',
 'tk_ttnam_aosomi_t29.csv',
 'tk_ttnam_aosomi_t3.csv',
 'tk_ttnam_aosomi_t30.csv',
 'tk_ttnam_aosomi_t31.csv',
 'tk_ttnam_aosomi_t32.csv',
 'tk_ttnam_aosomi_t33.csv',
 'tk_ttnam_aosomi_t34.csv',
 'tk_ttnam_aosomi_t35.csv',
 'tk_ttnam_aosomi_t36.csv',
 'tk_ttnam_aosomi_t37.csv',
 'tk_ttnam_aosomi_t38.csv',
 'tk_ttnam_aosomi_t39.csv',
 'tk_ttnam_aosomi_t4.csv',
 'tk_ttnam_aosomi_t40.csv',
 'tk_ttnam_aosomi_t41.csv',
 'tk_ttnam_aosomi_t42.csv',
 'tk_ttnam_aosomi_t43.csv',
 'tk_ttnam_aosomi_t44.csv',
 'tk_ttnam_aosomi_t45.csv',
 'tk_ttnam_aosomi_t46.csv',
 'tk_ttnam_aosomi_t47.csv',
 'tk_ttnam_aosomi_t48.csv',
 'tk_ttnam_aosomi_t49.csv',
 'tk_ttnam_aosomi_t5.csv',
 'tk_ttnam_aosomi_t50.csv',
 'tk_ttnam_aosomi_t6.csv',
 'tk_ttnam_aosomi_t7.csv',
 'tk_ttnam_aosomi_t8.csv',
 'tk_ttnam_aosomi_t9.csv']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_aosomi_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales,category
0,Áo sơ mi nam vải cotton mềm không nhăn-Quà tặng,108.000₫,https://tka.tiki.vn/pixel/pixel?data=HVrmdVJJQ...,1,-41%,Đã bán 33,aosomi
1,Áo sơ mi nam dài tay màu trắng không túi vải m...,108.000₫,https://tka.tiki.vn/pixel/pixel?data=ivuvlBECN...,2,-35%,Đã bán 30,aosomi
2,Áo sơ mi nam dài tay màu tím,159.000₫,https://tka.tiki.vn/pixel/pixel?data=X8G2VZoZa...,3,-31%,Đã bán 23,aosomi
3,Áo sơ mi nam dài tay vải cotton mểm không nhăn,108.000,https://tka.tiki.vn/pixel/pixel?data=kKVVf24wS...,4,NaN,NaN,aosomi
4,NaN,NaN,https://tka.tiki.vn/pixel/pixel?data=1MbqkvlhZ...,5,NaN,NaN,aosomi
...,...,...,...,...,...,...,...
35,Áo sơ mi nam ngắn tay a,195.000₫,https://tiki.vn/ao-so-mi-nam-ngan-tay-a-p25161...,36,NaN,Đã bán 3,aosomi
36,Áo Sơ Mi Nam Tay Ngắn Mẫu 1,228.000,https://tiki.vn/a-o-so-mi-nam-tay-ngan-ma-u-1-...,37,NaN,NaN,aosomi
37,NaN,NaN,https://tiki.vn/ao-so-mi-trang-nam-hoa-tiet-ho...,38,NaN,NaN,aosomi
38,Áo Sơ Mi Nam Họa Tiết Vải Lụa Hàn Không Nhăn H...,299.000₫,https://tiki.vn/ao-so-mi-nam-hoa-tiet-vai-lua-...,39,NaN,Đã bán 4,aosomi
39,Áo Sơ Mi Form Rộng Unisex Nam Nữ Tay Dài Hàn Q...,99.000₫,https://tiki.vn/ao-so-mi-form-rong-unisex-nam-...,40,NaN,Đã bán 35,aosomi

1. Xử lý dữ liệu

In [5]:
df_all = df_all.drop('index', axis=1)

In [6]:
df_all.dropna(subset=['sales'], inplace=True)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales,category
0,Áo sơ mi nam vải cotton mềm không nhăn-Quà tặng,108.000₫,https://tka.tiki.vn/pixel/pixel?data=HVrmdVJJQ...,-41%,Đã bán 33,aosomi
1,Áo sơ mi nam dài tay màu trắng không túi vải m...,108.000₫,https://tka.tiki.vn/pixel/pixel?data=ivuvlBECN...,-35%,Đã bán 30,aosomi
2,Áo sơ mi nam dài tay màu tím,159.000₫,https://tka.tiki.vn/pixel/pixel?data=X8G2VZoZa...,-31%,Đã bán 23,aosomi
3,Áo sơ mi nam trơn tay dài cao cấp Lados - 779 ...,139.000₫,https://tiki.vn/ao-so-mi-nam-tron-tay-dai-cao-...,NaN,Đã bán 3.2k,aosomi
4,"Áo sơ mi nam trơn không nhăn LADOS - 523, Chất...",116.000₫,https://tiki.vn/ao-so-mi-nam-tron-khong-nhan-l...,-51%,Đã bán 542,aosomi
...,...,...,...,...,...,...
828,Áo sơ mi ngắn tay nam Columbia Pine Canyon - 2...,545.000,https://tiki.vn/ao-so-mi-ngan-tay-nam-columbia...,NaN,Đã bán 1,aosomi
829,"Áo sơ mi nam, áo sơ mi cộc tay phối màu trẻ tr...",199.000₫,https://tiki.vn/ao-so-mi-nam-ao-so-mi-coc-tay-...,NaN,Đã bán 2,aosomi
830,Áo sơ mi nam ngắn tay a,195.000₫,https://tiki.vn/ao-so-mi-nam-ngan-tay-a-p25161...,NaN,Đã bán 3,aosomi
831,Áo Sơ Mi Nam Họa Tiết Vải Lụa Hàn Không Nhăn H...,299.000₫,https://tiki.vn/ao-so-mi-nam-hoa-tiet-vai-lua-...,NaN,Đã bán 4,aosomi
832,Áo Sơ Mi Form Rộng Unisex Nam Nữ Tay Dài Hàn Q...,99.000₫,https://tiki.vn/ao-so-mi-form-rong-unisex-nam-...,NaN,Đã bán 35,aosomi

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0      108000
1      108000
2      159000
3      139000
4      116000
        ...
828    545000
829    199000
830    195000
831    299000
832     99000
Name: price, Length: 833, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0        33.0
1        30.0
2        23.0
3      3200.0
4       542.0
        ...
828       1.0
829       2.0
830       3.0
831       4.0
832      35.0
Name: sales, Length: 833, dtype: float64

In [11]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0        3564000.0
1        3240000.0
2        3657000.0
3      444800000.0
4       62872000.0
          ...
828       545000.0
829       398000.0
830       585000.0
831      1196000.0
832      3465000.0
Name: revenue, Length: 833, dtype: float64

In [12]:
total = df_all["revenue"].sum()

In [13]:
print("Tổng doanh số aosomi: ", total)
print("So mat hang da ban: ", len(df_all["title"])) # san pham da ban
print("So san pham da ban: ", df_all["sales"].sum()) # san pham co luot ban

Tổng doanh số aosomi:  3490099120.0
So mat hang da ban:  833
So san pham da ban:  20489.0

In [14]:
df_all

,title,price,link_item,discount,sales,category,revenue
0,Áo sơ mi nam vải cotton mềm không nhăn-Quà tặng,108000,https://tka.tiki.vn/pixel/pixel?data=HVrmdVJJQ...,-41%,33.0,aosomi,3564000.0
1,Áo sơ mi nam dài tay màu trắng không túi vải m...,108000,https://tka.tiki.vn/pixel/pixel?data=ivuvlBECN...,-35%,30.0,aosomi,3240000.0
2,Áo sơ mi nam dài tay màu tím,159000,https://tka.tiki.vn/pixel/pixel?data=X8G2VZoZa...,-31%,23.0,aosomi,3657000.0
3,Áo sơ mi nam trơn tay dài cao cấp Lados - 779 ...,139000,https://tiki.vn/ao-so-mi-nam-tron-tay-dai-cao-...,NaN,3200.0,aosomi,444800000.0
4,"Áo sơ mi nam trơn không nhăn LADOS - 523, Chất...",116000,https://tiki.vn/ao-so-mi-nam-tron-khong-nhan-l...,-51%,542.0,aosomi,62872000.0
...,...,...,...,...,...,...,...
828,Áo sơ mi ngắn tay nam Columbia Pine Canyon - 2...,545000,https://tiki.vn/ao-so-mi-ngan-tay-nam-columbia...,NaN,1.0,aosomi,545000.0
829,"Áo sơ mi nam, áo sơ mi cộc tay phối màu trẻ tr...",199000,https://tiki.vn/ao-so-mi-nam-ao-so-mi-coc-tay-...,NaN,2.0,aosomi,398000.0
830,Áo sơ mi nam ngắn tay a,195000,https://tiki.vn/ao-so-mi-nam-ngan-tay-a-p25161...,NaN,3.0,aosomi,585000.0
831,Áo Sơ Mi Nam Họa Tiết Vải Lụa Hàn Không Nhăn H...,299000,https://tiki.vn/ao-so-mi-nam-hoa-tiet-vai-lua-...,NaN,4.0,aosomi,1196000.0
832,Áo Sơ Mi Form Rộng Unisex Nam Nữ Tay Dài Hàn Q...,99000,https://tiki.vn/ao-so-mi-form-rong-unisex-nam-...,NaN,35.0,aosomi,3465000.0

In [15]:
df_all.to_csv("tk_aosomi_all_ed.csv")