In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_160124(12hdem)\thoitrangnam\doboi"
os.listdir(path)

['tk_doboi.csv',
 'tk_doboi.ipynb',
 'tk_doboi_all.ipynb',
 'tk_ttn_doboi_npage.ipynb',
 'tk_ttn_doboi_t10.csv',
 'tk_ttn_doboi_t11.csv',
 'tk_ttn_doboi_t2.csv',
 'tk_ttn_doboi_t3.csv',
 'tk_ttn_doboi_t4.csv',
 'tk_ttn_doboi_t5.csv',
 'tk_ttn_doboi_t6.csv',
 'tk_ttn_doboi_t7.csv',
 'tk_ttn_doboi_t8.csv',
 'tk_ttn_doboi_t9.csv']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_doboi_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales,category
0,Quần Bơi Nam Thiết Kế Vảy Cá Mập Cleacco Chống...,111.000₫,https://tka.tiki.vn/pixel/pixel?data=nqPqrHH72...,1,-45%,Đã bán 697,doboi
1,Quần Bơi Nam Boxer Có Túi CLEACCO DEENYT Chất ...,195.000₫,https://tka.tiki.vn/pixel/pixel?data=a7aSaWVBF...,2,-40%,Đã bán 395,doboi
2,Quần Bơi Nam Thiết Kế Vảy Cá Mập Cleacco Chống...,108.000₫,https://tiki.vn/quan-boi-nam-thiet-ke-vay-ca-m...,3,-46%,Đã bán 697,doboi
3,"Quần bơi, áo bơi nam dạng dài tay ôm sát body ...",220.000₫,https://tiki.vn/quan-boi-ao-boi-nam-dang-dai-t...,4,-42%,Đã bán 7,doboi
4,Quần bơi nam phổ thông,89.000₫,https://tiki.vn/quan-boi-nam-pho-thong-p233676...,5,-30%,Đã bán 15,doboi
...,...,...,...,...,...,...,...
35,NaN,NaN,https://tiki.vn/quan-boi-nam-tam-giac-in-hinh-...,36,NaN,NaN,doboi
36,"Quần bơi nam họa tiết cool ngầu, phom rộng rãi...",130.000₫,https://tiki.vn/quan-boi-nam-hoa-tiet-cool-nga...,37,NaN,NaN,doboi
37,Quần đi biển nam Oneill Hyperfreak Mysto 20 - ...,899.000₫,https://tiki.vn/quan-di-bien-nam-oneill-hyperf...,38,NaN,NaN,doboi
38,Quần Bơi Nam Kèm Mũ,99.900₫,https://tiki.vn/quan-boi-nam-kem-mu-p17904013....,39,NaN,NaN,doboi
39,Quần bơi boxer nam thun poly co giãn tốt QSHOP...,180.000,https://tiki.vn/quan-boi-boxer-nam-thun-poly-c...,40,NaN,NaN,doboi

1. Xử lý dữ liệu

In [5]:
df_all = df_all.drop('index', axis=1)

In [6]:
df_all.dropna(subset=['sales'], inplace=True)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales,category
0,Quần Bơi Nam Thiết Kế Vảy Cá Mập Cleacco Chống...,111.000₫,https://tka.tiki.vn/pixel/pixel?data=nqPqrHH72...,-45%,Đã bán 697,doboi
1,Quần Bơi Nam Boxer Có Túi CLEACCO DEENYT Chất ...,195.000₫,https://tka.tiki.vn/pixel/pixel?data=a7aSaWVBF...,-40%,Đã bán 395,doboi
2,Quần Bơi Nam Thiết Kế Vảy Cá Mập Cleacco Chống...,108.000₫,https://tiki.vn/quan-boi-nam-thiet-ke-vay-ca-m...,-46%,Đã bán 697,doboi
3,"Quần bơi, áo bơi nam dạng dài tay ôm sát body ...",220.000₫,https://tiki.vn/quan-boi-ao-boi-nam-dang-dai-t...,-42%,Đã bán 7,doboi
4,Quần bơi nam phổ thông,89.000₫,https://tiki.vn/quan-boi-nam-pho-thong-p233676...,-30%,Đã bán 15,doboi
...,...,...,...,...,...,...
127,Quần short nam vải dù cao cấp QSHOP QS569,350.000₫,https://tiki.vn/quan-short-nam-vai-du-cao-cap-...,-10%,Đã bán 1,doboi
128,Quần bơi cao cấp may 2 lớp chắc chắn chất thun...,119.000₫,https://tiki.vn/quan-boi-cao-cap-may-2-lop-cha...,NaN,Đã bán 1,doboi
129,Quần đi biển nam họa tiết mẫu mới 2022,55.000₫,https://tiki.vn/quan-di-bien-nam-hoa-tiet-mau-...,NaN,Đã bán 1,doboi
130,"Quần đi biển nam dáng rộng, chất thun bơi lạnh...",260.000₫,https://tiki.vn/quan-di-bien-nam-dang-rong-cha...,NaN,Đã bán 3,doboi
131,Quần Tắm Nam Cao Cấp,160.000₫,https://tiki.vn/quan-tam-nam-cao-cap-p6055663....,NaN,Đã bán 4,doboi

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0      111000
1      195000
2      108000
3      220000
4       89000
        ...
127    350000
128    119000
129     55000
130    260000
131    160000
Name: price, Length: 132, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0      697.0
1      395.0
2      697.0
3        7.0
4       15.0
       ...
127      1.0
128      1.0
129      1.0
130      3.0
131      4.0
Name: sales, Length: 132, dtype: float64

In [11]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0      77367000.0
1      77025000.0
2      75276000.0
3       1540000.0
4       1335000.0
          ...
127      350000.0
128      119000.0
129       55000.0
130      780000.0
131      640000.0
Name: revenue, Length: 132, dtype: float64

In [12]:
total = df_all["revenue"].sum()

In [13]:
print("Tổng doanh số doboi: ", total)
print("So mat hang da ban: ", len(df_all["title"])) # san pham da ban
print("So san pham da ban: ", df_all["sales"].sum()) # san pham co luot ban

Tổng doanh số doboi:  942627270.0
So mat hang da ban:  132
So san pham da ban:  6025.0

In [14]:
df_all

,title,price,link_item,discount,sales,category,revenue
0,Quần Bơi Nam Thiết Kế Vảy Cá Mập Cleacco Chống...,111000,https://tka.tiki.vn/pixel/pixel?data=nqPqrHH72...,-45%,697.0,doboi,77367000.0
1,Quần Bơi Nam Boxer Có Túi CLEACCO DEENYT Chất ...,195000,https://tka.tiki.vn/pixel/pixel?data=a7aSaWVBF...,-40%,395.0,doboi,77025000.0
2,Quần Bơi Nam Thiết Kế Vảy Cá Mập Cleacco Chống...,108000,https://tiki.vn/quan-boi-nam-thiet-ke-vay-ca-m...,-46%,697.0,doboi,75276000.0
3,"Quần bơi, áo bơi nam dạng dài tay ôm sát body ...",220000,https://tiki.vn/quan-boi-ao-boi-nam-dang-dai-t...,-42%,7.0,doboi,1540000.0
4,Quần bơi nam phổ thông,89000,https://tiki.vn/quan-boi-nam-pho-thong-p233676...,-30%,15.0,doboi,1335000.0
...,...,...,...,...,...,...,...
127,Quần short nam vải dù cao cấp QSHOP QS569,350000,https://tiki.vn/quan-short-nam-vai-du-cao-cap-...,-10%,1.0,doboi,350000.0
128,Quần bơi cao cấp may 2 lớp chắc chắn chất thun...,119000,https://tiki.vn/quan-boi-cao-cap-may-2-lop-cha...,NaN,1.0,doboi,119000.0
129,Quần đi biển nam họa tiết mẫu mới 2022,55000,https://tiki.vn/quan-di-bien-nam-hoa-tiet-mau-...,NaN,1.0,doboi,55000.0
130,"Quần đi biển nam dáng rộng, chất thun bơi lạnh...",260000,https://tiki.vn/quan-di-bien-nam-dang-rong-cha...,NaN,3.0,doboi,780000.0
131,Quần Tắm Nam Cao Cấp,160000,https://tiki.vn/quan-tam-nam-cao-cap-p6055663....,NaN,4.0,doboi,640000.0

In [15]:
df_all.to_csv("tk_doboi_all_ed.csv")