In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_170124(12hdem) - Copy\thoitrangnu\aokhoacnu"
os.listdir(path)

['.ipynb_checkpoints',
 'tk_akn.csv',
 'tk_aokhoacnu_all.ipynb',
 'tk_ttn_akn.ipynb',
 'tk_ttn_akn_npage.ipynb',
 'tk_ttn_akn_t10.csv',
 'tk_ttn_akn_t11.csv',
 'tk_ttn_akn_t12.csv',
 'tk_ttn_akn_t13.csv',
 'tk_ttn_akn_t14.csv',
 'tk_ttn_akn_t15.csv',
 'tk_ttn_akn_t16.csv',
 'tk_ttn_akn_t17.csv',
 'tk_ttn_akn_t18.csv',
 'tk_ttn_akn_t19.csv',
 'tk_ttn_akn_t2.csv',
 'tk_ttn_akn_t20.csv',
 'tk_ttn_akn_t21.csv',
 'tk_ttn_akn_t22.csv',
 'tk_ttn_akn_t23.csv',
 'tk_ttn_akn_t24.csv',
 'tk_ttn_akn_t25.csv',
 'tk_ttn_akn_t26.csv',
 'tk_ttn_akn_t27.csv',
 'tk_ttn_akn_t28.csv',
 'tk_ttn_akn_t29.csv',
 'tk_ttn_akn_t3.csv',
 'tk_ttn_akn_t30.csv',
 'tk_ttn_akn_t31.csv',
 'tk_ttn_akn_t32.csv',
 'tk_ttn_akn_t33.csv',
 'tk_ttn_akn_t34.csv',
 'tk_ttn_akn_t35.csv',
 'tk_ttn_akn_t36.csv',
 'tk_ttn_akn_t37.csv',
 'tk_ttn_akn_t38.csv',
 'tk_ttn_akn_t39.csv',
 'tk_ttn_akn_t4.csv',
 'tk_ttn_akn_t40.csv',
 'tk_ttn_akn_t41.csv',
 'tk_ttn_akn_t42.csv',
 'tk_ttn_akn_t43.csv',
 'tk_ttn_akn_t44.csv',
 'tk_ttn_akn_t45.csv',
 'tk_ttn_akn_t46.csv',
 'tk_ttn_akn_t47.csv',
 'tk_ttn_akn_t48.csv',
 'tk_ttn_akn_t49.csv',
 'tk_ttn_akn_t5.csv',
 'tk_ttn_akn_t50.csv',
 'tk_ttn_akn_t6.csv',
 'tk_ttn_akn_t7.csv',
 'tk_ttn_akn_t8.csv',
 'tk_ttn_akn_t9.csv']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_aokhoacnu_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales,category
0,"Áo khoác gió cách nhiệt GOKING, form unisex ch...",235.000₫,https://tka.tiki.vn/pixel/pixel?data=hdk2OleDq...,1,-44%,Đã bán 89,aokhoacnu
1,Áo vest nữ blazer hàn quốc [HÀNG CAO CẤP] form...,299.000₫,https://tka.tiki.vn/pixel/pixel?data=ozddpQdWx...,2,-44%,Đã bán 97,aokhoacnu
2,"Áo khoác gió GOKING 2 lớp, form unisex cho nam...",235.000₫,https://tka.tiki.vn/pixel/pixel?data=vCeOAtQL3...,3,-44%,Đã bán 80,aokhoacnu
3,"Áo khoác gió cách nhiệt GOKING phối viền, mũ d...",255.000₫,https://tka.tiki.vn/pixel/pixel?data=NSKqu_ucy...,4,-12%,Đã bán 102,aokhoacnu
4,Áo Khoác Nữ Măng Tô Dạ,550.000₫,https://tka.tiki.vn/pixel/pixel?data=RDgl41FL1...,5,NaN,Đã bán 88,aokhoacnu
...,...,...,...,...,...,...,...
35,NaN,NaN,https://tiki.vn/hang-san-ao-khoac-phao-nu-ngan...,36,NaN,NaN,aokhoacnu
36,"Áo len nữ, áo len dài tay cổ tròn thu đông AL46",219.000₫,https://tiki.vn/ao-len-nu-ao-len-dai-tay-co-tr...,37,NaN,NaN,aokhoacnu
37,Áo Khoác Phao Nữ 3 Lớp Chần Bông Lông Vũ Cực Ấ...,208.000₫,https://tiki.vn/ao-khoac-phao-nu-3-lop-chan-bo...,38,NaN,Đã bán 1,aokhoacnu
38,(HÀNG SẴN) Áo Khoác Phao Lông Vũ Dáng Dài Phon...,745.000₫,https://tiki.vn/hang-san-ao-khoac-phao-long-vu...,39,NaN,NaN,aokhoacnu
39,Set áo vest blazer nữ ngắn tay 2 túi hàng thiế...,476.000,https://tiki.vn/set-ao-vest-blazer-nu-ngan-tay...,40,NaN,NaN,aokhoacnu

1. Xử lý dữ liệu

In [5]:
df_all = df_all.drop('index', axis=1)

In [6]:
df_all.dropna(subset=['sales'], inplace=True)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales,category
0,"Áo khoác gió cách nhiệt GOKING, form unisex ch...",235.000₫,https://tka.tiki.vn/pixel/pixel?data=hdk2OleDq...,-44%,Đã bán 89,aokhoacnu
1,Áo vest nữ blazer hàn quốc [HÀNG CAO CẤP] form...,299.000₫,https://tka.tiki.vn/pixel/pixel?data=ozddpQdWx...,-44%,Đã bán 97,aokhoacnu
2,"Áo khoác gió GOKING 2 lớp, form unisex cho nam...",235.000₫,https://tka.tiki.vn/pixel/pixel?data=vCeOAtQL3...,-44%,Đã bán 80,aokhoacnu
3,"Áo khoác gió cách nhiệt GOKING phối viền, mũ d...",255.000₫,https://tka.tiki.vn/pixel/pixel?data=NSKqu_ucy...,-12%,Đã bán 102,aokhoacnu
4,Áo Khoác Nữ Măng Tô Dạ,550.000₫,https://tka.tiki.vn/pixel/pixel?data=RDgl41FL1...,NaN,Đã bán 88,aokhoacnu
...,...,...,...,...,...,...
852,"Áo Khoác Nữ Chống Nắng , Chống Nước Kiểu Dáng ...",139.000₫,https://tiki.vn/ao-khoac-nu-chong-nang-chong-n...,NaN,Đã bán 38,aokhoacnu
853,Áo len tay bồng nữ kiểu cổ lọ ngắn tay dáng ôm...,105.000₫,https://tiki.vn/ao-len-tay-bong-nu-kieu-co-lo-...,NaN,Đã bán 38,aokhoacnu
854,"Áo blazer- Áo vest nữ công sở, chất liệu đũi, ...",179.000₫,https://tiki.vn/ao-blazer-ao-vest-nu-cong-so-c...,NaN,Đã bán 2,aokhoacnu
855,áo khoác chống nắng cao cấp [nón rời trơn,165.000₫,https://tiki.vn/ao-khoac-chong-nang-cao-cap-no...,NaN,Đã bán 6,aokhoacnu
856,Áo Khoác Phao Nữ 3 Lớp Chần Bông Lông Vũ Cực Ấ...,208.000₫,https://tiki.vn/ao-khoac-phao-nu-3-lop-chan-bo...,NaN,Đã bán 1,aokhoacnu

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0      235000
1      299000
2      235000
3      255000
4      550000
        ...
852    139000
853    105000
854    179000
855    165000
856    208000
Name: price, Length: 857, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0       89.0
1       97.0
2       80.0
3      102.0
4       88.0
       ...
852     38.0
853     38.0
854      2.0
855      6.0
856      1.0
Name: sales, Length: 857, dtype: float64

In [11]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0      20915000.0
1      29003000.0
2      18800000.0
3      26010000.0
4      48400000.0
          ...
852     5282000.0
853     3990000.0
854      358000.0
855      990000.0
856      208000.0
Name: revenue, Length: 857, dtype: float64

In [12]:
total = df_all["revenue"].sum()

In [13]:
print("Tổng doanh số aokhoacnu: ", total)
print("So mat hang da ban: ", len(df_all["title"])) # san pham da ban
print("So san pham da ban: ", df_all["sales"].sum()) # san pham co luot ban

Tổng doanh số aokhoacnu:  4028832654.0
So mat hang da ban:  857
So san pham da ban:  18001.0

In [14]:
df_all

,title,price,link_item,discount,sales,category,revenue
0,"Áo khoác gió cách nhiệt GOKING, form unisex ch...",235000,https://tka.tiki.vn/pixel/pixel?data=hdk2OleDq...,-44%,89.0,aokhoacnu,20915000.0
1,Áo vest nữ blazer hàn quốc [HÀNG CAO CẤP] form...,299000,https://tka.tiki.vn/pixel/pixel?data=ozddpQdWx...,-44%,97.0,aokhoacnu,29003000.0
2,"Áo khoác gió GOKING 2 lớp, form unisex cho nam...",235000,https://tka.tiki.vn/pixel/pixel?data=vCeOAtQL3...,-44%,80.0,aokhoacnu,18800000.0
3,"Áo khoác gió cách nhiệt GOKING phối viền, mũ d...",255000,https://tka.tiki.vn/pixel/pixel?data=NSKqu_ucy...,-12%,102.0,aokhoacnu,26010000.0
4,Áo Khoác Nữ Măng Tô Dạ,550000,https://tka.tiki.vn/pixel/pixel?data=RDgl41FL1...,NaN,88.0,aokhoacnu,48400000.0
...,...,...,...,...,...,...,...
852,"Áo Khoác Nữ Chống Nắng , Chống Nước Kiểu Dáng ...",139000,https://tiki.vn/ao-khoac-nu-chong-nang-chong-n...,NaN,38.0,aokhoacnu,5282000.0
853,Áo len tay bồng nữ kiểu cổ lọ ngắn tay dáng ôm...,105000,https://tiki.vn/ao-len-tay-bong-nu-kieu-co-lo-...,NaN,38.0,aokhoacnu,3990000.0
854,"Áo blazer- Áo vest nữ công sở, chất liệu đũi, ...",179000,https://tiki.vn/ao-blazer-ao-vest-nu-cong-so-c...,NaN,2.0,aokhoacnu,358000.0
855,áo khoác chống nắng cao cấp [nón rời trơn,165000,https://tiki.vn/ao-khoac-chong-nang-cao-cap-no...,NaN,6.0,aokhoacnu,990000.0
856,Áo Khoác Phao Nữ 3 Lớp Chần Bông Lông Vũ Cực Ấ...,208000,https://tiki.vn/ao-khoac-phao-nu-3-lop-chan-bo...,NaN,1.0,aokhoacnu,208000.0

In [15]:
df_all.to_csv("tk_aokhoacnu_all_ed.csv")