In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_160124(12htrua)\dienthoai_maytinhbang\dienthoai"
os.listdir(path)

['.ipynb_checkpoints',
 'oppo',
 'samsung',
 'tk_smartphone.csv',
 'tk_smartphone.ipynb',
 'tk_smartphone_all.ipynb',
 'tk_smartphone_npage.ipynb',
 'tk_smartphone_t10.csv',
 'tk_smartphone_t11.csv',
 'tk_smartphone_t12.csv',
 'tk_smartphone_t2.csv',
 'tk_smartphone_t3.csv',
 'tk_smartphone_t4.csv',
 'tk_smartphone_t5.csv',
 'tk_smartphone_t6.csv',
 'tk_smartphone_t7.csv',
 'tk_smartphone_t8.csv',
 'tk_smartphone_t9.csv',
 'xiaomi']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_smartphone_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales,category
0,Điện thoại Samsung Galaxy Z Flip 4 (8GB/256GB),10.990.000₫,https://tka.tiki.vn/pixel/pixel?data=skkKuGzPa...,1,-58%,Đã bán 98,smartphone
1,Điện thoại vivo Y22s (8GB - 128GB) - Hàng Chín...,4.990.000₫,https://tka.tiki.vn/pixel/pixel?data=_38YYraAT...,2,-17%,Đã bán 4,smartphone
2,[MỚI] Điện thoại vivo Y17s - Hàng chính hãng -...,3.790.000₫,https://tka.tiki.vn/pixel/pixel?data=VYmUlDn-_...,3,-5%,Đã bán 5,smartphone
3,Điện thoại VIVO Y02t - Hàng chính hãng - Pin K...,2.790.000₫,https://tka.tiki.vn/pixel/pixel?data=HnPLym85E...,4,-15%,Đã bán 3,smartphone
4,[Mới] Điện thoại vivo V29e 5G (8GB/256GB) - Hà...,8.690.000₫,https://tka.tiki.vn/pixel/pixel?data=GhwxJhmkS...,5,-3%,Đã bán 2,smartphone
...,...,...,...,...,...,...,...
35,NaN,NaN,https://tiki.vn/dien-thoai-samsung-galaxy-a04s...,36,NaN,NaN,smartphone
36,Điện Thoại Samsung Galaxy A04e - Hàng Chính Hãng,2.340.000₫,https://tiki.vn/dien-thoai-samsung-galaxy-a04e...,37,NaN,NaN,smartphone
37,Điện thoại Samsung Galaxy Z Fold 4 5G 512GB Ke...,42.000.000₫,https://tiki.vn/dien-thoai-samsung-galaxy-z-fo...,38,NaN,NaN,smartphone
38,Điện thoại Samsung Galaxy A04 32GB - Hàng chín...,2.400.000₫,https://tiki.vn/dien-thoai-samsung-galaxy-a04-...,39,NaN,NaN,smartphone
39,Điện thoại Samsung Galaxy A04e (3GB/32GB) - Hà...,2.325.000₫,https://tiki.vn/dien-thoai-samsung-galaxy-a04e...,40,NaN,NaN,smartphone

1. Xử lý dữ liệu

In [5]:
df_all = df_all.drop('index', axis=1)

In [6]:
df_all.dropna(subset=['sales'], inplace=True)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales,category
0,Điện thoại Samsung Galaxy Z Flip 4 (8GB/256GB),10.990.000₫,https://tka.tiki.vn/pixel/pixel?data=skkKuGzPa...,-58%,Đã bán 98,smartphone
1,Điện thoại vivo Y22s (8GB - 128GB) - Hàng Chín...,4.990.000₫,https://tka.tiki.vn/pixel/pixel?data=_38YYraAT...,-17%,Đã bán 4,smartphone
2,[MỚI] Điện thoại vivo Y17s - Hàng chính hãng -...,3.790.000₫,https://tka.tiki.vn/pixel/pixel?data=VYmUlDn-_...,-5%,Đã bán 5,smartphone
3,Điện thoại VIVO Y02t - Hàng chính hãng - Pin K...,2.790.000₫,https://tka.tiki.vn/pixel/pixel?data=HnPLym85E...,-15%,Đã bán 3,smartphone
4,[Mới] Điện thoại vivo V29e 5G (8GB/256GB) - Hà...,8.690.000₫,https://tka.tiki.vn/pixel/pixel?data=GhwxJhmkS...,-3%,Đã bán 2,smartphone
...,...,...,...,...,...,...
179,Điện Thoại Realme C51 3GB/64GB - Hàng Chính Hãng,2.699.000₫,https://tiki.vn/dien-thoai-realme-c51-3gb-64gb...,NaN,Đã bán 1,smartphone
180,Điện thoại Xiaomi Redmi 9A 2GB/32GB Xám - Hàng...,2.088.000₫,https://tiki.vn/dien-thoai-xiaomi-redmi-9a-2gb...,NaN,Đã bán 1,smartphone
181,Điện Thoại Samsung Galaxy A14 5G (4GB/128GB) -...,5.000.000₫,https://tiki.vn/dien-thoai-samsung-galaxy-a14-...,NaN,Đã bán 1,smartphone
182,Điện thoại TECNO Spark 6 Go (4GB/64GB) - Hàng ...,2.559.000₫,https://tiki.vn/dien-thoai-tecno-spark-6-go-4g...,NaN,Đã bán 4,smartphone
183,Điện thoại OPPO A57 4GB/128GB Đen - Hàng chính...,3.850.000₫,https://tiki.vn/dien-thoai-oppo-a57-4gb-128gb-...,NaN,Đã bán 1,smartphone

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0      10990000
1       4990000
2       3790000
3       2790000
4       8690000
         ...
179     2699000
180     2088000
181     5000000
182     2559000
183     3850000
Name: price, Length: 184, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0      98.0
1       4.0
2       5.0
3       3.0
4       2.0
       ...
179     1.0
180     1.0
181     1.0
182     4.0
183     1.0
Name: sales, Length: 184, dtype: float64

In [11]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0      1.077020e+09
1      1.996000e+07
2      1.895000e+07
3      8.370000e+06
4      1.738000e+07
           ...
179    2.699000e+06
180    2.088000e+06
181    5.000000e+06
182    1.023600e+07
183    3.850000e+06
Name: revenue, Length: 184, dtype: float64

In [12]:
total = df_all["revenue"].sum()

In [13]:
print("Tổng doanh số smartphone: ", total)
print("So mat hang da ban: ", len(df_all["title"])) # san pham da ban
print("So san pham da ban: ", df_all["sales"].sum()) # san pham co luot ban

Tổng doanh số smartphone:  288214214000.0
So mat hang da ban:  184
So san pham da ban:  34693.0

In [14]:
df_all

,title,price,link_item,discount,sales,category,revenue
0,Điện thoại Samsung Galaxy Z Flip 4 (8GB/256GB),10990000,https://tka.tiki.vn/pixel/pixel?data=skkKuGzPa...,-58%,98.0,smartphone,1.077020e+09
1,Điện thoại vivo Y22s (8GB - 128GB) - Hàng Chín...,4990000,https://tka.tiki.vn/pixel/pixel?data=_38YYraAT...,-17%,4.0,smartphone,1.996000e+07
2,[MỚI] Điện thoại vivo Y17s - Hàng chính hãng -...,3790000,https://tka.tiki.vn/pixel/pixel?data=VYmUlDn-_...,-5%,5.0,smartphone,1.895000e+07
3,Điện thoại VIVO Y02t - Hàng chính hãng - Pin K...,2790000,https://tka.tiki.vn/pixel/pixel?data=HnPLym85E...,-15%,3.0,smartphone,8.370000e+06
4,[Mới] Điện thoại vivo V29e 5G (8GB/256GB) - Hà...,8690000,https://tka.tiki.vn/pixel/pixel?data=GhwxJhmkS...,-3%,2.0,smartphone,1.738000e+07
...,...,...,...,...,...,...,...
179,Điện Thoại Realme C51 3GB/64GB - Hàng Chính Hãng,2699000,https://tiki.vn/dien-thoai-realme-c51-3gb-64gb...,NaN,1.0,smartphone,2.699000e+06
180,Điện thoại Xiaomi Redmi 9A 2GB/32GB Xám - Hàng...,2088000,https://tiki.vn/dien-thoai-xiaomi-redmi-9a-2gb...,NaN,1.0,smartphone,2.088000e+06
181,Điện Thoại Samsung Galaxy A14 5G (4GB/128GB) -...,5000000,https://tiki.vn/dien-thoai-samsung-galaxy-a14-...,NaN,1.0,smartphone,5.000000e+06
182,Điện thoại TECNO Spark 6 Go (4GB/64GB) - Hàng ...,2559000,https://tiki.vn/dien-thoai-tecno-spark-6-go-4g...,NaN,4.0,smartphone,1.023600e+07
183,Điện thoại OPPO A57 4GB/128GB Đen - Hàng chính...,3850000,https://tiki.vn/dien-thoai-oppo-a57-4gb-128gb-...,NaN,1.0,smartphone,3.850000e+06

In [15]:
df_all.to_csv("tk_smartphone_all_ed.csv")