In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_180124(12htrua) - Copy (4)\thoitrangnam\aosomi"
os.listdir(path)

['.ipynb_checkpoints',
 'tk_aosomi.csv',
 'tk_aosomi_all.ipynb',
 'tk_ttnam_aosomi.ipynb',
 'tk_ttnam_aosomi_npage.ipynb',
 'tk_ttnam_aosomi_t10.csv',
 'tk_ttnam_aosomi_t11.csv',
 'tk_ttnam_aosomi_t12.csv',
 'tk_ttnam_aosomi_t13.csv',
 'tk_ttnam_aosomi_t14.csv',
 'tk_ttnam_aosomi_t15.csv',
 'tk_ttnam_aosomi_t16.csv',
 'tk_ttnam_aosomi_t17.csv',
 'tk_ttnam_aosomi_t18.csv',
 'tk_ttnam_aosomi_t19.csv',
 'tk_ttnam_aosomi_t2.csv',
 'tk_ttnam_aosomi_t20.csv',
 'tk_ttnam_aosomi_t21.csv',
 'tk_ttnam_aosomi_t22.csv',
 'tk_ttnam_aosomi_t23.csv',
 'tk_ttnam_aosomi_t24.csv',
 'tk_ttnam_aosomi_t25.csv',
 'tk_ttnam_aosomi_t26.csv',
 'tk_ttnam_aosomi_t27.csv',
 'tk_ttnam_aosomi_t28.csv',
 'tk_ttnam_aosomi_t29.csv',
 'tk_ttnam_aosomi_t3.csv',
 'tk_ttnam_aosomi_t30.csv',
 'tk_ttnam_aosomi_t31.csv',
 'tk_ttnam_aosomi_t32.csv',
 'tk_ttnam_aosomi_t33.csv',
 'tk_ttnam_aosomi_t34.csv',
 'tk_ttnam_aosomi_t35.csv',
 'tk_ttnam_aosomi_t36.csv',
 'tk_ttnam_aosomi_t37.csv',
 'tk_ttnam_aosomi_t38.csv',
 'tk_ttnam_aosomi_t39.csv',
 'tk_ttnam_aosomi_t4.csv',
 'tk_ttnam_aosomi_t40.csv',
 'tk_ttnam_aosomi_t41.csv',
 'tk_ttnam_aosomi_t42.csv',
 'tk_ttnam_aosomi_t43.csv',
 'tk_ttnam_aosomi_t44.csv',
 'tk_ttnam_aosomi_t45.csv',
 'tk_ttnam_aosomi_t46.csv',
 'tk_ttnam_aosomi_t47.csv',
 'tk_ttnam_aosomi_t48.csv',
 'tk_ttnam_aosomi_t49.csv',
 'tk_ttnam_aosomi_t5.csv',
 'tk_ttnam_aosomi_t50.csv',
 'tk_ttnam_aosomi_t6.csv',
 'tk_ttnam_aosomi_t7.csv',
 'tk_ttnam_aosomi_t8.csv',
 'tk_ttnam_aosomi_t9.csv']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_aosomi_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales,category
0,Áo sơ mi nam cổ trụ cài hêt cúc tay dài vài kh...,108.000₫,https://tka.tiki.vn/pixel/pixel?data=unhbbDCbo...,1,-41%,Đã bán 2,aosomi
1,Áo sơ mi nam vải cotton mềm không nhăn-Quà tặng,108.000₫,https://tka.tiki.vn/pixel/pixel?data=TK-xaJULX...,2,-35%,Đã bán 32,aosomi
2,Áo sơ mi nam dài tay màu tím,159.000₫,https://tka.tiki.vn/pixel/pixel?data=v8KlS3IS1...,3,-31%,Đã bán 23,aosomi
3,Áo sơ mi nam cổ lãnh tụ dài tay màu xanh biển ...,159.000₫,https://tka.tiki.vn/pixel/pixel?data=Ct5IQeAIg...,4,-35%,Đã bán 27,aosomi
4,Áo sơ mi nam dài tay kẻ caro trắng đen,159.000₫,https://tka.tiki.vn/pixel/pixel?data=kkPvjIemp...,5,-41%,Đã bán 14,aosomi
...,...,...,...,...,...,...,...
35,Áo sơ mi nam ngắn tay a,195.000₫,https://tiki.vn/ao-so-mi-nam-ngan-tay-a-p25161...,36,NaN,Đã bán 3,aosomi
36,Áo Sơ Mi Nam Tay Ngắn Mẫu 1,228.000,https://tiki.vn/a-o-so-mi-nam-tay-ngan-ma-u-1-...,37,NaN,NaN,aosomi
37,NaN,NaN,https://tiki.vn/ao-so-mi-trang-nam-hoa-tiet-ho...,38,NaN,NaN,aosomi
38,Áo Sơ Mi Nam Họa Tiết Vải Lụa Hàn Không Nhăn H...,299.000₫,https://tiki.vn/ao-so-mi-nam-hoa-tiet-vai-lua-...,39,NaN,Đã bán 4,aosomi
39,Áo Sơ Mi Form Rộng Unisex Nam Nữ Tay Dài Hàn Q...,92.000₫,https://tiki.vn/ao-so-mi-form-rong-unisex-nam-...,40,NaN,Đã bán 62,aosomi

1. Xử lý dữ liệu

In [5]:
df_all = df_all.drop('index', axis=1)

In [6]:
df_all.dropna(subset=['sales'], inplace=True)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales,category
0,Áo sơ mi nam cổ trụ cài hêt cúc tay dài vài kh...,108.000₫,https://tka.tiki.vn/pixel/pixel?data=unhbbDCbo...,-41%,Đã bán 2,aosomi
1,Áo sơ mi nam vải cotton mềm không nhăn-Quà tặng,108.000₫,https://tka.tiki.vn/pixel/pixel?data=TK-xaJULX...,-35%,Đã bán 32,aosomi
2,Áo sơ mi nam dài tay màu tím,159.000₫,https://tka.tiki.vn/pixel/pixel?data=v8KlS3IS1...,-31%,Đã bán 23,aosomi
3,Áo sơ mi nam cổ lãnh tụ dài tay màu xanh biển ...,159.000₫,https://tka.tiki.vn/pixel/pixel?data=Ct5IQeAIg...,-35%,Đã bán 27,aosomi
4,Áo sơ mi nam dài tay kẻ caro trắng đen,159.000₫,https://tka.tiki.vn/pixel/pixel?data=kkPvjIemp...,-41%,Đã bán 14,aosomi
...,...,...,...,...,...,...
838,Áo sơ mi ngắn tay nam Columbia Pine Canyon - 2...,545.000,https://tiki.vn/ao-so-mi-ngan-tay-nam-columbia...,NaN,Đã bán 1,aosomi
839,"Áo sơ mi nam, áo sơ mi cộc tay phối màu trẻ tr...",199.000₫,https://tiki.vn/ao-so-mi-nam-ao-so-mi-coc-tay-...,NaN,Đã bán 2,aosomi
840,Áo sơ mi nam ngắn tay a,195.000₫,https://tiki.vn/ao-so-mi-nam-ngan-tay-a-p25161...,NaN,Đã bán 3,aosomi
841,Áo Sơ Mi Nam Họa Tiết Vải Lụa Hàn Không Nhăn H...,299.000₫,https://tiki.vn/ao-so-mi-nam-hoa-tiet-vai-lua-...,NaN,Đã bán 4,aosomi
842,Áo Sơ Mi Form Rộng Unisex Nam Nữ Tay Dài Hàn Q...,92.000₫,https://tiki.vn/ao-so-mi-form-rong-unisex-nam-...,NaN,Đã bán 62,aosomi

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0      108000
1      108000
2      159000
3      159000
4      159000
        ...
838    545000
839    199000
840    195000
841    299000
842     92000
Name: price, Length: 843, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0       2.0
1      32.0
2      23.0
3      27.0
4      14.0
       ...
838     1.0
839     2.0
840     3.0
841     4.0
842    62.0
Name: sales, Length: 843, dtype: float64

In [11]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0       216000.0
1      3456000.0
2      3657000.0
3      4293000.0
4      2226000.0
         ...
838     545000.0
839     398000.0
840     585000.0
841    1196000.0
842    5704000.0
Name: revenue, Length: 843, dtype: float64

In [12]:
total = df_all["revenue"].sum()

In [13]:
print("Tổng doanh số aosomi: ", total)
print("So mat hang da ban: ", len(df_all["title"])) # san pham da ban
print("So san pham da ban: ", df_all["sales"].sum()) # san pham co luot ban

Tổng doanh số aosomi:  3678324680.0
So mat hang da ban:  843
So san pham da ban:  22766.0

In [14]:
df_all

,title,price,link_item,discount,sales,category,revenue
0,Áo sơ mi nam cổ trụ cài hêt cúc tay dài vài kh...,108000,https://tka.tiki.vn/pixel/pixel?data=unhbbDCbo...,-41%,2.0,aosomi,216000.0
1,Áo sơ mi nam vải cotton mềm không nhăn-Quà tặng,108000,https://tka.tiki.vn/pixel/pixel?data=TK-xaJULX...,-35%,32.0,aosomi,3456000.0
2,Áo sơ mi nam dài tay màu tím,159000,https://tka.tiki.vn/pixel/pixel?data=v8KlS3IS1...,-31%,23.0,aosomi,3657000.0
3,Áo sơ mi nam cổ lãnh tụ dài tay màu xanh biển ...,159000,https://tka.tiki.vn/pixel/pixel?data=Ct5IQeAIg...,-35%,27.0,aosomi,4293000.0
4,Áo sơ mi nam dài tay kẻ caro trắng đen,159000,https://tka.tiki.vn/pixel/pixel?data=kkPvjIemp...,-41%,14.0,aosomi,2226000.0
...,...,...,...,...,...,...,...
838,Áo sơ mi ngắn tay nam Columbia Pine Canyon - 2...,545000,https://tiki.vn/ao-so-mi-ngan-tay-nam-columbia...,NaN,1.0,aosomi,545000.0
839,"Áo sơ mi nam, áo sơ mi cộc tay phối màu trẻ tr...",199000,https://tiki.vn/ao-so-mi-nam-ao-so-mi-coc-tay-...,NaN,2.0,aosomi,398000.0
840,Áo sơ mi nam ngắn tay a,195000,https://tiki.vn/ao-so-mi-nam-ngan-tay-a-p25161...,NaN,3.0,aosomi,585000.0
841,Áo Sơ Mi Nam Họa Tiết Vải Lụa Hàn Không Nhăn H...,299000,https://tiki.vn/ao-so-mi-nam-hoa-tiet-vai-lua-...,NaN,4.0,aosomi,1196000.0
842,Áo Sơ Mi Form Rộng Unisex Nam Nữ Tay Dài Hàn Q...,92000,https://tiki.vn/ao-so-mi-form-rong-unisex-nam-...,NaN,62.0,aosomi,5704000.0

In [15]:
df_all.to_csv("tk_aosomi_all_ed.csv")