In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_190124(12hdem) - Copy (5)\dienthoai_maytinhbang\maydocsach"
os.listdir(path)

['.ipynb_checkpoints',
 'tk_dienthoai_maytinhbang_maydocsach.ipynb',
 'tk_dienthoai_maytinhbang_maydocsach_t2.ipynb',
 'tk_maydocsach_all.ipynb',
 'tk_maydocsach_t1.csv',
 'tk_maydocsach_t2.csv']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_maydocsach_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales,category
0,Máy đọc sách New Kindle 11th 2022 (16GB) - Hàn...,2.680.000₫,https://tka.tiki.vn/pixel/pixel?data=qBLvOd8Lc...,1,-10%,Đã bán 3,maydocsach
1,Máy đọc sách All New Kindle Paperwhite 5 (11th...,3.330.000₫,https://tka.tiki.vn/pixel/pixel?data=0P1Byb5kD...,2,-9%,Đã bán 3,maydocsach
2,Máy đọc sách Kindle 2022 (11th) - All new kind...,2.680.000₫,https://tka.tiki.vn/pixel/pixel?data=4tQaTIa2R...,3,-14%,Đã bán 8,maydocsach
3,Máy đọc sách Kindle Paperwhite 5 (8GB) - Hàng ...,3.440.000₫,https://tka.tiki.vn/pixel/pixel?data=WbNtuSe5w...,4,-16%,NaN,maydocsach
4,Combo Máy đọc sách All New Kindle Paperwhite 5...,3.380.000₫,https://tka.tiki.vn/pixel/pixel?data=OLM9DGkLY...,5,-10%,Đã bán 4,maydocsach
...,...,...,...,...,...,...,...
13,Combo Máy đọc sách All New Kindle Paperwhite 5...,3.790.000₫,https://tka.tiki.vn/pixel/pixel?data=IfYGuFPCT...,14,NaN,Đã bán 3,maydocsach
14,Máy đọc sách Kindle Scribe - Hàng nhập khẩu,12.590.000₫,https://tka.tiki.vn/pixel/pixel?data=XkCo_yCO-...,15,NaN,Đã bán 5,maydocsach
15,Bút học tiếng Anh i-Tek Venus 2023 (HÀNG CHÍNH...,560.000₫,https://tiki.vn/but-hoc-tieng-anh-i-tek-chinh-...,16,NaN,Đã bán 1,maydocsach
16,Máy đọc sách All new Paperwhite Gen 5 (11th) m...,3.490.000₫,https://tiki.vn/may-doc-sach-all-new-paperwhit...,17,NaN,NaN,maydocsach
17,Máy đọc sách Kobo Nia - Hàng nhập khẩu,2.680.000₫,https://tiki.vn/may-doc-sach-kobo-nia-p1487018...,18,NaN,NaN,maydocsach

1. Xử lý dữ liệu

In [5]:
df_all = df_all.drop('index', axis=1)

In [6]:
df_all.dropna(subset=['sales'], inplace=True)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales,category
0,Máy đọc sách New Kindle 11th 2022 (16GB) - Hàn...,2.680.000₫,https://tka.tiki.vn/pixel/pixel?data=qBLvOd8Lc...,-10%,Đã bán 3,maydocsach
1,Máy đọc sách All New Kindle Paperwhite 5 (11th...,3.330.000₫,https://tka.tiki.vn/pixel/pixel?data=0P1Byb5kD...,-9%,Đã bán 3,maydocsach
2,Máy đọc sách Kindle 2022 (11th) - All new kind...,2.680.000₫,https://tka.tiki.vn/pixel/pixel?data=4tQaTIa2R...,-14%,Đã bán 8,maydocsach
3,Combo Máy đọc sách All New Kindle Paperwhite 5...,3.380.000₫,https://tka.tiki.vn/pixel/pixel?data=OLM9DGkLY...,-10%,Đã bán 4,maydocsach
4,Máy đọc sách New Kindle 11th 2022 (16GB) - Hàn...,3.190.000₫,https://tiki.vn/may-doc-sach-new-kindle-11th-2...,-3%,Đã bán 502,maydocsach
...,...,...,...,...,...,...
60,Máy đọc sách Kindle 2022 (11th) - All new kind...,2.680.000₫,https://tka.tiki.vn/pixel/pixel?data=10IVYYiNv...,NaN,Đã bán 8,maydocsach
61,Máy đọc sách All New Kindle Paperwhite 5 (11th...,3.330.000₫,https://tka.tiki.vn/pixel/pixel?data=D40TAqQTW...,NaN,Đã bán 3,maydocsach
62,Combo Máy đọc sách All New Kindle Paperwhite 5...,3.790.000₫,https://tka.tiki.vn/pixel/pixel?data=IfYGuFPCT...,NaN,Đã bán 3,maydocsach
63,Máy đọc sách Kindle Scribe - Hàng nhập khẩu,12.590.000₫,https://tka.tiki.vn/pixel/pixel?data=XkCo_yCO-...,NaN,Đã bán 5,maydocsach
64,Bút học tiếng Anh i-Tek Venus 2023 (HÀNG CHÍNH...,560.000₫,https://tiki.vn/but-hoc-tieng-anh-i-tek-chinh-...,NaN,Đã bán 1,maydocsach

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0      2680000
1      3330000
2      2680000
3      3380000
4      3190000
        ...
60     2680000
61     3330000
62     3790000
63    12590000
64      560000
Name: price, Length: 65, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0       3.0
1       3.0
2       8.0
3       4.0
4     502.0
      ...
60      8.0
61      3.0
62      3.0
63      5.0
64      1.0
Name: sales, Length: 65, dtype: float64

In [11]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0     8.040000e+06
1     9.990000e+06
2     2.144000e+07
3     1.352000e+07
4     1.601380e+09
          ...
60    2.144000e+07
61    9.990000e+06
62    1.137000e+07
63    6.295000e+07
64    5.600000e+05
Name: revenue, Length: 65, dtype: float64

In [12]:
total = df_all["revenue"].sum()

In [13]:
print("Tổng doanh số maydocsach: ", total)
print("So mat hang da ban: ", len(df_all["title"])) # san pham da ban
print("So san pham da ban: ", df_all["sales"].sum()) # san pham co luot ban

Tổng doanh số maydocsach:  24006496424.0
So mat hang da ban:  65
So san pham da ban:  6496.0

In [14]:
df_all

,title,price,link_item,discount,sales,category,revenue
0,Máy đọc sách New Kindle 11th 2022 (16GB) - Hàn...,2680000,https://tka.tiki.vn/pixel/pixel?data=qBLvOd8Lc...,-10%,3.0,maydocsach,8.040000e+06
1,Máy đọc sách All New Kindle Paperwhite 5 (11th...,3330000,https://tka.tiki.vn/pixel/pixel?data=0P1Byb5kD...,-9%,3.0,maydocsach,9.990000e+06
2,Máy đọc sách Kindle 2022 (11th) - All new kind...,2680000,https://tka.tiki.vn/pixel/pixel?data=4tQaTIa2R...,-14%,8.0,maydocsach,2.144000e+07
3,Combo Máy đọc sách All New Kindle Paperwhite 5...,3380000,https://tka.tiki.vn/pixel/pixel?data=OLM9DGkLY...,-10%,4.0,maydocsach,1.352000e+07
4,Máy đọc sách New Kindle 11th 2022 (16GB) - Hàn...,3190000,https://tiki.vn/may-doc-sach-new-kindle-11th-2...,-3%,502.0,maydocsach,1.601380e+09
...,...,...,...,...,...,...,...
60,Máy đọc sách Kindle 2022 (11th) - All new kind...,2680000,https://tka.tiki.vn/pixel/pixel?data=10IVYYiNv...,NaN,8.0,maydocsach,2.144000e+07
61,Máy đọc sách All New Kindle Paperwhite 5 (11th...,3330000,https://tka.tiki.vn/pixel/pixel?data=D40TAqQTW...,NaN,3.0,maydocsach,9.990000e+06
62,Combo Máy đọc sách All New Kindle Paperwhite 5...,3790000,https://tka.tiki.vn/pixel/pixel?data=IfYGuFPCT...,NaN,3.0,maydocsach,1.137000e+07
63,Máy đọc sách Kindle Scribe - Hàng nhập khẩu,12590000,https://tka.tiki.vn/pixel/pixel?data=XkCo_yCO-...,NaN,5.0,maydocsach,6.295000e+07
64,Bút học tiếng Anh i-Tek Venus 2023 (HÀNG CHÍNH...,560000,https://tiki.vn/but-hoc-tieng-anh-i-tek-chinh-...,NaN,1.0,maydocsach,5.600000e+05

In [15]:
df_all.to_csv("tk_maydocsach_all_ed.csv")