In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\crawl_160124(12htrua)\thoitrangnam\aoni"
os.listdir(path)

['tk_aoni.csv',
 'tk_aoni_all.ipynb',
 'tk_ttn_an.ipynb',
 'tk_ttn_an_npage.ipynb',
 'tk_ttn_aoni_t10.csv',
 'tk_ttn_aoni_t11.csv',
 'tk_ttn_aoni_t12.csv',
 'tk_ttn_aoni_t13.csv',
 'tk_ttn_aoni_t14.csv',
 'tk_ttn_aoni_t15.csv',
 'tk_ttn_aoni_t16.csv',
 'tk_ttn_aoni_t17.csv',
 'tk_ttn_aoni_t18.csv',
 'tk_ttn_aoni_t19.csv',
 'tk_ttn_aoni_t2.csv',
 'tk_ttn_aoni_t20.csv',
 'tk_ttn_aoni_t3.csv',
 'tk_ttn_aoni_t4.csv',
 'tk_ttn_aoni_t5.csv',
 'tk_ttn_aoni_t6.csv',
 'tk_ttn_aoni_t7.csv',
 'tk_ttn_aoni_t8.csv',
 'tk_ttn_aoni_t9.csv']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_aoni_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales,category
0,"Áo Sweater Nam 5S FASHION POSITIVE, Chất Nỉ Co...",285.000₫,https://tka.tiki.vn/pixel/pixel?data=IpxDi5rpF...,1,-35%,NaN,aoni
1,"Áo Sweater Nỉ Nam 5S FASHION, Chất Cotton Mềm ...",199.000₫,https://tka.tiki.vn/pixel/pixel?data=LdvL4XK5j...,2,-40%,Đã bán 3,aoni
2,"Áo Sweater Nam 5S FASHION Chất Nỉ Dày Dặn, Pho...",266.000₫,https://tka.tiki.vn/pixel/pixel?data=RqqRj3DGo...,3,-35%,Đã bán 1,aoni
3,"Áo Sweater Nam 5S FASHION Chất Nỉ Cotton, Phom...",253.000₫,https://tka.tiki.vn/pixel/pixel?data=F4p88dMyT...,4,-35%,Đã bán 1,aoni
4,"Áo Nỉ Nam Cổ Tròn 5S FASHION Nhiều Màu, Vải Co...",259.000₫,https://tka.tiki.vn/pixel/pixel?data=vMU2NwQIo...,5,-35%,Đã bán 2,aoni
...,...,...,...,...,...,...,...
35,NaN,NaN,https://tiki.vn/ao-ni-nam-nu-chat-lieu-ni-day-...,36,NaN,NaN,aoni
36,Áo sweater LOGO under Hà Nội Form Rộng Áo nỉ d...,250.000₫,https://tiki.vn/ao-sweater-logo-under-ha-noi-f...,37,NaN,NaN,aoni
37,"Áo nỉ nam, nữ chất liệu nỉ dày dặn chất lượng,...",348.000₫,https://tiki.vn/ao-ni-nam-nu-chat-lieu-ni-day-...,38,NaN,NaN,aoni
38,Áo len nam cổ lọ vàng cao cấp,520.000₫,https://tiki.vn/ao-len-nam-co-lo-vang-cao-cap-...,39,NaN,NaN,aoni
39,Áo len nam cổ lọ visco 2020 - xuongaolen.com,220.000,https://tiki.vn/ao-len-nam-co-lo-visco-2020-xu...,40,NaN,Đã bán 1,aoni

1. Xử lý dữ liệu

In [5]:
df_all = df_all.drop('index', axis=1)

In [6]:
df_all.dropna(subset=['sales'], inplace=True)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales,category
0,"Áo Sweater Nỉ Nam 5S FASHION, Chất Cotton Mềm ...",199.000₫,https://tka.tiki.vn/pixel/pixel?data=LdvL4XK5j...,-40%,Đã bán 3,aoni
1,"Áo Sweater Nam 5S FASHION Chất Nỉ Dày Dặn, Pho...",266.000₫,https://tka.tiki.vn/pixel/pixel?data=RqqRj3DGo...,-35%,Đã bán 1,aoni
2,"Áo Sweater Nam 5S FASHION Chất Nỉ Cotton, Phom...",253.000₫,https://tka.tiki.vn/pixel/pixel?data=F4p88dMyT...,-35%,Đã bán 1,aoni
3,"Áo Nỉ Nam Cổ Tròn 5S FASHION Nhiều Màu, Vải Co...",259.000₫,https://tka.tiki.vn/pixel/pixel?data=vMU2NwQIo...,-35%,Đã bán 2,aoni
4,Áo Len Cổ Lọ Nam SZone SAL222 Phong Cách Hàn Quốc,129.000₫,https://tiki.vn/ao-len-co-lo-nam-szone-sal222-...,-24%,Đã bán 601,aoni
...,...,...,...,...,...,...
216,"Áo Len Nam Cổ tim phong cách Hàn Quốc, Áo len ...",103.000₫,https://tiki.vn/ao-len-nam-co-tim-phong-cach-h...,NaN,Đã bán 2,aoni
217,Áo len nam cổ lọ loại dày đẹp,199.000₫,https://tiki.vn/ao-len-nam-co-lo-loai-day-dep-...,NaN,Đã bán 1,aoni
218,Áo len nam vải mềm mịn không xù cổ 3 phân body...,159.000,https://tiki.vn/ao-len-nam-vai-mem-min-khong-x...,NaN,Đã bán 1,aoni
219,Áo Len Nam Cho Người Lớn Tuổi FGT03,390.000₫,https://tiki.vn/ao-len-nam-cho-nguoi-lon-tuoi-...,NaN,Đã bán 12,aoni
220,Áo len nam cổ lọ visco 2020 - xuongaolen.com,220.000,https://tiki.vn/ao-len-nam-co-lo-visco-2020-xu...,NaN,Đã bán 1,aoni

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0      199000
1      266000
2      253000
3      259000
4      129000
        ...
216    103000
217    199000
218    159000
219    390000
220    220000
Name: price, Length: 221, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0        3.0
1        1.0
2        1.0
3        2.0
4      601.0
       ...
216      2.0
217      1.0
218      1.0
219     12.0
220      1.0
Name: sales, Length: 221, dtype: float64

In [11]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0        597000.0
1        266000.0
2        253000.0
3        518000.0
4      77529000.0
          ...
216      206000.0
217      199000.0
218      159000.0
219     4680000.0
220      220000.0
Name: revenue, Length: 221, dtype: float64

In [12]:
total = df_all["revenue"].sum()

In [13]:
print("Tổng doanh số aoni: ", total)
print("So mat hang da ban: ", len(df_all["title"])) # san pham da ban
print("So san pham da ban: ", df_all["sales"].sum()) # san pham co luot ban

Tổng doanh số aoni:  558003997.0
So mat hang da ban:  221
So san pham da ban:  2642.0

In [14]:
df_all

,title,price,link_item,discount,sales,category,revenue
0,"Áo Sweater Nỉ Nam 5S FASHION, Chất Cotton Mềm ...",199000,https://tka.tiki.vn/pixel/pixel?data=LdvL4XK5j...,-40%,3.0,aoni,597000.0
1,"Áo Sweater Nam 5S FASHION Chất Nỉ Dày Dặn, Pho...",266000,https://tka.tiki.vn/pixel/pixel?data=RqqRj3DGo...,-35%,1.0,aoni,266000.0
2,"Áo Sweater Nam 5S FASHION Chất Nỉ Cotton, Phom...",253000,https://tka.tiki.vn/pixel/pixel?data=F4p88dMyT...,-35%,1.0,aoni,253000.0
3,"Áo Nỉ Nam Cổ Tròn 5S FASHION Nhiều Màu, Vải Co...",259000,https://tka.tiki.vn/pixel/pixel?data=vMU2NwQIo...,-35%,2.0,aoni,518000.0
4,Áo Len Cổ Lọ Nam SZone SAL222 Phong Cách Hàn Quốc,129000,https://tiki.vn/ao-len-co-lo-nam-szone-sal222-...,-24%,601.0,aoni,77529000.0
...,...,...,...,...,...,...,...
216,"Áo Len Nam Cổ tim phong cách Hàn Quốc, Áo len ...",103000,https://tiki.vn/ao-len-nam-co-tim-phong-cach-h...,NaN,2.0,aoni,206000.0
217,Áo len nam cổ lọ loại dày đẹp,199000,https://tiki.vn/ao-len-nam-co-lo-loai-day-dep-...,NaN,1.0,aoni,199000.0
218,Áo len nam vải mềm mịn không xù cổ 3 phân body...,159000,https://tiki.vn/ao-len-nam-vai-mem-min-khong-x...,NaN,1.0,aoni,159000.0
219,Áo Len Nam Cho Người Lớn Tuổi FGT03,390000,https://tiki.vn/ao-len-nam-cho-nguoi-lon-tuoi-...,NaN,12.0,aoni,4680000.0
220,Áo len nam cổ lọ visco 2020 - xuongaolen.com,220000,https://tiki.vn/ao-len-nam-co-lo-visco-2020-xu...,NaN,1.0,aoni,220000.0

In [15]:
df_all.to_csv("tk_aoni_all_ed.csv")